do not show tab when disabled
twbs/bootstrap pull request #20174
Opened 2016-06-25 21:27 UTC by maxbeatty

attempts to fix #19849

2016-06-25 21:48 UTC, maxbeatty commented
Is it better to fix the @houndci-bot comments or keep with the existing style of the test file?

2016-06-28 07:10 UTC, XhmikosR commented
I guess you can ignore the hound issues.

2016-06-28 17:57 UTC, maxbeatty commented
👍 happy to update the whole file so it passes hound. whatever I can I do to move v4 forward ⏩

2016-08-03 23:57 UTC, maxbeatty commented
attempted to fix @houndci-bot's comments but then tests broke because underlying phantomjs isn't new enough to handle ES2015 like `const` and arrow functions :(

2016-10-12 07:19 UTC, Johann-S requested changes

2016-10-12 07:19 UTC, Johann-S commented on js/tests/unit/tab.js
> +  'use strict'
Why did you remove the semicolon ?

2016-10-12 07:19 UTC, Johann-S commented on js/tests/visual/tab.html
> +  <h4>Tabs with disabled tab</h4>
Why did you add a visuel test in addition of a unit test ? Currently visuel tests are usefull to show something impossible to test in unit tests

2016-10-12 17:48 UTC, maxbeatty commented on js/tests/unit/tab.js
> +  'use strict'
It's been awhile since I did this. most likely just following eslint prompts in atom

2016-10-12 17:48 UTC, maxbeatty commented on js/tests/visual/tab.html
> +  <h4>Tabs with disabled tab</h4>
I felt it was a clearer way to demonstrate and verify the fix

2016-11-28 21:48 UTC, mdo commented
Closing as dupe of #20795.

2016-11-28 21:48 UTC, closed without merging