Fixed progress bar color variables
twbs/bootstrap pull request #20819
Opened 2016-10-01 09:31 UTC by mvdriel

2016-10-01 19:50 UTC, wolfy1339 commented
This is invalid, the variables you're referring to don't exist. Unless you meant the color of the placeholder text ontop of the progress bar

2016-10-01 22:16 UTC, mvdriel commented
@wolfy1339 Sorry, description was missing. I renamed some variables to make their name more meaningful.

2016-10-02 05:12 UTC, wolfy1339 requested changes
Please change those variables in _variables.scss

2016-10-02 09:29 UTC, mvdriel commented
@wolfy1339 I did rename those variables in _variables.scss and in _progress.scss.

2016-10-02 14:41 UTC, wolfy1339 approved these changes

2016-10-03 02:56 UTC, mdo commented
Not too into the variable renaming here, but I'll take a look at the other proposed change here of tying this to the brand primary color.

2016-10-03 02:56 UTC, closed without merging