Add variables for transitions
twbs/bootstrap pull request #21345
Opened 2016-12-14 23:26 UTC by tomlutzenberger

Revision of #21334

See also #21266

2016-12-15 01:49 UTC, Starsam80 requested changes
You didn't have to close the old PR, `git push --force` does exist. If you fix the 2 notes I made, LGTM.

First time doing a GitHub review. No idea how this is going to work

2016-12-15 01:49 UTC, Starsam80 commented on scss/_buttons.scss
> +  @include transition($transition-base);
This should be its own variable: `$btn-transition`

2016-12-15 01:49 UTC, Starsam80 commented on scss/_images.scss
> +  @include transition($transition-base);
This should be its own variable: `$thumbnail-transition`

2016-12-15 15:44 UTC, guylepage3 commented
@tomlutzenberger 
I agree with @Starsam80, you shouldn't keep moving this around from issue to issue to PR to PR. It makes it very difficult for others contributing to follow along.

Again as stated way back in issue https://github.com/twbs/bootstrap/issues/21266 & https://github.com/twbs/bootstrap/pull/21334
> I feel that the naming convention for these variables should match btn names, reducing complexity.

The reason being is that this could limit the number of variables to a standard set. Bootstrap is not created to offer "all" solutions but a couple. It's just a framework. Not a full huge behemoth framework that does everything. IMO.

2016-12-15 22:57 UTC, tomlutzenberger commented
Yes, I have to admit that I haven't thought of the forced push.
I'll fix those 2 things.

2016-12-16 21:31 UTC, Starsam80 approved these changes

2016-12-20 04:33 UTC, merged