Dropdown: remove dependency to role="menu", role="listbox" a and li elements => fix keyboard navigation
twbs/bootstrap pull request #21535
Opened 2017-01-04 17:28 UTC by vanduynslagerp

Re-opened #19864 to fix conflicts as for some reason the head branch of the original PR is marked as "unknown" (Sorry for the inconvenience...)

Per migration documentation in https://github.com/twbs/bootstrap/commit/4d8d8bdab4b0e2931fcf92ce30d772b05a989434:

> - Rebuilt dropdown styles and markup to provide easy, built-in support for `<a>` and `<button>` based dropdown items.
> - Dropdown items now require `.dropdown-item`.

Per https://github.com/twbs/bootstrap/issues/19034#issuecomment-179749958 role="menu" should have been dropped.

This PR:
- Remove the dependency to `role="menu"` or `role="listbox"` and rely on the class `dropdown-menu` instead
- Remove the dependency to the `a` element for the dropdown-item and rely on the class `dropdown-item` instead
- Remove the necessity to wrap dropdown-item in `li` elements

All this problems affected only the keyboard navigation in the dropdown.
With this modification the javascript now matches the markup in the documentation.
The keyboard navigation works again now in [dropdowns](http://v4-alpha.getbootstrap.com/components/dropdowns/).

2017-01-06 20:59 UTC, vanduynslagerp commented
Update unit test with new markup.
Per [comment](https://github.com/twbs/bootstrap/pull/21375#issuecomment-269697431)

2017-01-14 15:31 UTC, jump020305 commented
@all can you help me with this one http://stackoverflow.com/questions/41645884/accessibility-for-select-fields-in-ie11

2017-03-19 02:19 UTC, vanduynslagerp commented
@bardiharborow I see that you added a lot of commit on this branch from v4-dev.
Now the branch contains modifications to the dist file and many other that were not in my PR. Also it fails the travis build. Do you know what happened here ?

2017-03-20 19:52 UTC, mdo commented
This PR is a little wonky right now, but any chance for a review from @Johann-S and @bardiharborow on the core changes at https://github.com/twbs/bootstrap/pull/21535/files#diff-bfe9dc603f82b0c51ba7430c1fe4c558?

2017-03-20 19:56 UTC, vanduynslagerp commented
I merged the last changes from v4-dev and for some reason the diff in the PR show all these changes even though it shouldn't as they are not different from the last v4-dev.
Looking at the diff between v4-dev and my dropdown-keyboard branch show the proper diff: https://github.com/twbs/bootstrap/compare/v4-dev...vanduynslagerp:dropdown-keyboard

2017-03-20 21:27 UTC, Johann-S commented
It's a very good work thank you @vanduynslagerp 👍 

IMO we shouldn't remove dependency to ``role="menu"`` or ``role="listbox"`` for the accessibility but I'm not an expert in this subject we should call the ARIA guy @patrickhlauke 😄

2017-03-20 21:33 UTC, vanduynslagerp commented
@Johann-S the PR remove the dependency to `role="menu"` and `role="listbox"` in the JS selectors so it's consistent with other JS module and rely on classes for selector.
Like other components in Bootstrap, the use of `role="menu"`, `role="listbox"` or `aria-` for accessibility is recommended in the documentation and examples.

2017-04-12 08:57 UTC, Johann-S requested changes

2017-04-12 08:57 UTC, Johann-S commented on js/src/dropdown.js
> +  const REGEXP_KEYDOWN = new RegExp(`${ARROW_UP_KEYCODE}|${ARROW_DOWN_KEYCODE}|${ESCAPE_KEYCODE}`)
Can you change the indent please ?

2017-04-12 14:32 UTC, Johann-S approved these changes

2017-04-12 14:32 UTC, Johann-S commented
Sorry but your branch is out-of-date so can you update ?

2017-04-12 19:47 UTC, Johann-S commented
Again but I arrived too late and your branch isn't up to date and #21802 too

2017-04-13 12:08 UTC, Johann-S commented
Can you notice me when you update your branch ? Or can you allow me to update your branch ? Thank you

2017-04-13 17:07 UTC, vanduynslagerp commented
I gave you permission

2017-04-13 23:34 UTC, patrickhlauke approved these changes
Looks good, and does indeed fix the issue of Firefox/space. Good stuff

2017-04-13 23:37 UTC, merged