Fixed property order, and same line issues
twbs/bootstrap pull request #21545
Opened 2017-01-05 05:10 UTC by matrixfox

Suppressed scss lint minor issues inside of the mixins folder.

2017-01-05 06:19 UTC, wolfy1339 commented on scss/mixins/_hover.scss
> +  &:hover { @content }
I disagree with this change die to the comment in the code.

2017-01-05 14:31 UTC, matrixfox commented on scss/mixins/_hover.scss
> +  &:hover { @content }
Line should be indented 2 spaces, but was indented 3 spaces at line 11 col 1.

2017-01-06 22:16 UTC, mdo requested changes

2017-01-06 22:16 UTC, mdo commented on scss/mixins/_hover.scss
> +  &:hover { @content }
This change should be removed; it's purposefully aligned with the commented out parts above and below it.

2017-01-07 14:19 UTC, closed without merging