Accordion behavior with JQuery interface
twbs/bootstrap pull request #21726
Opened 2017-01-14 21:00 UTC by vanduynslagerp

Fixes #21168

The problem is due to unclear documentation. The `data-parent` has to be set on the collapsible area and not on the trigger.

2017-01-15 01:09 UTC, bardiharborow commented
Please don't check-in changes to the `dist` files, it causes unnecessary merge conflicts.

2017-01-15 14:55 UTC, vanduynslagerp commented
My bad. I removed the `dist` files

2017-03-23 09:09 UTC, Johann-S requested changes
Please can you update this file too : https://github.com/twbs/bootstrap/blob/v4-dev/js/tests/visual/collapse.html

2017-03-23 20:14 UTC, Johann-S approved these changes

2017-03-23 20:15 UTC, merged