Dropdown: refine handling of keydown in input and textarea
twbs/bootstrap pull request #21802
Opened 2017-01-21 05:30 UTC by vanduynslagerp

Fixes #21366

This PR handle better the key inputs in `input` and `textarea` within `dropdown` and `dropdown-menu`.
As a side note, keyboard navigation is current broken and the fix is here #21535. 

**This PR will be fully working only when #21535 lands.**

Here is the new behaviors.

#### `input` and `textarea` within a `dropdown-menu`:
- **Escape key:** dropdown behavior => close the menu
- **Arrow down:** default behavior (move to the cursor to the end of the text in the `input` or `textarea`)
- **Arrow down:** default behavior => move to the cursor to the beginning of the text in the `input` or `textarea`
- **Space key:** default behavior => enter a space character in the `input` or `textarea`
- **Other key:** default behavior => enter the character in the `input` or `textarea`

#### `input` and `textarea` within a `dropdown` but outside of the `dropdown-menu`:
- **Escape key:** dropdown behavior => close the menu
- **Arrow down:** dropdown behavior => put the focus on the first/next `dropdown-item` in the menu
- **Arrow up:** dropdown behavior => put the focus on the first/previous `dropdown-item` in the menu
- **Space key:** default behavior => enter a space character in the `input` or `textarea`
- **Other key:** default behavior => enter the character in the `input` or `textarea`

2017-04-10 09:29 UTC, Johann-S approved these changes
LGTM 👍 

But we have to review this #21535 first

2017-04-12 08:58 UTC, Johann-S commented
Can you update your branch @vanduynslagerp ? Thank you 👍

2017-04-14 07:56 UTC, Johann-S commented
Can you fix the conflict @vanduynslagerp ? please 👍

2017-04-29 16:50 UTC, Johann-S commented
Your unit test failed because of the lack of `.dropdown-item` and `li` isn't focusable without `tabindex="1"`

With this HTML everything is fine : 

```html
      <ul class="tabs">
        <li class="dropdown">
          <input type="text" id="input" data-toggle="dropdown">
          <ul class="dropdown-menu" role="menu">
            <li id="item1" tabindex="1" class="dropdown-item"><a href="#">Secondary link</a></li>
            <li id="item2" tabindex="1" class="dropdown-item"><a href="#">Something else here</a></li>
            <li class="divider"/>
            <li tabindex="1" class="dropdown-item"><a href="#">Another link</a></li>
          </ul>
        </li>
      </ul>

2017-04-29 16:51 UTC, Johann-S requested changes
Your unit test failed because of the lack of `.dropdown-item` and `li` isn't focusable without `tabindex="1"`

With this HTML everything is fine : 

```html
      <ul class="tabs">
        <li class="dropdown">
          <input type="text" id="input" data-toggle="dropdown">
          <ul class="dropdown-menu" role="menu">
            <li id="item1" tabindex="1" class="dropdown-item"><a href="#">Secondary link</a></li>
            <li id="item2" tabindex="1" class="dropdown-item"><a href="#">Something else here</a></li>
            <li class="divider"/>
            <li tabindex="1" class="dropdown-item"><a href="#">Another link</a></li>
          </ul>
        </li>
      </ul>

2017-10-18 03:42 UTC, mdo commented
@Johann-S I pushed the class name change but tests are still failing. Any chance you could take a look?

2017-10-26 08:37 UTC, Johann-S commented
Superseded by : #24557

2017-10-26 08:37 UTC, closed without merging

2017-10-26 09:17 UTC, XhmikosR commented on js/src/dropdown.js
> +      //  - If key is other than excape
`escape`