cover popover arrow when title is present
twbs/bootstrap pull request #22436
Opened 2017-04-13 14:48 UTC by IdanCo

## Summary
Following issue #22432 and PR #22433 , change to arrow color of popover when title is present -
![image](https://cloud.githubusercontent.com/assets/10364499/25009865/e478bdfc-2070-11e7-9113-af739551c1d9.png)

See it in action here - http://jsbin.com/tubuwu/edit?html,output

## Before
Arrow color was the same, regardless of the presence or absence of a title in the popover

## After
Arrow color is now dependent on the presence or absence of a title in the popover

## Technical
I've used an existing pseudo element of the title, originally intended to fix a gap between the popover and the arrow, and redesigned it cover the arrow all together with the title's background color.

2017-04-13 14:50 UTC, Johann-S commented
X-Ref : https://github.com/twbs/bootstrap/pull/22433

2017-04-13 14:54 UTC, Johann-S requested changes
Please can you fix that : https://travis-ci.org/twbs/bootstrap/jobs/221759321#L284

2017-04-13 15:17 UTC, IdanCo commented
Fixed 👍

2017-04-14 07:20 UTC, Johann-S approved these changes

2017-04-14 08:49 UTC, IdanCo commented
To be honest, this solution (or the previous one for that matter) is not the best i can think of. No doubt it works, but it lacks the simplicity and cleanness we've come to expect from Bootstrap. I'd like to suggest two alternatives -

## 1. Use `has-titlte` class
Since javascript is already injecting the popover, we can add ([here maybe](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/popover.js#L113)) a single line to toggle between the states -
```js
$tip.toggleClass('has-title', this.getTitle())
```
And the with a single line of css (instead of the [current dozen](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_popover.scss#L93)) set the arrow color:
```sass
&.has-title::after {
 border-bottom-color: $popover-title-bg;
}
```

## 2. Replace pseudo element with a real element
If the arrow will be an element instead of a psudo-element, it will be possible to use the [sibling selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors) to target the arrow like this -
```sass
.popover-title + .popover-arrow::after {
  border-width: $popover-arrow-width;
}
```
This [cannot be done](http://stackoverflow.com/questions/7735267/can-i-target-a-before-or-after-pseudo-element-with-a-sibling-combinator) with a pseudo element. I realize pseudo element for arrows were [intoduced recently](https://github.com/twbs/bootstrap/pull/17238), but since the markup is injected by js anyway, I don't see what is gained by using pseudo element, but this is one example of what is lost.

Thoughts?

2017-04-16 20:51 UTC, mdo commented
Thanks, but we'll leave it as-is without the extra element or color change. The white arrow is intentional.

2017-04-16 20:51 UTC, closed without merging

2017-04-18 09:21 UTC, IdanCo commented
Sounds good to me, i'll just recommend in that case to remove [this rule](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_popover.scss#L93) completely.