v4 Color update
twbs/bootstrap pull request #22551
Opened 2017-05-01 23:43 UTC by mdo

While working on the forms update, I noticed we have quite a few ways of reassigning variables for our color system. The `$brand-` variables have been around for awhile as a support system for semantic naming, but honestly, it's an unhelpful abstraction. Not everyone's primary color is blue or their error state red.

This PR aims to drastically improve the power of our colors, simplify code by removing the `$brand-` and `$state-` variables, and increase the number of component variants and utility classes. This has been built in such a way that we can easily expand or add new maps for color shades after v4 ships. I went down a few paths the last couple weeks and ultimately decided this was the one of least resistance given a shorter window.

More specifically, this:

- Removes the `$brand-` variables, replaced by `${color}` variables. For example, instead of `$brand-primary` it's `$blue`.
- Removes the `$state-` variables as only alerts and list groups were using them. Fixes #22175. (For those following along at home, this is the start of the color variable rabbit hole. :laughing:)
- Renames all component variants from success, info, warning, and danger to their color counterparts.
- Fixes #21311 by adding `.btn-gray-dark` variant.
- Closes #19792 as a won't fix by removing card variants for background and border utils.
- Fixes #18119 by adding a color contrast mixin.
- Closes #22062 and #22363—no need for customizing the color of badges when there are text color utilities.
- Updates buttons to use the `$colors` Sass map to generate more button variants.

More still to come, including:

- [ ] Finish updating Options docs
- [ ] Revamp the colors to create an actual color scheme
- [ ] Ideally improve contrast ratios
- [ ] Consolidate and standardize variant names

See #18462 for first foray into color palette. That PR failed as it started with the brand and state colors vs abandoning them completely for a clearer and more customizable system.

2017-05-02 04:50 UTC, mdo commented
Tweaking colors a bit...

<img width="870" alt="screen shot 2017-05-01 at 9 49 04 pm" src="https://cloud.githubusercontent.com/assets/98681/25604428/21c78954-2eb8-11e7-988a-ad514143c3eb.png">

2017-05-02 07:42 UTC, gseregni commented
It will be harder to create reusable themes considering that the color will be expressed in the class name in html. (no more bootswatch and similar) I'm not sure it was an unhelpful abstraction.

2017-05-02 08:03 UTC, gseregni commented
Since you are touching colors, i propose again to introduce 2 vars for text color (i.e. $text-color-dark and $text-color-light) that are applied automatically to text-color property. (Using their luma difference with backgournd)
It would help to keep text readable and consistent while changing backgrounds.

2017-05-02 17:42 UTC, pat270 commented
I'm in agrement with @gseregni, having the color in the class name makes it difficult to theme applications where we don't have control over the markup. Not everyone's primary color is blue or error state red, but generally, everyone has a primary color and error state. Semantic naming made it easier to change colors globally across components. One day our primary color might be blue, but the next day it's red. It's easier to remember where all our primary buttons are versus having to remember what our primary color was the day before.

I'm actually for minimizing the number of colors included in v4, since there are an infinite amount of color palettes you may want to use. Help us create awesome accessible reusable cross browser compatible components and let us theme it to match our needs!

With that said, it looks like we can go back if we like by defining the `$color` sass map to be whatever we want, which is great! Just concerned about some of the variant CSS bloat.

2017-05-03 01:47 UTC, mdo commented
> It will be harder to create reusable themes considering that the color will be expressed in the class name in html. (no more bootswatch and similar) I'm not sure it was an unhelpful abstraction.

I don't see how this PR prevents themes from being created.

- There are now variables and a Sass map. This allows more fine grained control and customization, as well as easier class generating from the map.
- There are twice as many colors available, meaning more pre-built modifiers for many components.
- It's all Sass maps and variables, so you can quite easily replace the default values with your own.

2017-05-03 08:02 UTC, gseregni commented
@mdo The problem it's not about creating custom themes (Sass color map it's ok), It's about having more themes that you can apply to the same page without touching html.  Using the new rules  you'll end up having colors written in HTML not CSS, so you won't be able to switch from one theme to another. With semantic-color-naming instead this was trivial.

2017-05-03 13:26 UTC, marcsoler commented
@gseregni If I'm not mistaken, by this PR will not affect HTML at all but rather offer customizable themes similar to Google Materials idea. We had the navbar and navbar-inverse class markup. This PR could avoid this and make it more simpler and versatile

2017-05-03 15:46 UTC, jipexu commented
if i understood... we lost the context class (danger, default, warning ...) for some color name in html ...If we compare
- a semantic contextuel class (danger, default, warning ...) with color defined by the css 
- a semantic color class (green red ....) class with color defined by the css
for me it seems that in the second case we lost a great information in the structure of the html

 .... & heavy work to rewrite entire html of some  project  &...

or i dont understand ?

2017-05-03 17:49 UTC, bogdaniel commented
@gseregni haven't used a theme generator .. and based on what i read the theme generator only generates a custom bootstrap version ( css file ) so it modifies just some colors and stuff .. shouldn't be easier now to generate a color palette .. ? I mean they will just put there 5 variable generate the css for them and have a text added to use your chosen colors you have the following classes.. =D simple as that :-? . also you can always have your own mixin to create

2017-05-03 20:18 UTC, gseregni commented
@bogdaniel I develop a popular Bootstrap builder and, believe me, for my use case this PR is a bad thing. Maybe for you and many others not. it's ok.

2017-05-03 20:22 UTC, gseregni commented
@marcsoler yes the use of a color map in sass make everything definitely more versatile. And it's absolutely welcome. My concern is just about the choice of choosing "explicit palette" (btn-red) instead of semantic palette (btn-primary) as default.

2017-05-04 09:36 UTC, patrickhlauke commented
have to agree that moving away from abstract names such as `warning`, `danger`, `success` to specific `red`, `orange` etc seems rather backwards to me.

2017-05-04 14:32 UTC, jipexu commented
yes this PR is great for a big choice of colour and the scss mechanic 
but i am really affraid for the lost of the context class because it's means we lost consistancy
for example 
in our cms we use theme and skin (to allow admin or user to choose) ,
so the html from the php is always same and contextual class (defined by dev) allow to apply different style with great coherence just because is contextual ...
if not a btn-blue will stay for ever a btn-blue in html 
and even if we change for pink in scss it will become a btn-blue pink ...

so is there a way to keep both :  consistancy contextual class and  this great new possibility of colours ??

2017-05-04 15:47 UTC, rafalp commented
Yeah, this will be brainbreaking for endusers of those of us who build default or base themes for their projects with Bootstrap with assumption that those themes will be further customized via css changes.

2017-05-04 19:14 UTC, Thomas--S commented
I don't know if this was already suggested, but how about this?

1) Having color pallets named by the color name (as suggested in this PR).

2) Having the semanitc color names (like the previous behaviour). 

Then there could be the following code (only an example):

```sass
// Color variable definitions by color name
$red = #ff0000;
$green = #00aa00;
$blue = #0000ff;
$orange = #ff9900;

// Semantic color definitions
$error = $red;
$success = $green;
$brand-primary = $blue;
```

Then you can use both, the color-name based CSS classes (for things were it is about this special color) _and_ the semantic name (when it comes about semantic coloring).

2017-05-04 21:50 UTC, dvmuccillo commented
I agree with @Thomas--S.
Keeping the current contextual classes and adding the pallet proposed in this PR seems the best solution.

2017-05-05 05:13 UTC, LarryAzevedo commented
I agree.  This change would make theming and updating a nightmare (which many of us at my work need to do).  Please reconsider @mdo.

2017-05-06 08:20 UTC, BrokenCrust commented
I agree with @Thomas--S.  The is no harm in adding a wide colour palette but only if it is in addition to, not a replacement for the current semantic palette with a default assignment of colours as now.  `btn-red` and alike essentially puts specific design elements back into the html which doesn't seem like good practice.

Is it better to have `btn btn-red btn-big btn-bold btn-rounded btn-text-white`, or just `btn btn-danger`?

If the semantic palette dispersed I doubt I would swap to the other way, but add it back myself in css.

I'm not sure what problem this is solving even.  Why did a PR about branding swoosh out to encompass buttons?

2017-05-06 18:51 UTC, acasar commented
+1 for keeping the contextual classes. I have several templates where i only adjust the "brand-*" variables to customize the template for a particular client. With this change I'd have to make significant changes to the HTML markup instead.

2017-05-07 20:21 UTC, ncoden requested changes

2017-05-07 20:21 UTC, ncoden commented on scss/mixins/_background-variant.scss
> -}
Because no one is using Sass but you... No one could need this mixin... --'

2017-05-07 20:21 UTC, ncoden commented on scss/utilities/_background.scss
> +}
```sass
@each $color, $value in $colors {
  @include bg-variant('.bg-#{$color}', $value);
}
```

2017-05-07 20:38 UTC, ncoden commented
@mdo 

Our head right now in the [Foundation](https://github.com/zurb/foundation-sites) team: 😭 

Please take a look at https://github.com/zurb/foundation-sites/issues/9671. "Semantic colors", "DRY", "maintainable", "customizable"... everything has been said there.

2017-05-08 05:06 UTC, IamManchanda commented
Excuse me... This fixes #21311 ??
I mean what?? .... I never wanted this way!

2017-05-09 20:18 UTC, mabar commented
This PR brings to my mind times when I had $orange. And $orange was blue.
With this change we will simply start to hacking it. When colors in stylesheets are changed so no one want to change template the same way. Abstraction is really helpful here. Classes should have meaning. And not be HTML version of CSS definition. Who would like .display-block, .left-10px etc. classes?

Maybe it's time for colors management tool like [that](https://github.com/oddbird/accoutrement-color)
No pollution in global scope and meaning-full names can be just a reference on specific color.

2017-05-14 18:51 UTC, wilsonge commented
As the @joomla 4 release lead, I'd like to add my concerns about the effect this will have on the template ecosystem using bootstrap. Many of our templates have different colour themes where they simply swap out CSS files based on a simple parameter. As has been stated this ends up with all the problems mentioned above. For what it counts for I'd strongly urge reconsideration of this approach.

2017-05-14 19:37 UTC, brianteeman commented
Who needs semantic class names when you can have a green class that outputs yellow - it's obviously much better said every designer never

2017-05-23 14:58 UTC, fulldecent commented
This PR reduces the ability of blind users to read web pages and I do not support it.

According to BuiltWith, 20% of the top million websites use Bootstrap. Therefore Bootstrap-HTML is an important flavor of HTML. https://trends.builtwith.com/docinfo/Twitter-Bootstrap

Currently, the semantic value of `.text-danger` and `.alert-danger` is well known from reading the HTML even if you ignore the CSS. Therefore it is very reasonable for a screen reader to add certain alert sound before reading `.*-danger`. Similarly, `.text-muted` can be read with a lower intonation (just like parenthetical text). And this will be helpful for blind readers. They will understand the context and the meaning.

`.text-red` is less meaningful.

2017-05-23 15:04 UTC, rafalp commented
Can you name one screen reader that actually intones things differently based on css classes?

2017-05-23 15:55 UTC, patrickhlauke commented
> This PR reduces the ability of blind users to read web pages and I do not support it. [...] it is very reasonable for a screen reader to add certain alert sound before reading `.*-danger`.

Note that no screen reader or other assistive technology does this. What matters are semantic HTML elements. class names are completely ignored by AT.

2017-05-23 16:39 UTC, fulldecent commented
@rafaelstz Google uses it. Not a screen reader for humans. But it is a tool that extracts semantic meaning from web pages.

2017-05-23 16:42 UTC, rafalp commented
@fulldecent Can you share that tool for use to see ourselves? Remembring how heavy google is on web schema, I'm finding it hard to buy.

2017-05-24 07:29 UTC, bbmatt commented
MDO : "this is the start of the color variable rabbit hole. " - no kidding, given the amount of comments.
I don't really see a problem with this change. For anyone who has been using Bootstrap actively over the years, many may agree that the brand color concept never really worked. (others may differ)
Semantically, btn-blue as a *class* name makes as much sense as btn-success, as you shouldn't be leaning on class names to give semantic meaning anyway - HTML should be used for this!
In some cases, you can end up using the -success, -danger, -warning for elements that are in no way related to that concept.
In fact, the whole concept of success, danger, warning etc. in class names has always seemed to me to just get in the way.

2017-05-24 07:51 UTC, patrickhlauke commented
> Semantically, btn-blue as a class name makes as much sense as btn-success, as you shouldn't be leaning on class names to give semantic meaning anyway

of course i can also name my classes `.btn-chicken` and `.btn-sdgjicositjc`. but i'd say primarily this is about not confusing developers. and naming something with a particular name only to then have that result in a completely different style is...confusing to developers. since there is indeed no actual meaning to the class name itself, i move for them to remain the same they were before.

2017-05-24 07:51 UTC, brianteeman commented
> Semantically, btn-blue as a class name makes as much sense as btn-success, as you shouldn't be leaning on class names to give semantic meaning anyway - HTML should be used for this!

Yes it makes semantic sense if the colour that is displayed is blue. But as already stated by many contributors here who create re-usable and customisable themes it will result in btn-blue being displayed in any colour of the rainbow. So no semantic sense there at all. 

Hey why even bother having btn in the class name if only html should be used for semantic meaning why not call it xyz-blue. Sorry that might sound facetious but its the logical conclusion of your statement.

2017-05-24 10:01 UTC, bbmatt commented
> Hey why even bother having btn in the class name if only html should be used for semantic meaning why not call it xyz-blue. Sorry that might sound facetious but its the logical conclusion of your statement.

I should probably elaborate. Semantically it means something to *coders*. That's fine. 
In this instance, btn-blue means it's a blue button. btn-success means it's a, erm, a successful button? 
If your btn-blue ends up being orange, that's your call as a coder. 
Bootstrap as a framework is easy to extend. Just create your own custom button scss file and use the mixin to generate your own set of btn classes. Heck, bring back btn-success, btn-danger etc. if that's what you want. ;)

2017-05-24 10:25 UTC, brianteeman commented
@bbmatt you assume that everyone using bootstrap for their web site is a coder. They are not. The success of bootstrap is because of the customisability that coders can build into their templates without needing to change the markup.

As stated by @wilsonge https://github.com/twbs/bootstrap/pull/22551#issuecomment-301331990 this change if accepted will seriously question the usage of bootstrap with joomla and its suitability for being the default.

2017-05-24 15:23 UTC, Vercadium commented
People need to remind themselves who the majority of people are that use this framework. When you take the stance of the people likely to comment here or contribute to the project you invite a sample bias; these individuals are likely to be experienced and understand reasoning such as *"It's all Sass maps and variables, so you can quite easily replace the default values with your own"*.

In reality, I would wager that the bulk of Bootstrap users are clicking "download", dumping in the minified assets and building on top of mark-up from boilerplate template X; maybe with a splash of mark-up copied from the Bootstrap documentation (or more likely Stack Overflow). Hell, even that might be an rose-tinted view.

You might say that's their problem, but when we have the choice to satisfy everyone (maybe with a little compromising) and choose not to, I believe it's ours.

I understand that we already have issues with our seemingly semantic naming even if it accommodates easy "skinning" of Bootstrap - if someone wanted a red colour, they might use "-danger" even if they aren't trying to convey that. Obviously that's bad, but **why is this an argument for removing that abstraction rather than improving it?**

When you remove abstraction by naming a class name (which appears in HTML) after the value of a property (which appears in the CSS) you diminish the benefits of isolating the presentation layer, creating tighter coupling between the styles and mark-up.

2017-05-24 19:19 UTC, bbmatt commented
> In reality, I would wager that the bulk of Bootstrap users are clicking "download", dumping in the minified assets and building on top of mark-up from boilerplate template X; maybe with a splash of mark-up copied from the Bootstrap documentation (or more likely Stack Overflow). Hell, even that might be an rose-tinted view.

Yep, that was me, 7 or 8 years back. This is such a moot point. I would've happily used btn-blue or btn-green back then. I wanted a color on the button I was using. Green means "go ahead", red means "danger" for those that are able to see color. 

It seems to me that this is more about backward compatibility than anything else, not wanting to let go of what was an opinionated framework option in the first instance. 

The context of a button action is in the text that button displays. "Submit", "Back", "Cancel".
Color is an added benefit. Red is a warning, Green is a 'go' - btn-green. btn.red.

2017-05-25 17:35 UTC, jipexu commented
Hi

- in a CMS context 

the part of this PR who give up of the context class, is really a bad thing ...
as brianteeman wrote
> create re-usable and customisable themes
> The success of bootstrap is because of the customisability that coders can build into their templates without needing to change the markup.

This is one of the main benefit of the couple FW/CMS and precisely it is only possible with this type of class ...

why ?
Because all this can be done by the webmasters (who are very often poor coder and far from the use of SASS ...)
Even if some can use sass to make their beautifull css do you think they will rewrite the entire CMS  to NOT have a btn-blue yellow ... an alert-red black...?

So in most case the entire project will have a very disapointed source code  ... for the CMS developpers it's very frustrating

So one more time for the good alchemy (easy customisability at all level of 'dev') between a framework and a CMS
we need this class !
The part of this PR who give up of the context class is as the opposite side of this ...
Of course all is possible ! but to have what at the end in the most of the cases :  a btn-red blue ?
no need use FW to do this ! 

@bbmatt
backward compatibility is also one argument against this PR (the part who give up the context class) sure ! but far to be the main argument ....

> The context of a button action is in the text that button displays. "Submit", "Back", "Cancel".
Color is an added benefit. Red is a warning, Green is a 'go' - btn-green. btn.red.

and this explanation let me very skeptical ..

sorry for my english sometimes short to express precisely some idea ...

2017-05-25 19:15 UTC, bbmatt commented
> you assume that everyone using bootstrap for their web site is a coder. They are not. The success of bootstrap is because of the customisability that coders can build into their templates without needing to change the markup.

There's no assumption about it. If you are applying bootstrap to a project, I really hope you are a coder. The very act of creating templates implies that you are creating code. 
I view bootstrap as a set of sensible defaults, but I don't view it as the be and end all of how I create websites. I view it as a framework. 

It is extendable, modifiable. 

You don't need sass / less to modify the code, just the ability to use a text editor and some curiosity about html/css coding. With a few lines of code, you can override anything.

There's a great deal of 'preciousness' knocking about here, just because mdo has decided to use colors in class names. Big whoop. World hasn't ended.

2017-05-25 19:20 UTC, brianteeman commented
> There's no assumption about it. If you are applying bootstrap to a project, I really hope you are a coder. The very act of creating templates implies that you are creating code.

I am talking about USING not creating

2017-05-25 20:52 UTC, LarryAzevedo commented
I don't know about everyone else but one of the **first** things I learned about CSS class names was that it's bad practice to put a color's name into the class.

I ignored that advice on a particular project and sure enough, it came back to bite me in the butt.  

History teaches us.

2017-05-26 06:34 UTC, bbmatt commented
All the elements that this proposed change pertains to, have a *parent* class. The applied 'color' style is a modifier. 
I completely agree that binding your html classes to color or any other css attribute isn't a good idea for the *parent* class, but this isn't the case in this proposal, it's on the modifier. Ok, so alert-warning is more descriptive than alert-orange, but what if I want an orange alert that has nothing to do with a warning? 
A green badge that has nothing to do with 'success' ? 

We end up binding these elements to concepts - in a code viewing sense - that may or may not apply to them.

2017-05-26 07:59 UTC, patrickhlauke commented
For people who vehemently defend the idea that class names don't matter and there's no semantic value in them (to developers)...in that case, it wouldn't make a difference if we kept the current class names rather than changing them to use color names, no? Since they can be arbitrary, there's no harm either way...

2017-05-26 08:02 UTC, patrickhlauke commented
> In fact, I want to make all brand-success colors bright pink, so now all my success modifiers show bright pink backgrounds. This may suggest success to some people, but most expect success to be green?

so with the new model what would you do? override the color of `.alert-green { color: DeepPink; }`? is that better than redefining `.alert-success { color: DeepPink; }`?

2017-05-26 08:07 UTC, mabar commented
@bbmatt  I would like to see in docs that 'success' is for successful operation and not for green. Writing one selector for different color on specific place is not much work.
But for cms developers this isn't good. Classes with -primary, -success etc. would be written everywhere. Much more code if we want our templates to be universal. And if anyone like to create new theme so that developer must know all our classes.
Moreover this solution is only partial in what you wanted to do. Eg. [forms](https://github.com/twbs/bootstrap/pull/22551/files#diff-55562cf68df408880356390d08c7a3cb) are highly coupled with specific variables. And it's absolutely not easily overwriteable as these classes are added by JS and by server. So we will must change our client and server scripts to use different colors? If we don't want to do that so in $green will be blue.

2017-05-26 08:46 UTC, bbmatt commented
> so with the new model what would you do? override the color of .alert-green { color: DeepPink; }? is that better than redefining .alert-success { color: DeepPink; }?

No, I'd make my own modifiers as needed & frequently do.

> So we will must change our client and server scripts to use different colors? If we don't want to do that so in $green will be blue.

I guess this is the danger of tying your CMS templates to a universal css framework. I completely get where you are coming from - this small change in bootstrap would result in a either a large change for your CMS. OR you could 'patch in' a CSS override, which would be very quick to do (re-introduce the classes you needed), 10 minute job. 

The thing is, you can't expect an independent framework that is used across countless projects, to ensure backward compatibility with your own project.

2017-05-26 08:59 UTC, patrickhlauke commented
> No, I'd make my own modifiers as needed & frequently do.

so the change (or no change) to the core BS classnames wouldn't actually affect you then. so no problem keeping them as they are now, which seems to make more sense for other devs, at least based on the conversation here so far?

2017-05-26 08:59 UTC, brianteeman commented
This is NOTHING to do with backwards compatibility at all. 
This is about ensuring that the majority of bootstrap users are able to continue using bootstrap

2017-05-26 09:00 UTC, bbmatt commented
> For people who vehemently defend the idea that class names don't matter and there's no semantic value in them (to developers)...in that case, it wouldn't make a difference if we kept the current class names rather than changing them to use color names, no? Since they can be arbitrary, there's no harm either way...

Class names do matter, of course they do. I would never deny that. In this case, we have a parent class & we have a modifier. What is being proposed here is to change a very prescriptive set of modifier names to something far more generic - color. What else would you use that isn't prescriptive? As soon as you start tying more emotive nouns to classes, you kinda limit their semantic use for coders.

2017-05-26 09:10 UTC, mabar commented
Re-using code is what every developer should want. Eg. login form can be used without changes for eg. 10 websites. And when I have 10 themes on all of them so 100 modifications are needed to write? When I write only one before? Annoying. For cms developers and for developers using this css too. 

My cms is nout bound to bootstrap. But is used as default. And default should be easy. No-one will continue with building complex systems with bootstrap. Large systems as joomla are depending on reconfiguring bootstrap is only what is required to change look. Rewriting html, php and js to change look is simply stupid.

Every framework developer in any language would say abstraction is better.

2017-05-26 09:13 UTC, bbmatt commented
> Every framework developer in any language would say abstraction is better.

Sure, but in this case, the abstraction has meaning that may not be wanted! 
It isn't abstract enough. It prescribes the nouns success, warning, danger and info whether you want them or not!

2017-05-26 09:21 UTC, mabar commented
Think in context of all used languages. Biggest problem are forms. Not buttons. In current state you can use parrent button class and apply modifier in same way as with this PR. If I'll forget it's problematic in cms to replace primary with green etc. so problem is still the same. Forms are highly coupled with specific colors. Everyone must reinvent wheel. And developers which come to this code must learn, how was wheel reinvented.

2017-05-26 09:26 UTC, mabar commented
And if current abstraction is not good enought - it should be improved. Not removed.

2017-05-26 09:41 UTC, blikblum commented
> In order to change the colors in the framework, a coder would be expected to know how to do this and how to use preprocessing. If they wanted to make btn-green purple, surely they could just as easily create a btn-purple modifier? Or maybe btn-signup?

This is not how themes with color variants work.

Example: You have a button with class btn-success that by default is blue

The theme also provides a variant where buttons with such class have pink color. This is possible without changing the markup, just changing to a CSS file where btn-success has a pink style

With the proposal the button would have a btn-blue class by default. To provide a pink color variant that does not require markup change the theme author would need to create a CSS rule where btn-blue have pink style.

The theme author could create your own semantic classes with the drawback of increasing the cognitive load of theme user that has to learn new markup instead of using his BS knowledge.

Also if this will require at least theme and CMS authors to create your own rules where is the usefullnes​ of it?

BTW: look at wrapbootstrap and themeforest to see how important is theme market for BS users

2017-05-26 11:51 UTC, mbabker commented
I honestly feel like this change favors developers and custom theme designers over organizations that are distributing reusable themes or platforms like Joomla where Bootstrap was standardized as the default UI framework (a decision which helped to drive a fair majority of our templating ecosystem to standardize on Bootstrap as well).  Sure, for those of us with the savvy and skill to make the changes, editing some HTML to change `blue` to `green` may be easy, or for theme distributors adding a "middle layer" on top of Bootstrap to retain a set of more semantic (and therefore generic and reusable) can be done, but this hurts end users in a space where they aren't as technically savvy and are either going to be the ones hacking their CSS to `.blue { color: green; }` or it will be harder for them in the case of a CMS environment to keep their template up-to-date with the parent source because they will have to make an excessive number of changes to change a color attribute.

As @wilsonge hinted to, and as I'm now saying as Joomla's current production lead, we are watching this with a vested interest as this change could require us to re-evaluate our UI defaults.

2017-05-26 11:54 UTC, bbmatt commented
> drawback of increasing the cognitive load of theme user that has to learn new markup instead of using his BS knowledge.

I think we should give credit for people having enough curiosity and ability to understand a minor amend to modifier classes!

> Also if this will require at least theme and CMS authors to create your own rules where is the usefullnes​ of it?

Experimentation, expression, customisation, expandability, learning. Using a framework and extending on it to suit different needs?

This is one of those discussions that I guess is purely a matter of personal choice. I see this proposed change as being beneficial - getting rid of prescriptive modifier class descriptions. Others see it as a terrible crime against css, daring to use color names in modifier classes - shock! horror! Others see it as something that will result in changes to their own projects.

2017-05-26 12:38 UTC, xcartmods commented
Just get on with it, or Foundation beckons...

2017-05-26 12:57 UTC, patrickhlauke commented
feeling i'm getting the more i hear the discussion:

- this change will benefit authors who used the warning, success, etc modifiers not for their meaning, but to achieve a certain look (e.g. using success because it's green, not because it indicates success - rather than overriding the color of whatever more appropriate/meaningful modifier class name in their own additional styles)
- this change will require theme authors and people wanting to easily reskin/change the default theme to modify their HTML output to use different classes / assign new classnames and compile their own bootstrap styles

so there are two sides, both to some extent with merit. i still heavily lean towards not changing the classnames. @mdo, after throwing this hand grenade of a PR...any thoughts? because this has the potential of turning into a never-ending discussion otherwise ;)

2017-05-26 13:03 UTC, brianteeman commented
And it will disadvantage any cms who used the warning, success, etc modifiers for their meaning

2017-05-26 14:06 UTC, browner12 commented
I agree with you @patrickhlauke, there is definitely merit to both sides.  For me as a developer, my mindset was always exactly what you listed. I never thought, "I need a success button", I thought "I need a green button", so the semantic class names lost their true meaning.

Is the simple solution to include both options?  Make the changes to allow developers to have more flexibility, and retain the semantic names for the theme developers?  Does this cause too much bloat, or is there some other downside to this?

2017-05-26 15:51 UTC, blikblum commented
>>    drawback of increasing the cognitive load of theme user that has to learn new markup instead of using his BS knowledge.

> I think we should give credit for people having enough curiosity and ability to understand a minor amend to modifier classes!

Is not about curiosity or ability to change the markup. In an practical example all admin templates i've found ([admin lte](https://adminlte.io/themes/AdminLTE/pages/UI/general.html), [propeller](http://propeller.in/admin-theme-detail.php)) uses `alert-danger`, `alert-success` etc to style alerts. When start using such themes those familiar with BS already know how use them. There are thousand of users of such components, see the sell stats in market places

With the change each theme author can create it own class name abstraction, e.g. `alert-confirm`, `alert-note`, `alert-error`, others may recreate the old classes names and finally there will be those that will use `alert-green`, `alert-blue`. 

> This is one of those discussions that I guess is purely a matter of personal choice. I see this proposed change as being beneficial - getting rid of prescriptive modifier class descriptions

Is not about personal changes, in this discussion there are tons of technical arguments.

Also, about being prescriptive this is IMO one of the Bootstrap selling points. When i was evaluating a CSS framework i looked Foundation but, although technically good, it does not provide ready to use components to create a UI. With Bootstrap + custom themes i can leverage a good looking UI without the need to implement my own unique design from scratch.  I believe a significant part of BS users fall in this category.

2017-05-29 09:36 UTC, bbmatt commented
Reading through this thread, it struck me that obviously there's a lot of self-interest here. Theme developers & users, CMS developers. Absolutely nothing wrong with that - these changes would incur a fair amount of change.

I had a quick look through the propeller admin theme that blikblum linked too. Sublime text reports 77 entries for -success. Not all of those have been removed in this proposed PR (has-success for instance). So sure, lots of amends to CSS and HTML. 

**However, the glaring elephant in the room for these themes & CMS's, is that the move to Bootstrap 4 is going to incur far more than just the proposals this particular PR would create.**

https://github.com/twbs/bootstrap/blob/4a8728d54c2a89b923ca019f8daf497927aeccdd/docs/migration.md

Boom. The migration.md document. 

The changes here are far more sweeping than dropping a few modifier classes. 
In many cases, a judgement call will need to be made whether to attempt to "patch in" the modifications or to rewrite. That depends how modular the implementation of bootstrap is in each instance. 

To return back to the propellor theme as an example, this theme has implemented it's own card solution, pmd-card. So the developers have to decide whether to keep this or to move over to the bootstrap 4 card when they migrate. 

That is just one migration issue the theme has to face.

So really, the talk about how this minor amend to modifier classes doesn't amount to a whole lot when panels, wells & thumbnails are replaced by cards, glyphicons are gone and numerous other changes have happened. 

... waits for the inevitable downvotes ... ;)

2017-05-29 09:42 UTC, brianteeman commented
@bbmatt Sorry but you are still not understanding the issue. All the b/c changes such as panels, wells and thumbnaills are one time changes to the theme to make the theme compatible with bs4. The proposal under discussion here will effect every theme for all time as stated by multiple people multiple times

2017-05-29 09:46 UTC, bbmatt commented
I completely understand the issue and really don't think it's a big deal at all. These are just *modifier* classes. That's it. Sure, people have learned these patterns and have come to expect they are in place, but they will also have used panels, wells and icons.

2017-05-29 09:51 UTC, patrickhlauke commented
@bbmatt i think you made your point. others have also made their point that they'd prefer modifier classes that aren't tied to a color name. i guess we'll have to agree to disagree here instead of going around the same circular discussion.

2017-05-29 10:33 UTC, mabar commented
As Patrick said, it's not about just changing few modifiers when upgrading to bs4. It's about changing them everytime, when colors are changed. And not only in css but in html too. It means more work.
More work for theme developers, cms developers and drag'n'drop builder developers. 
Unfortunately for you @bbmatt this change would affect negatively more bs users then positively. Bad idea to do for the purpose of little improvement in intelligibility of markup. Moreover it's improvement mainly for developers who just click on download button. And what will do that kind of developers with .button-green when want color which is not in defaults? !important override

2017-05-30 18:07 UTC, bbmatt commented
> And what will do that kind of developers with .button-green when want color which is not in defaults? !important override

Does a kitten die each time someone does that? No. Seriously, why do some devs get so hung up on this, like it's some cast in iron rule that "thou shalt not use color names in css modifier classes".
So what if someone slaps !important and overrides alert-green with red? 
What will happen? Nothing. It will make their code make less sense, that's it. Big whoop.

2017-05-30 18:44 UTC, mdo commented
I probably should've locked this earlier, but doing so now. I'll be revisiting this PR shortly.

2017-06-15 18:32 UTC, mdo commented
Picking this up in a fresh PR that focuses on ensuring theme-ability via CSS and Sass by preserving a "brand theme" while also adding more options for colors. See #22836.

2017-06-15 18:32 UTC, closed without merging