Update Dependencies (REUPLOAD)
twbs/bootstrap pull request #22594
Opened 2017-05-10 14:08 UTC by CDAGaming

Uglify-JS: 2.8.22 > 3.0.3
QUnitJS: 2.3.1 > 2.3.2
PostCSS-CLI: 3.1.1 > 4.0.0
Clean-CSS-CLI: 4.0.12 > 4.1.0
Babel-Eslint: 7.2.2 > 7.2.3
AutoPrefixer: 6.7.7 > 7.0.1

2017-05-10 15:57 UTC, wolfy1339 commented
The Autoprefixer upgrade is a major one, relevent notes from the Changelog:

## 7.0.1
* Fix Autoprefixer for old JS runtimes.

## 7.0 “Coelestem adspicit lucem”
* Remove node.js 0.12 support.
* Use PostCSS 6.0.
* Use Browserslist 2.
* Use `caniuse-lite` instead of `caniuse-db` (by Ben Briggs).
* Use `^` for Browserslist dependencies, instead of `~`.
* Disable Grid Layout prefixes for IE by default.
* Fix `-ms-grid-column-align`.
```

2017-05-19 19:46 UTC, CDAGaming commented
Seems Odd that on the latest commit it's referencing TWO different version of JQuery. In config.yml also, that jQuery file CDN can be adjusted to cdnjs, while I'll most likely add to this PR later today

2017-05-26 23:49 UTC, mdo commented
This will need some reviewing and testing before we accept. Can anyone confirm all the dist files build properly and there are no errors?

2017-05-27 00:03 UTC, CDAGaming commented
May Need to recheck these dependencies, as some may have updated once more.

2017-05-27 00:04 UTC, CDAGaming commented
Yup, some deps need More Updating, one moment

2017-05-27 00:33 UTC, CDAGaming commented
Local Environment and Travis Building is Successful, and Bundler Version Dependency is now also Updated

2017-05-27 00:43 UTC, CDAGaming commented
Just Realized we are now using popper, which has a LOT of outdated dependencies, RIP 👍

2017-05-27 12:26 UTC, Johann-S commented
It seems @bardiharborow made a test in our `deps` branch (see : https://github.com/twbs/bootstrap/commit/eb0130ad9bdaf175d11d75e76ec04d3326947893)

and Travis build failed https://travis-ci.org/twbs/bootstrap/builds/231071098

2017-05-27 12:33 UTC, CDAGaming commented
Odd @Johann-S ,as in this PR all builds are reporting successfull, and the main errors im seeing are in relation to QUnit, ill pull the changes done in deps branch and see whats up with it

2017-05-27 12:45 UTC, CDAGaming commented
So, looking into the changes, the deps referenced still seem to be a bit outdated. I've also noticed that 'docs/assets/js/vendor/jquery-slim.min.js' was removed, but it appears that the errors in Travis is still referencing this file. Seems at this time, that that could be a probable cause of those errors. @bardiharborow You may reference the newer commits on this PR, and try to add back 'docs/assets/js/vendor/jquery-slim.min.js', which might fix travis error

2017-05-27 12:57 UTC, CDAGaming commented
As you can see, Updated QUnit with No issues. Most likely error cause was that deleted file most likely

2017-05-29 07:34 UTC, Johann-S approved these changes
LGTM 👍

2017-05-30 20:20 UTC, wolfy1339 requested changes

2017-05-30 20:20 UTC, wolfy1339 commented on js/tests/vendor/qunit.css
> +}
Please re-add the final new-line

2017-05-30 20:56 UTC, CDAGaming commented on js/tests/vendor/qunit.css
> +}
It's there. was just an invisible diff, and shouldnt need to be worried about

2017-05-31 04:11 UTC, merged