Support multiple Carousel indicators lists
twbs/bootstrap pull request #22646
Opened 2017-05-17 18:45 UTC by MikhailRoot

Carousel now supports multiple carousel-indicators lists to switch .active class on all of them simultaneously.

2017-05-18 05:53 UTC, Johann-S commented
Maybe you can add a preview of this feature and fix CI issues please

2017-05-18 21:54 UTC, MikhailRoot commented
@Johann-S   Created a demo of this feature here: https://codepen.io/MikhailRoot/full/VbEPwy/ 
 The idea and need was to support multiple carousel slides indicators.
Before my edits it just took the first set of indicators and removed .active class from any other.
Also updated code to use jQuery each iterator instead of for loop.

2017-05-18 22:16 UTC, vsn4ik requested changes

2017-05-18 22:16 UTC, vsn4ik commented on js/carousel.js
> +        var $nextIndicator = $( $(indicator).children()[nextItemIndex])
`$( $(indicator)...)` -> `$($(indicator)...)`

2017-05-18 22:17 UTC, MikhailRoot commented
Travis CI for some reason fails with "Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES"

2017-05-18 22:18 UTC, MikhailRoot commented on js/carousel.js
> +        var $nextIndicator = $( $(indicator).children()[nextItemIndex])
Done :)

2017-05-19 13:21 UTC, vsn4ik commented on js/carousel.js
> +      $(this.$indicators).each(function(index,indicator){
`(index,indicator)` -> `(index, indicator)`&

2017-05-19 14:39 UTC, Johann-S commented
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

If you want you can submit your PR for our `v4` release

2017-05-19 14:39 UTC, closed without merging