Add position utilities class
twbs/bootstrap pull request #23095
Opened 2017-07-15 12:55 UTC by CVarisco

Utility class to set position property.
Old PR #19292 with discussion.
Inspiration #18476

Thanks

2017-07-16 19:54 UTC, mdo requested changes

2017-07-16 19:54 UTC, mdo commented on scss/utilities/_position.scss
> +.pos-s { position: static; }
You're missing `position: sticky`, which, with this naming scheme, would be problematic. We'll need that utility and a different name.

2017-07-16 19:57 UTC, CVarisco commented on scss/utilities/_position.scss
> +.pos-s { position: static; }
You are right!
Could be a good naming scheme ?
`pos-sti`
`pos-sta`
`pos-rel`
`pos-abs`
`pos-fix`

2017-07-16 20:25 UTC, mdo commented on scss/utilities/_position.scss
> +.pos-s { position: static; }
At that point, we might as well use the full value names. `.p-sticky`, `.p-static`, etc.

2017-07-16 20:28 UTC, CVarisco commented on scss/utilities/_position.scss
> +.pos-s { position: static; }
Cool!
Thank you, I will a commit with this edit 🙂

2017-07-17 04:52 UTC, jipexu commented on scss/utilities/_position.scss
> +.pos-s { position: static; }
why not keep pos- or po- as prefix as p is use for padding ?

2017-07-17 05:20 UTC, mdo commented on scss/utilities/_position.scss
> +.pos-s { position: static; }
Because there's no risk of overlap with padding—these values are unique to positioning.

2017-07-17 15:55 UTC, mdo commented
I think your rebase went awry a bit :).

2017-07-17 17:42 UTC, CVarisco commented
ops, I'm sorry for that 🙁 
would you like that I squash commits ?

2017-07-18 02:25 UTC, mdo commented
I can squash as I merge when it comes to that :)

2017-08-08 05:29 UTC, mdo commented
Closing as this history got messed up.

2017-08-08 05:29 UTC, closed without merging