Assorted docs patches
twbs/bootstrap pull request #23102
Opened 2017-07-16 13:27 UTC by XhmikosR

Please check the individual patches, I'm too lazy to split each one to a separate branch. :)

/CC @bardiharborow @Johann-S @mdo

2017-07-16 13:30 UTC, Johann-S commented on _config.yml
> +  popper_hash:    "sha384-DnkRdQ7qQnIyQu3l2I77BVrTus+ZPSPbzkftVyG/w9e7UxGp0S0a72dG5FfBY/G3"
How do you convert `sha256` to `sha384` ? 
If I have to update Popper.js it would be helpful thanks 👍

2017-07-16 13:33 UTC, XhmikosR commented on _config.yml
> +  popper_hash:    "sha384-DnkRdQ7qQnIyQu3l2I77BVrTus+ZPSPbzkftVyG/w9e7UxGp0S0a72dG5FfBY/G3"
Just generate the hash for the file with https://srihash.org; it defaults to sha384.

2017-07-16 19:52 UTC, mdo requested changes

2017-07-16 19:52 UTC, mdo commented on _includes/social.html
> +<meta property="og:image:height" content="600">
These values need updating—the `bootstrap-social.png` isn't a 600x600 square.

2017-07-16 19:52 UTC, mdo commented on _includes/social.html
> +<meta property="og:image" content="{{ site.url | replace: 'https://', 'http://' }}{{ site.social_image_path }}">
Does the open graph protocol require a non-secure and secure URL? Can we not default to secure?

2017-07-17 03:47 UTC, bardiharborow requested changes

2017-07-17 03:47 UTC, bardiharborow commented on _includes/footer.html
> +    <p>Currently v{{ site.current_version }}. Code licensed <a rel="license" href="https://github.com/twbs/bootstrap/blob/master/LICENSE" target="_blank" rel="noopener">MIT</a>, docs <a rel="license"
Travis is mad because you've got duplicate `rel` attributes on this line. `rel="license noopener"` should work?

2017-07-19 14:35 UTC, bardiharborow commented on _includes/social.html
> +<meta property="og:image" content="{{ site.url | replace: 'https://', 'http://' }}{{ site.social_image_path }}">
Apparently... http://ogp.me/#structured

2017-07-19 14:46 UTC, bardiharborow commented
@XhmikosR sorry to mess with your PR, but this should be good to go now.

2017-07-19 14:47 UTC, bardiharborow approved these changes

2017-07-19 14:51 UTC, XhmikosR commented on _includes/footer.html
> +    <p>Currently v{{ site.current_version }}. Code licensed <a rel="license noopener" href="https://github.com/twbs/bootstrap/blob/master/LICENSE" target="_blank">MIT</a>, docs <a rel="license noopen
This doesn't make sense @bardiharborow since rel license doesn't have target="_blank". Please revert such changes, thanks.

2017-07-19 14:55 UTC, XhmikosR commented
@bardiharborow: Iignore my previous comment. I just reviewed the changes and looks good although personally I wouldn't add `rel="license"` here.

2017-07-19 15:04 UTC, bardiharborow commented
@XhmikosR I didn't get your previous comment, but why don't you think the pre-existing `rel="license"` is appropriate? http://microformats.org/wiki/rel-license

2017-07-19 15:14 UTC, XhmikosR commented
I thought you added it in this branch. That is why I generally prefer I rebase my PRs to check the changes ;)

2017-07-20 16:53 UTC, RinkAttendant6 commented on _includes/social.html
> +<meta property="og:image" content="{{ site.url | replace: 'https://', 'http://' }}{{ site.social_image_path }}">
Nothing on that page says that the `og:image` property can't be an https URL or that it has to be different than `og:image:secure_url`

2017-07-20 17:03 UTC, XhmikosR commented
No one said it does. I simply went the explicit way. Both work similarly.

On Jul 20, 2017 19:59, "Vincent" <notifications@github.com> wrote:

> *@RinkAttendant6* commented on this pull request.
> ------------------------------
>
> In _includes/social.html
> <https://github.com/twbs/bootstrap/pull/23102#discussion_r128571371>:
>
> >  {% else %}
>    <meta property="og:url" content="{{ site.url }}">
>    <meta property="og:title" content="{{ site.title }}">
>    <meta property="og:description" content="{{ site.description }}">
>  {% endif %}
> -<meta property="og:image" content="{{ site.url }}{{ site.social_image_path }}">
> +<meta property="og:image" content="{{ site.url | replace: 'https://', 'http://' }}{{ site.social_image_path }}">
>
> Nothing on that page says that the og:image property can't be an https
> URL or that it has to be different than og:image:secure_url
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/twbs/bootstrap/pull/23102#discussion_r128571371>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAVVtfaWqnfukR6hXiwghkbTcK0Whb4Aks5sP4dmgaJpZM4OZS9E>
> .
>

2017-07-30 21:11 UTC, mdo approved these changes

2017-07-30 23:27 UTC, merged