Add margin variable for paragraphs
twbs/bootstrap pull request #23140
Opened 2017-07-22 15:36 UTC by prateekgoel

I added a section for paragraphs in _variables.scss, used that variable to change hard coded margin value for p element.

Fixes #23031

2017-07-25 16:18 UTC, mdo requested changes
Paragraphs don't have horizontal margin on them (by default or from Bootstrap), so there's no need to reset them if there is nothing there to begin with.

Please restore the `margin-top: 0;` and use a variable for the `margin-bottom`.

Also, no need to shorten the word to four letters—use `$paragraph-margin-bottom` or something like that maybe?

2017-07-25 17:06 UTC, prateekgoel commented
Ok. I'll do these changes. Thanks.

2017-07-27 13:20 UTC, prateekgoel commented
@mdo For now, I have restored `margin-top: 0;`
Let me know if anything else need to be done.

2017-08-06 14:38 UTC, prateekgoel commented
@mdo Any update on this?

2017-08-07 02:54 UTC, mdo requested changes
This'll go in for Beta 2 at the earliest.

2017-08-07 02:54 UTC, mdo commented on scss/_variables.scss
> +$breadcrumb-margin:             0 0 1rem !default;
This should be here

2017-08-07 04:26 UTC, prateekgoel commented on scss/_variables.scss
> +$breadcrumb-margin:             0 0 1rem !default;
@mdo Should I add breadcumb-margin too? I mean this PR is for paragraph-margin. For breadcrumb there's a different PR #23138 .

2017-08-07 23:01 UTC, mdo commented on scss/_variables.scss
> +$breadcrumb-margin:             0 0 1rem !default;
Crap, I typo-ed—I meant shouldn't be here. It's in the wrong PR, so you can remove it.

2017-08-08 05:36 UTC, prateekgoel commented on scss/_variables.scss
> +$breadcrumb-margin:             0 0 1rem !default;
@mdo Did the changes.

2017-08-11 06:00 UTC, merged