Adds a border radius to modal headers
twbs/bootstrap pull request #23799
Opened 2017-09-01 18:04 UTC by andresgalante

This PR fixes #23798

When a background color is added to the modal header it shows a square corner. This PR is adding border radius to it so it follows the border radius.

What do you think?

2017-09-13 18:48 UTC, XhmikosR approved these changes

2017-10-02 05:06 UTC, mdo requested changes
There are several unrelated changes in this PR.

2017-10-02 05:25 UTC, andresgalante commented
@mdo I am sorry I had an auto formatter on. 😞 

I fixed the PR but it's still showing a strange diff, I don't know why.

2017-10-03 01:04 UTC, mdo approved these changes

2017-10-03 01:59 UTC, merged

2017-11-23 08:11 UTC, iwinux commented
@andresgalante @mdo `.modal-content` already has `border-radius`, why should we set it on `.modal-header` again?

2017-11-23 14:47 UTC, andresgalante commented
Hi @iwinux please read this issue https://github.com/twbs/bootstrap/issues/23798

2017-12-06 14:44 UTC, tmorehouse commented
Actually this bug persists when using a background on modal-footer.