Use border-radius mixin throughout scss
twbs/bootstrap pull request #23872
Opened 2017-09-07 20:26 UTC by lglasgow

As I was going through an update for my company's version of v4 bootstrap I noticed that the `border-radius` mixin wasn’t being used in some places where I thought it should be. I went through and updated code where it seemed that mixin should be used.

2017-09-27 07:38 UTC, XhmikosR commented
I'm not 100% sure about this. Sure, it's nice for consistency, but there's no other gain as far as I can tell.

Waiting for @mdo's final word.

2017-10-11 17:08 UTC, andresgalante commented on scss/_custom-forms.scss
> +    @include border-radius($custom-radio-indicator-border-radius);
Please remove it from here, if $enable-rounded is set to false we will lose the styles for the radio

2017-10-11 17:08 UTC, andresgalante commented on scss/_custom-forms.scss
> +    @include border-radius($custom-select-border-radius);
There is no need to use the mixin here, or replace the if statement with the mixin

2017-10-11 17:09 UTC, andresgalante commented on scss/_forms.scss
> +    @include border-radius($input-border-radius);
same here, the if statement is present already

2017-10-11 17:09 UTC, andresgalante requested changes
@XhmikosR I am also not sure if we need this. The main advantage of doing this is that if `$enable-rounded` is set to `false`, you'll get a compiled CSS that doesn't include these declarations. So there are some places on this PR where using the mixin is wrong or unnecessary.

2017-10-19 03:45 UTC, mdo commented
The advantage I think to using the mixin in more places is ideally Sass will remove all those selectors when the `$enable-rounded` is disabled and we're doing `@include border-radius(0)`.

2017-10-23 02:43 UTC, closed without merging