rework getting started intro a bit.
twbs/bootstrap pull request #24006
Opened 2017-09-20 01:48 UTC by bkdotcom

address issues raised in #23991
make it a bit more clear what javascript files are necessary and when..  move the "notes" to callouts

2017-09-20 01:50 UTC, bkdotcom commented
additionally:  It would be nice show alternate usage of `bootstrap.bundle.min.js`  is it on cdn?
url and hash need added to _config.yml

2017-09-20 07:06 UTC, Johann-S commented
currently `bootstrap.bundle.min.js` isn't on CDN because it's a new feature of our next release

2017-09-20 09:06 UTC, XhmikosR requested changes

2017-09-20 09:06 UTC, XhmikosR commented on docs/4.0/getting-started/introduction.md
> +If you wish to use our <a href="../../components/">javascript components</a>, you will need to place the following three scripts near the end of your pages, right before the closing `</body>` tag\*.
Use Markdown syntax and remove multiple spaces

2017-09-20 09:06 UTC, XhmikosR commented on docs/4.0/getting-started/introduction.md
> +* While we use [jQuery’s slim build](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) in our docs, the full version is also supported.
No need for you to use `’`; Jekyll does this for us.

2017-09-20 09:06 UTC, XhmikosR commented on docs/4.0/getting-started/introduction.md
> +And that’s it—you’re on your way to a fully Bootstrapped site. If you’re at all unsure about the general page structure, keep reading for an example page template.
Same here about `’`.

2017-10-03 00:35 UTC, mdo commented
Closing for #24214.

2017-10-03 00:35 UTC, closed without merging