prevent empty carousel from throwing, and staying in a 'sliding' state
twbs/bootstrap pull request #24132
Opened 2017-09-27 05:06 UTC by jimmymain

There are numerous questions on stack overflow relating to how the carousel becomes broken when it is emptied for any reason. This makes binding slides using angular or similar technologies very difficult, as they will routinely replace the set of slides with a new set.

whist I believe that calling `$.carousel()` should reset all the settings (particularly the `sliding` state), this simpler tweak at least ensures that if you use an angular / react binding to the carousel and it becomes empty, it does not get stuck in a sliding state.

please consider this pull - or something similar.

- https://stackoverflow.com/questions/29027830/getting-cannot-read-property-offsetwidth-of-undefined-with-bootstrap-carousel
- https://stackoverflow.com/questions/35918723/bootstrap-carousel-controls-causing-error
- https://stackoverflow.com/questions/29027830/getting-cannot-read-property-offsetwidth-of-undefined-with-bootstrap-carousel

2017-09-27 05:26 UTC, jimmymain commented
I am not sure how to go about fixing the CI build.
Some documentation element is not correct - I am unsure of how this relates to the javascript change I made.

Please consider fixing this issue though - it's causing a fair few questions on github.

2017-09-27 06:43 UTC, Johann-S requested changes

2017-09-27 06:43 UTC, Johann-S commented on js/carousel.js
> +      if (typeof $next == 'object' && $next.length)
please use `===` here

2017-09-27 06:43 UTC, Johann-S commented
Generally we don't accept any changes in v3 so for now I won't close this issue

/CC @mdo (for the final word)

2017-09-27 07:37 UTC, jimmymain commented
I understand that, but it's such a simple fix to a rather annoying problem - clearly not just experienced by myself.

2017-09-27 16:23 UTC, jimmymain commented on js/carousel.js
> +      if (typeof $next == 'object' && $next.length)
i have made the requested correction.

2017-10-03 05:49 UTC, XhmikosR commented
My main concern is that this should target the master branch and not v3.4.0.

2017-10-03 12:16 UTC, jimmymain commented
I am happy to move it to another branch if there's a reasonable chance it will be pulled.

2017-10-03 12:22 UTC, XhmikosR commented
@mdo: should I merge this manually to master?

2017-10-03 12:22 UTC, XhmikosR commented
@Johann-S: does the change look good to you? Ideally I think we should also have a test case.

2017-10-03 12:37 UTC, Johann-S commented
Yep a unit test would be a good things because here I just see a way to force the reflow but not sure if it fix the issue

2017-10-03 12:50 UTC, jimmymain commented
Ideally Yes, but firstly it's a difficult test and secondly - the fix is
just a null check.

On Tue, Oct 3, 2017 at 2:25 PM XhmikosR <notifications@github.com> wrote:

> @Johann-S <https://github.com/johann-s>: does the change look good to
> you? Ideally I think we should also have a test case.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/twbs/bootstrap/pull/24132#issuecomment-333825054>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ACb8qu-PCqiq2nvqgw6Etgt_DPMRNw5Iks5soifGgaJpZM4PlOQa>
> .
>

2017-10-03 13:02 UTC, Johann-S commented
Maybe with a visual test ? on a Codepen ?

2017-10-03 14:11 UTC, Hima1717 commented
Nothing Found

2017-10-04 02:20 UTC, jimmymain commented
I will put a code pen together and post the link here.

On Tue, 03 Oct 2017 at 16:14, Himanshu Singh Kushwah <
notifications@github.com> wrote:

> Nothing Found
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/twbs/bootstrap/pull/24132#issuecomment-333854257>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ACb8qg4ZiLOeQ54zCGOfl7dfMvavv8c2ks5sokE_gaJpZM4PlOQa>
> .
>

2017-10-04 07:28 UTC, jimmymain commented
I have created a code pen that clearly shows the issue.
https://codepen.io/jimmymain/pen/boYeZV?editors=1111

If you click "Toggle Slide List" the list of slides is emptied, and immediate the javascript error is raised in the console. "Cannot Read Property 'offsetWidth'".

The slide list is then in a **stuck** state where it can no longer slide.
My fix resolves the issue.

2017-10-04 07:45 UTC, Johann-S approved these changes

2017-10-04 07:52 UTC, XhmikosR commented
Manually merged to master. Thanks!

2017-10-04 07:52 UTC, closed without merging