Add support for calculate and dynamically change offset position for …
twbs/bootstrap pull request #24208
Opened 2017-10-02 15:25 UTC by romanlex

Sorry for bad English.
Add support for calculate and dynamically change offset position for dropdown menu.
Function call always when call Popper.js modifierFn.
Now I can change dynamically position of dropdown menu 
```javascript
            $('[data-toggle="dropdown"]').dropdown({
                offsetFn: function(data) {
                    data.left = -100;
                    return data
                }
            });
```

2017-10-02 15:56 UTC, romanlex commented
When use this code found bug in Popper.js(( Cannot set offset.left more when element width but can set any negative values

2017-10-02 16:40 UTC, romanlex commented
I think what better send all popper params, because it's more customizable solution and can change more settings of Popper
```javascript
_getOffset(data) {
  const popperOffset = $.extend({}, data.offsets, this._config.offsetFn(data.offsets) || {})
  Object.keys(popperOffset).forEach((key) => {
    data.offsets[key] = popperOffset[key]
  })
  return data
}
```

2017-10-03 07:27 UTC, Johann-S requested changes

2017-10-03 07:27 UTC, Johann-S commented on dist/js/bootstrap.bundle.js
> +    offsetFn: function offsetFn(data) {
Please do not commit dist files, you must revert this change

2017-10-03 07:27 UTC, Johann-S commented on docs/4.0/components/dropdowns.md
> +      <td>offsetFn</td>
No need for an new option here, just check if `offset` is a function or not

2017-10-03 07:27 UTC, Johann-S commented on js/src/dropdown.js
> +          event.type === 'keyup' && event.which !== TAB_KEYCODE)) {
you have unrelated changes here and their...

2017-10-03 09:21 UTC, closed without merging

2017-10-03 09:27 UTC, Johann-S commented
Why did you closed your PR @romanlex ?

2017-10-03 09:53 UTC, romanlex commented
@Johann-S big thx for your reply and thx for what you teach and say how to properly make changes.
I tried to correct your comments and made a new one PR

2017-10-03 09:55 UTC, Johann-S commented
Ok :smiley: you're welcome :wink: but you can just update this one 
I made an issue related to that PR https://github.com/twbs/bootstrap/issues/24223

2017-10-03 10:05 UTC, romanlex commented
I don't now ) How I can close this PR?