#24373 : Documentation/Navbar : Refer to utility classes uses. Add Printing section
twbs/bootstrap pull request #24380
Opened 2017-10-15 06:56 UTC by aavmurphy

refer to the  (not navbar) classes used for newbies
navbars don't print, so say this, and add example of a print-only alternative

2017-10-15 11:39 UTC, XhmikosR commented on docs/4.0/components/navbar.md
> +- its responsive - it automatically collapses at the `lg` (large) breakpoint.
`It's`

2017-10-16 02:25 UTC, mdo requested changes
Rather than add an entire new section to this page, let's put this under the `How it works` list.

2017-10-18 16:15 UTC, aavmurphy commented
@mdo please re-check. have added 1 more thing (fixed-top/bottom uses position:fixed), so doesn't reserve a gap on the screen. couldn't thing of a nice way to phrase it though. thanks

2017-10-18 17:26 UTC, mdo approved these changes
I pushed another commit to fine tune some things here around the language and formatting of the content—more links to utilities pages, better formatting of paragraphs and lists, etc.

Thanks for the back and forth!

2017-10-18 17:26 UTC, merged

2017-10-18 18:04 UTC, aavmurphy commented
Thanks!