Allow nested structure for accordions
twbs/bootstrap pull request #25121
Opened 2017-12-29 17:19 UTC by MartijnCuppens

Fixes #25119

2017-12-30 20:48 UTC, Johann-S requested changes
Please add a unit test

2017-12-30 21:39 UTC, MartijnCuppens commented
- Simplified the documentation (data-children attribute was not used in js and is not needed anymore)
- Added a unit test for nested elements
- Fixed existing tests where the data-parent was set on the link and not the collapsible content

2017-12-30 23:50 UTC, XhmikosR commented on docs/4.0/components/collapse.md
> +You can extend the default collapse behavior to create an accordion.
Hmm, this doesn't seem right.

2017-12-31 10:25 UTC, Johann-S commented on docs/4.0/components/collapse.md
> +You can extend the default collapse behavior to create an accordion.
Agree with @XhmikosR

2017-12-31 10:25 UTC, Johann-S approved these changes

2017-12-31 12:53 UTC, merged