feat: improvements of `.navbar-expand .dropdown-menu`
twbs/bootstrap pull request #25223
Opened 2018-01-07 19:15 UTC by zalog

I think we need some improvements on the `.navbar-expand .dropdown-menu` on mobile.
Imho it must feels like a submenu, not a dropdown like on desktop vieports.

### This is my proposal:

![after](https://user-images.githubusercontent.com/985838/34652991-4b58f6b2-f3ee-11e7-9896-423c5a5158b0.gif)

### This was before:

![before](https://user-images.githubusercontent.com/985838/34652977-154d3b82-f3ee-11e7-992c-fbe7f0d9709d.gif)

What do you think?

2018-01-08 10:57 UTC, andresgalante commented
Hi @zalog Thanks for the contribution, a few month ago I've taken a try to fix this on this PR #24055

Your solution is a bit different, maybe you can take a look at that one and let me know what you think.

2018-01-08 11:09 UTC, zalog commented
Oh! Sorry, didn't saw that PR... Perhaps because diversity, it's a win/win for the repo :)
Can you please rebase your branch? I'd like to take a look there.

2018-01-11 19:50 UTC, zalog commented
I made some tests on the min file size, bootstrap.min.css:
- actual `twbs:v4-dev` - **141.0k**
- `zalog:zalog-navbar-dropdown` - **145.8k**
- `andresgalante:drop-menu-navbar` rebased onto v4-dev - **147.5**

`andresgalante:drop-menu-navbar` does not have styling for `.dropdown-header` and it needs some extra vars `$navbar-*-dropdown-*` - [code here](https://github.com/andresgalante/bootstrap/commit/44843412711c019debcc8bbbabd3e0a8cc5a6a2e#diff-d8ee409a461718bfb6240710c8c73382R542).

I think `zalog:zalog-navbar-dropdown` it's a better approach.

And, if we consider #25274, we can win 0.5k, and the final size would be 145.3 :).

But, I think I can make some other improvements.

2018-01-11 21:40 UTC, zalog commented
Done! I think this is it, or we are very close.
We now have only 1.8kb increase, **142.8kb**.
It's the same aproach as here #25274, mobile first.

Check out the last commit, and of course the [pen v2](https://codepen.io/zalog/pen/jYxYRJ) :)

2018-01-15 04:33 UTC, andresgalante approved these changes
Hi @zalog , you are right, this is a leaner solution and takes headers into consideration.

@mdo I am ok merging this one and closing #24055

2018-01-15 04:40 UTC, andresgalante requested changes

2018-01-15 04:40 UTC, andresgalante commented on scss/_navbar.scss
> +    border-radius: 0;
@zalog sorry, I missed 2 this:
First:
You are removing `border` and `border-radius` when the drop menu is within a navbar always, even in large view ports. Remember that border radius is an opt in and we should keep them if the user chooses to do it.

2018-01-15 04:40 UTC, andresgalante commented on scss/_navbar.scss
> +    &.bg-#{$color} .dropdown-menu {
Second: this is changing the design. the drop menus would follow the color of the menu. I think I like it, but it might be a visual breaking change.

2018-01-15 04:57 UTC, andresgalante commented on scss/_navbar.scss
> +          white-space: nowrap;
what happens if the string is too long, would it overflow the screen?

2018-01-15 04:57 UTC, andresgalante commented on scss/_navbar.scss
> +  .dropdown-menu {
Why did you moved the `.dropdown-menu` selector under `.navbar` instead of `.navbar-nav`?

2018-01-15 10:27 UTC, zalog commented
Hi @andresgalante, I'll come back shortly on this branch.
Thanks for your time&feedback, you have a point there.

In the mean while, if you guys consider that we should not commit that contextual background on the dropdown for desktop (the breaking change), we can reset hard the last commit. But with this reset, we go back at 145.8kb :(

2018-04-01 22:22 UTC, closed without merging