inherit alert-link from parent
twbs/bootstrap pull request #25969
Opened 2018-03-29 13:53 UTC by m5o

* inherit alert-link from parent

Before | After
--- | ---
![screen shot 2018-03-29 at 15 51 07](https://user-images.githubusercontent.com/26371/38092692-417e1608-3369-11e8-8179-c54726e94cb6.png) | ![screen shot 2018-03-29 at 15 50 37](https://user-images.githubusercontent.com/26371/38092703-496d9c8a-3369-11e8-8104-18901b5e0dbc.png)

2018-04-16 12:08 UTC, andresgalante requested changes
Hi @m5o, this change might be breaking change to authors customizing the color of the alert links.

Even though it simplifies things a bit, it gives less control to author and I don't see that we gain anything by merging it.

Is there a good use case where you'd want to have it?

2018-04-17 09:40 UTC, m5o commented
@andresgalante – I just wanted to set awareness, that there exist these one-liners which adjust just a color nuance. An author can always setup his own `alert-[highlight]` styles with whatever color modifier he wants.

My point is, the `.alert-link` pattern isn't scaling, if we continue to define these utility class to "quickly provide matching colored links [within any alert]" to different components like e.g. Cards, Jumbotron, Nav,and Navbar.

UIkit, for example, has a `.[uk-]text-reset` / `.[uk-]link-reset` util class which reset `color` and `text-decoration`. This would be super handy and globally reusable in different components.

```css
a.uk-link-reset, a.uk-link-reset:hover, .uk-link-reset a, .uk-link-reset a:hover {
  color: inherit !important;
  text-decoration: none !important;
}
```

📖 https://getuikit.com/docs/link#link-reset

2018-05-25 09:40 UTC, m5o commented
@andresgalante 🔔

2018-07-07 22:36 UTC, mdo commented
Thanks @m5o, but we'll leave these links as they are for the darker contrast.

2018-07-07 22:36 UTC, closed without merging