add originalEvent to _clearMenus function (fixes #26336)
twbs/bootstrap pull request #26343
Opened 2018-04-19 08:55 UTC by jakubhonisek

2018-04-19 09:09 UTC, Johann-S requested changes
Please fix this error: https://travis-ci.org/twbs/bootstrap/jobs/368542629#L1156

and you must add a unit test to cover this case

2018-04-19 09:27 UTC, jakubhonisek commented
@Johann-S error was fixed

2018-04-19 09:31 UTC, Johann-S commented
Please add a unit test

2018-04-19 09:33 UTC, Johann-S commented on js/src/dropdown.js
> +          relatedTarget.original = event.originalEvent
`relatedTarget.originalEvent` would be better

2018-04-20 08:59 UTC, Johann-S commented
Why did you limit this event to click ?

2018-04-20 09:12 UTC, jakubhonisek commented
@Johann-S I wanted to avoid a collision with the name `originalEvent`. Also `click` is the only action that closes the dropdown (except `ESC` press).

2018-04-20 09:18 UTC, Johann-S requested changes

2018-04-20 09:18 UTC, Johann-S commented on js/src/dropdown.js
> +          relatedTarget.mouseEvent = event
I would prefer: `clickEvent`

2018-04-20 09:18 UTC, Johann-S commented on js/tests/unit/dropdown.js
> +  QUnit.test('should fire hide and hidden event with a mouseEvent', function (assert) {
I you want to add this property only for click event, you should add a test which verify this property isn't added on other type of events

2018-04-20 09:48 UTC, Johann-S commented on js/tests/unit/dropdown.js
> +        assert.onotO(e.clickEvent)
`assert.onotO(e.clickEvent)` I don't think `onotO` exist on `assert` 😆

2018-04-20 11:25 UTC, Johann-S approved these changes
LGTM 👍 

@mdo can I add new features in our next release ? (4.1.1) Or should I wait for 4.2 ?

2018-05-22 22:34 UTC, XhmikosR commented
@Johann-S: does this need to be documented in docs?

2018-05-23 09:18 UTC, Johann-S commented
yep that can be usefull, good catch @XhmikosR 👍

2018-06-23 23:00 UTC, XhmikosR commented
Closing for lack of replies.

2018-06-23 23:00 UTC, closed without merging

2018-06-25 06:40 UTC, jakubhonisek commented
Hi @XhmikosR , why did you close this pull request? Is there any action that I have to do? Or somebody else?

2018-06-25 06:44 UTC, XhmikosR commented
https://github.com/twbs/bootstrap/pull/26343#issuecomment-399715984