Box shadow issue 26377
twbs/bootstrap pull request #26493
Opened 2018-05-11 19:09 UTC by parammittal16

All the example pages having class box-shadow are replaced by bootstrap inbuilt box-shadow classes and then committed. 
Also, the example pages having unused box-shadow class, those pages box-shadow class is also removed and then committed.

2018-05-12 05:18 UTC, coliff approved these changes
LGTM! 👍

2018-05-29 06:44 UTC, coliff commented
HI @parammittal16 - your issue is currently in the 'Inbox' for possible inclusion to v4.1.2.
https://github.com/twbs/bootstrap/projects/14

Now you just need to wait. Hopefully it'll be merged and ship with v4.1.2 but maybe it'll take a little longer.

2018-06-01 10:39 UTC, parammittal16 commented
Ok thanks @coliff I hope it will be reviewed and be shipped 👍 soon.

2018-06-21 17:35 UTC, parammittal16 commented
Hi @coliff  my  PR was in the inbox yesterday but now it is missing from there ? What happened ?? Any updates ??

2018-07-07 22:27 UTC, mdo requested changes
All these instances of `box-shadow` should be replaced with `shadow-sm` instead of `shadow`. Happy to see that done here, or in another PR.

2018-07-08 00:49 UTC, parammittal16 commented
@mdo Sir I committed the changes that were requested

2018-07-09 04:31 UTC, mdo approved these changes
Thanks! Will slate for v4.1.3.

2018-07-14 21:05 UTC, merged