Fixed Card Columns section
twbs/bootstrap pull request #26587
Opened 2018-05-24 20:57 UTC by Vimal-Raghubir

- Removed duplicate card section in the second column.
- Put third card section into the details portion of the image like the first 2 columns, shifting the lorem ipsum section down into the correct spot.

#26267 defines the second point listed above. #26586 clearly defines the issues addressed in this PR.

2018-06-11 13:56 UTC, Vimal-Raghubir commented
Hi @XhmikosR , any update on this PR?

2018-06-11 14:02 UTC, XhmikosR commented
Sorry I'm very busy with work, please be patient until someone has the time to look into the changes.

2018-06-22 12:23 UTC, andresgalante requested changes
Hi @Vimal-Raghubir thanks for the PR, and sorry for taking us so long to get to review it.

I would like to keep more cards to show the masonry grid. Can we fix the text and keep the extra cards at the bottom of the right and middle column please?

2018-06-22 12:23 UTC, andresgalante commented on docs/4.1/components/card.md
> +    <img class="card-img" data-src="holder.js/100px260/" alt="Card image">
This should be `card-img-top`

2018-06-22 12:23 UTC, andresgalante commented on docs/4.1/components/card.md
> +      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height actio
This card is not wider, it's taller and it's not showing equal height

2018-06-26 20:58 UTC, andresgalante commented
Hi @Vimal-Raghubir Thanks for the changes, I would still like to keep more cards to show the masonry grid. Can you add them please?

thanks

2018-06-27 01:53 UTC, Vimal-Raghubir commented
Hi Andres which cards are you referring to?

2018-07-09 02:24 UTC, closed without merging