Allows tab function to be used with OL and UL
twbs/bootstrap pull request #26650
Opened 2018-06-02 01:25 UTC by tiesont

There are times when an `<ol>` is the correct node to use for a list, but the current tab() function will only work with either `<ul>` or `<nav>`. 

This PR changes `ACTIVE_UL` to `ACTIVE_LIST` and adds `nodeName === 'OL'` to the two checks for the tab button's parent node.

2018-06-04 14:26 UTC, Johann-S requested changes
Please add a unit test which cover this case

2018-06-04 20:04 UTC, tiesont commented
Actually curious to know how the current unit tests pass (assuming `v4-dev / js / tests / unit / tab.js` is the correct file to update). There are QUnit tests for ol-based markup, but I could not get tabs to work correctly without the changes I've made. I *think* it's because these tests only check for `active` and not `show`, which is how the active tab/pill is indicated. Do I have that right?

2018-06-04 20:31 UTC, Johann-S commented
I think you're right but can you add or change a unit test with a valid example ?

2018-06-04 20:47 UTC, tiesont commented
Sure. Won't be today, but I'll try to add something within a day or two.

2018-06-10 05:16 UTC, tiesont commented
@Johann-S Should the `assets/vendor/ ` folder contain a copy of QUnit (seems so from the README)? Seems to be missing, assuming patch-2 is the correct branch to be working from. Trying to run the unit tests in a browser, since I don't have NPM installed (and would rather not).

2018-06-10 07:38 UTC, Johann-S commented
No we made the decision to remove in our vendors because it's in our dev deps, so you have to install it with NPM, and please do not commit dist files

2018-06-10 20:20 UTC, tiesont commented
Okay, it'd probably be easiest if I close this, delete my fork, and create a new one with just the required updates. _Is_ patch-2 the correct branch to be working from?

2018-06-10 20:20 UTC, closed without merging

2018-06-11 07:40 UTC, Johann-S commented
you can call your branch whatever you want 😉