feature(carousel): carousel-item interval
twbs/bootstrap pull request #26667
Opened 2018-06-05 15:15 UTC by morrissey-ingenious

adds the ability to assign data-interval to an individual carousel-item.

I'm aware this may not be the proper way to add this functionality so please comment and give feedback and suggestions so that I can modify this pull request.

thanks

2018-06-06 09:40 UTC, Johann-S requested changes

2018-06-06 09:40 UTC, Johann-S commented on js/src/carousel.js
> +        if ($(nextElement).data('interval')) {
Please use more vanilla JS and change that line by
```js
const nextElementInterval = nextElement.getAttribute('data-interval')
if (nextElementInterval) {
```

2018-06-06 09:40 UTC, Johann-S commented on js/src/carousel.js
> +          this._config.defautlInterval = this._config.defautlInterval || this._config.interval
typo here, it's not `defautlInterval` but `defaultInterval`

2018-06-06 09:40 UTC, Johann-S commented on js/src/carousel.js
> +          this._config.interval = $(nextElement).data('interval')
Here instead of get the value from the dom use `nextElementInterval`

2018-06-06 09:41 UTC, Johann-S commented
There are a lots of things to do before we accept this MR :
- please add a CodePen which demonstrate what your code is doing
- add a unit test
- update our documentation

2018-06-06 18:04 UTC, morrissey-ingenious commented
@Johann-S what is the best way to pull these changes into a CodePen to show what my code is doing?  Thank You

2018-06-07 07:42 UTC, Johann-S approved these changes

2018-06-07 07:42 UTC, Johann-S commented
very nice @morrissey-ingenious 👍 

I want the feedbacks from other members before merging your PR

/CC @XhmikosR, @patrickhlauke, @mdo

2018-06-11 13:18 UTC, XhmikosR approved these changes

2018-09-18 12:55 UTC, merged