Allows both OL and UL lists for tab buttons
twbs/bootstrap pull request #26702
Opened 2018-06-11 20:11 UTC by tiesont

Modifies tab.js to allow OL as a parent element for the tab list items.

Duplicates UL-based visual tests to provide OL-based versions.

Adds check for "show" class to tabs unit tests.

2018-06-12 06:45 UTC, Johann-S commented on js/tests/unit/tab.js
>    QUnit.test('should activate element by tab id in ordered list', function (assert) {
it's the only unit test needed here, the other aren't related

2018-06-12 06:46 UTC, Johann-S requested changes
Some of your changes are irrelevant

2018-10-22 12:42 UTC, XhmikosR commented
@tiesont: can you take care of @Johann-S's comment?

2018-11-04 09:17 UTC, XhmikosR commented
Closing due to lack of response. You can comment here and we can re-open it if you decide to resume working on the requested changes.

2018-11-06 00:04 UTC, tiesont commented
I can fix this, I suppose, but I'm not sure what exactly is the issue here - I added those tests to make sure the plugin actually works with both UL and OL markup, which was the whole point of the original issue. Should I assume what you want is just the 

```javascript
assert.strictEqual($('#qunit-fixture').find('.show').attr('id'), 'home')
```

test? Or, do you only want the tests in tab.js?

2018-11-06 08:55 UTC, Johann-S commented
That's right, you just have to create one new test, with `<ol>` list, which show it works 👍

2018-11-07 06:10 UTC, tiesont commented
One _unit_ test (which should already be there) or one _visual_ test (which is also already there)? Is the issue that I modified the existing visual test to indicate which was UL-based and which was OL-based?

2018-11-09 09:06 UTC, Johann-S commented
@tiesont the is, you have unrelated changes.
Your fix should be:

![image](https://user-images.githubusercontent.com/1689750/48253171-ebb14480-e406-11e8-91a1-8419b19e82d2.png)

Because ordered list works, but with your fix we use the correct selector, so the use case is already covered

2018-11-12 01:00 UTC, tiesont commented
Okay, I'll admit that I'm not all that great at using Git (or GitHub, for that matter). I pulled down the 4.1.3 source, merged the updated tab.js file, and then made the updates to allow OL as a selector. I reverted the changes I made to the unit test and visual test files to match what is in this branch.

2018-11-12 09:05 UTC, Johann-S commented
I updated your branch and removed unrelated changes.

For me we should add one thing, it's a little note on our documentation to show we accept `<ol>` too 🤔 
You can edit that file to do that: https://github.com/twbs/bootstrap/blob/v4-dev/site/docs/4.1/components/navs.md#base-nav

2018-11-20 08:18 UTC, Johann-S approved these changes

2018-11-20 08:38 UTC, Johann-S commented
@XhmikosR do you know why Github tells me there are conflicts here ? I resolved all the conflicts 😟

2018-11-20 08:42 UTC, XhmikosR commented
I don't see any conflicts here.

2018-11-20 08:43 UTC, XhmikosR commented
Ah, I see it now. It's shown if you switch Rebase and merge. Because there's a merge commit.

2018-11-20 08:58 UTC, merged

2018-11-20 08:58 UTC, Johann-S commented
Thank you @tiesont 👍

2018-11-20 21:43 UTC, tiesont commented
@Johann-S No problem. Thank you for being patient with me.