Fix #26847
twbs/bootstrap pull request #26848
Opened 2018-07-10 19:12 UTC by jarstelfox

See: #26847

After doing some digging it looks like popover was previously checking for destroy, but this has been renamed to dispose in v4

2018-07-11 07:33 UTC, Johann-S requested changes

2018-07-11 07:33 UTC, Johann-S commented on js/src/popover.js
> +        if (!data && /dispose|destroy|hide/.test(config)) {
Can you remove `destroy` because it doesn't exist anymore

2018-07-12 20:07 UTC, jarstelfox commented
I've addressed your requested changes

2018-08-01 18:32 UTC, vsn4ik commented
@Johann-S Review please!

2018-08-02 09:46 UTC, Johann-S approved these changes

2018-08-02 11:51 UTC, merged

2018-08-03 02:39 UTC, bensamin commented
good

> 在 2018年8月2日，下午5:48，Johann-S <notifications@github.com> 写道：
> 
> @Johann-S approved this pull request.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/twbs/bootstrap/pull/26848#pullrequestreview-142719473>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AXGWn_vitCXDD-tRTGFHPgSZvehTODknks5uMssBgaJpZM4VJ93f>.
>