update toast documentation on accessibility
twbs/bootstrap pull request #27185
Opened 2018-09-05 20:17 UTC by Lausselloic

update documentation following discussion with @patrickhlauke  on PR #27155 

Maybe need a review for english because it's not my native langage.

Also add a question about default toast timeout actually defined to `500ms` maybe most of users will let it as is by copy/paste... don't know what's the usual timer on toaster but maybe increase it by default at 3seconds or 5seconds?

2018-09-06 05:06 UTC, Johann-S commented
About the timeout I chose that value `500ms` because for small message it'll be enough and for long message it won't be enough.
So we have to help our users to think by themselves we are not their mother/father and they are developers.
You added a useful information about to choose the right timeout so that's enough 👍

Personnaly the only doubts I have, it's, is it useful to have a show delay ?

2018-09-06 08:00 UTC, notabene requested changes

2018-09-06 08:00 UTC, notabene commented on site/docs/4.1/components/toasts.md
> +Toasts are intended to be small interruptions to your visitors or users, so to help those on screen readers, you should wrap your toasts in an [`aria-live` region](https://developer.mozilla.org/en-US
s/need/needed/
s/like list of form fields in error/e.g. for a list of for errors in a form/

2018-09-06 08:04 UTC, notabene requested changes

2018-09-06 08:04 UTC, notabene commented on site/docs/4.1/components/toasts.md
> +You also need to adapt the `role` and `aria-live` level depending on the content. If it's an important message like error, use `role="alert" aria-live="assertive"`, otherwise use `role="status" aria-
s/an important message like error/an important message like an error/

2018-09-06 08:04 UTC, notabene commented on site/docs/4.1/components/toasts.md
> +Be carefull to adapt the [`hide` timeout](#options) depending on the content to let all user enough time to read the content.
s/let all user/give all users/

2018-09-06 08:05 UTC, notabene requested changes

2018-09-06 08:05 UTC, notabene commented on site/docs/4.1/components/toasts.md
> +If you use `autohide: false` then you need to add a `close` button into the header to let user dismiss that element.
s/to let user dismiss/to enable users to dismiss/

2018-09-18 11:42 UTC, XhmikosR commented
@mdo @patrickhlauke: LGTY?

2018-09-18 11:43 UTC, Johann-S commented
>Personnaly the only doubts I have, it's, is it useful to have a show delay ?

What do you think about that @XhmikosR ?

2018-09-18 12:03 UTC, XhmikosR commented
@Johann-S: not sure to be honest, I'm not sure the branch is stable enough yet.

BTW I rebased this and the base branch to resolve the conflicts.

2018-09-18 12:39 UTC, Johann-S commented
@Lausselloic I updated the main PR by removing the show delay and fixing our documentation, can you rebase your branch ?

2018-09-18 12:45 UTC, Johann-S commented
finally I did it 😆

2018-09-18 15:28 UTC, mdo submitted a review, later dismissed
Couple text changes and then this seems good to go.

2018-09-18 15:28 UTC, mdo commented on site/docs/4.1/components/toasts.md
> +Be carefull to adapt the [`delay` timeout](#options) depending on the content to give all users enough time to read the content.
Noticed a typo here, but decided to rewrite this bit. Can you change this? If not, I can push a commit.

```
As the content you're displaying changes, be sure to update the [`delay` timeout](#options) to ensure people have enough time to read the toast.
```

2018-09-18 15:28 UTC, mdo commented on site/docs/4.1/components/toasts.md
> +If you use `autohide: false` then you need to add a `close` button into the header to enable users to dismiss that element.
Change to:

```
When using `autohide: false`, you must add a close button to allow users to dismiss the toast.
```

2018-09-18 15:50 UTC, XhmikosR approved these changes

2018-09-18 15:56 UTC, merged