Added 'show' and 'hide' methods to dropdown
twbs/bootstrap pull request #27370
Opened 2018-10-07 09:53 UTC by galczo5

2018-10-07 10:55 UTC, Johann-S requested changes
Hi @galczo5 ,

Thank you for your PR 👍 

But can you add a bit of context, why should we need those methods ? What's your use case ?

And can you add unit test for those two methods ?

2018-10-07 13:52 UTC, galczo5 commented
Hi,
In company we had an issue that we wanted to close all opened dropdowns when user select an option from one of them. We couldn't use `toggle` for it because it would open closed dropdowns. We had to keep state of each dropdown and conditionally call `toggle` method. 
So I've implemented missing `hide` method, and `show` method for consistency.

Later today I'll try to add missing unit tests.

2018-10-07 18:33 UTC, galczo5 commented
Unit tests pushed. Added missing trigger of `shown` and `hidden` events.

2018-10-08 07:58 UTC, Johann-S requested changes
Can you add more tests please, there are some lines which need tests:

![image](https://user-images.githubusercontent.com/1689750/46597515-a5538780-cae0-11e8-81a9-684a7144af8f.png)

- When it's disabled
- When it's active

And there are some line on the `hide` method too

2018-10-08 07:58 UTC, Johann-S commented on js/src/dropdown.js
> +    const parent   = Dropdown._getParentFromElement(this._element)
trailing spaces

2018-10-08 07:58 UTC, Johann-S commented on js/src/dropdown.js
> +    const parent   = Dropdown._getParentFromElement(this._element)
trailing spaces

2018-10-08 18:38 UTC, galczo5 commented
I've just added requested tests. I'm not sure if `preventDefault` tests are written correctly because I'm not very experienced with karma tests. 

It tests are not good, can you give me short description how should it works?
Thanks for your help!

2018-10-08 20:07 UTC, Johann-S commented
Thank you that's better, there are just two use cases missings:

- You should check that we do nothing if the dropdown is disabled on show and hide

and it'll be good 👍 

/CC @XhmikosR what do you think about that feature ? Seems interesting to me

2018-10-08 20:13 UTC, galczo5 commented
There are four tests for disabled dropdowns. One when dropdown is disabled via attribute, second when dropdown is disabled via class. For both methods.

2018-10-16 19:56 UTC, galczo5 commented
Are we ready for merge?

2018-10-16 20:11 UTC, Johann-S commented
I'm waiting for other team members feedbacks

2018-10-17 20:50 UTC, XhmikosR commented on js/src/dropdown.js
> +    const isActive = $(this._menu).hasClass(ClassName.SHOW)
Maybe skip `isActive` here and later one since they are used only once.

2018-10-18 19:18 UTC, galczo5 commented
@XhmikosR pushed

2018-10-19 07:50 UTC, Johann-S requested changes
sorry @galczo5 but I forgot one thing ! 😄 

Can you add those methods in our docs ? (`dropdown.md`)

2018-10-19 08:39 UTC, galczo5 commented
@Johann-S No problem :) I will edit it today

2018-10-20 09:45 UTC, Johann-S approved these changes

2018-10-20 09:45 UTC, galczo5 commented
Done :)

2018-10-20 11:27 UTC, merged