Unnecessarily restrictive children method
twbs/bootstrap pull request #27388
Opened 2018-10-09 18:29 UTC by sergchernata

Children method severely limits the markup customization of this plugin. We should be using find instead. As previously highlighted by #27006.

2018-10-09 19:19 UTC, Johann-S requested changes
Can you add a bit of context here ?

What's your use case ?

2018-10-09 19:42 UTC, sergchernata commented
Besides the issue I linked to, [here is another example](https://stackoverflow.com/questions/48814154/bootstrap-4-nested-navigation-link-opens-tab-content-only-the-first-time/52726523#52726523).

When navigation is customized and anchor elements are not direct children the plugin breaks. It's an unnecessary limitation. I see no harm, only upside.

Was there a specific reason for use of `children`?

2018-10-10 14:56 UTC, Johann-S commented
Yep we did that because of if you use a carousel in side a tabs you'll have a conflict between active classes 😟 see: https://github.com/twbs/bootstrap/pull/23087

2018-10-10 15:51 UTC, XhmikosR commented
@Johann-S: I thought we had a test case for this which I'd expect to see it fail?

2018-10-10 17:51 UTC, Johann-S commented
I was surprised too @XhmikosR 🤔 We'll have to fix that unit test.

@sergchernata this method is used to activate the tabs and the tab-content so not sure if it'll work but you should try 👍

I'm more than open if we can find a flexible solution

2018-10-10 19:48 UTC, sergchernata commented
[Here's a working pen with my proposition](https://codepen.io/anon/pen/LgyLvz), based on one of yours from a related issue.

Is there a different example I should be testing in?

2018-10-10 20:21 UTC, Johann-S commented
It seems it works well, can you push your changes here ?

2018-10-10 20:29 UTC, XhmikosR commented
We definitely need to add a test that covers the aforementioned case though...

2018-10-11 12:00 UTC, sergchernata commented
@XhmikosR I can help test if you link me to that case.

2018-10-11 12:08 UTC, XhmikosR commented
Well, I'd swear we had a test case for this, but it's been a long time, so I don't even remember. I'll need to dig into git log and PR/issues. Maybe @Johann-S remembers about it.

2018-10-11 12:47 UTC, sergchernata commented
@Johann-S my solution had an error, I'll do more testing.

2018-10-29 17:21 UTC, XhmikosR commented
So, any news @sergchernata?

2018-11-04 09:16 UTC, XhmikosR commented
Closing this due to lack of response.

2018-11-04 09:16 UTC, closed without merging