refactor(Modal): move `modal-scrollbar-measure` from SCSS to Js
twbs/bootstrap pull request #27472
Opened 2018-10-18 23:13 UTC by iamandrewluca

moved `modal-scrollbar-measure` from SCSS to Js
reused `Modal.prototype._getScrollbarWidth` in tests

Resolves #27471

2018-10-20 16:54 UTC, Johann-S requested changes

2018-10-20 16:54 UTC, Johann-S commented on js/src/modal.js
> +    scrollDiv.style.cssText = 'position: absolute; top: -9999px; width: 50px; height: 50px; overflow: scroll;'
Can you remove that change please, as we discussed in the related issue this CSS class is needed 👍

2018-10-21 10:17 UTC, iamandrewluca commented
@Johann-S should I rename this PR, to reflect right changes?

2018-10-21 15:19 UTC, Johann-S approved these changes

2018-10-21 15:45 UTC, merged