Fix tab fade out
twbs/bootstrap pull request #27533
Opened 2018-10-28 14:03 UTC by MartijnCuppens

The tab fadeout doesn't work because the `.show` class isn't removed. This causes some lag before the new tab is faded in.

Current behaviour:
https://getbootstrap.com/docs/4.1/components/navs/#javascript-behavior

2018-10-28 14:12 UTC, Johann-S requested changes
It's done on `_transitionComplete` here: https://github.com/twbs/bootstrap/blob/2781ccbf1afcccfd5fc31651988fea363514e175/js/src/tab.js#L175

Maybe it's not in the good order, so you should remove it when it's not the good place.

2018-10-28 14:13 UTC, Johann-S commented
Is it related to : https://github.com/twbs/bootstrap/issues/26525 @MartijnCuppens ? 🤔

2018-10-28 14:31 UTC, MartijnCuppens commented
Yes it is related to that ticket, thanks for mentioning that, @Johann-S.

We can indeed also remove the `.show` class from L175, at that point the class is already removed now.

2018-10-28 16:35 UTC, Johann-S commented
Not sure if there is a way to test that 🤔

2018-10-28 17:40 UTC, MartijnCuppens commented
Don't think so

2018-10-28 19:25 UTC, Johann-S requested changes

2018-10-28 20:46 UTC, MichelleKwa126 commented on js/src/tab.js
>      } else {
ACTIVE

2018-10-29 08:48 UTC, Johann-S approved these changes

2018-10-29 08:54 UTC, merged