[4.2] add `.text-wrap` class
twbs/bootstrap pull request #27568
Opened 2018-10-31 14:34 UTC by browner12

this is the opposite of `.text-nowrap`, and a forces elements to wrap onto new lines.

One use case for this is extra long button text. Bootstrap buttons by default do no wrap, so this class could be used to override that behavior.

2018-10-31 14:35 UTC, browner12 commented
references issue #19315

2018-10-31 16:13 UTC, MartijnCuppens commented
Hi @browner12,

There is a difference between `white-space: normal` and `word-wrap: break-word;` or `hyphens: auto;`. The utility class you provide doesn't do the same as was done in the ticket you're referring to.

> Bootstrap buttons by default do no wrap

This has been changed lately: https://github.com/twbs/bootstrap/commit/24bdadf9d3246b8b7668bd442dccf1f2aa5fae37#diff-8a4fc4262c9197c73b80fb80d8863ae5

So at the moment there's not really a reason to add this I think.

2018-10-31 16:36 UTC, browner12 commented
The reason I stuck with `white-space` here is because that's what `.text-nowrap` uses, so IMO `.text-wrap` should be the opposite.

Even though without the button behavior, I think this is a good small complement to the existing utility class.

2018-10-31 17:30 UTC, MartijnCuppens commented
I'm not fully convinced yet. Could you maybe provide a demo to show its use-case?

2018-11-02 14:19 UTC, browner12 commented
There are other components in Bootstrap that by default have a `white-space: nowrap;`.  Badges, dropdown items, navbar brands, and progress bars.   A user could also have some custom classes in their code that employ a nowrap.

This class would allow users to override that behavior on an individual basis.

```html
<div style="width: 100px; border: 1px solid red; ">
    <div class="badge badge-primary text-wrap">testing a very long badge name</div>
    <div class="badge badge-primary">testing a very long badge name</div>
</div>

<style>
    .text-wrap {
        white-space: normal;
    }
</style>
```

![screen shot 2018-11-02 at 9 18 24 am](https://user-images.githubusercontent.com/5232313/47920560-54854380-de80-11e8-8e54-1d2ed0fff354.png)

2018-11-02 17:01 UTC, MartijnCuppens approved these changes

2018-11-03 18:08 UTC, mdo approved these changes

2018-11-04 10:12 UTC, MartijnCuppens requested changes
Yes we should add this to the docs.

2018-11-04 11:34 UTC, XhmikosR approved these changes

2018-11-04 11:35 UTC, XhmikosR commented
@MartijnCuppens: I made the changes, have a look again and then I'll clean the branch and merge.

2018-11-04 13:41 UTC, MartijnCuppens commented
`white-space: normal` is the default behaviour, so I've changed the example to a badge, which makes it clear that this class can be used to override style set in css.

2018-11-04 13:42 UTC, MartijnCuppens approved these changes

2018-11-04 13:55 UTC, merged

2018-11-04 21:01 UTC, browner12 commented
thanks guys!