Add support for tooltip offset option to be a function
twbs/bootstrap pull request #28130
Opened 2019-01-28 21:04 UTC by jgolieb

Fixes #24223

2019-01-29 15:19 UTC, Johann-S requested changes
Can you move the logic in a private method please and can you add unit tests please

2019-01-29 15:19 UTC, Johann-S commented on js/src/tooltip.js
> +          data.offsets = $.extend({}, data.offsets, this.config.offset(data.offsets, this.element) || {})
please use the spread operator here

```js
data.offsets = {
  ...data.offsets,
  ...this.config.offset(data, this.element) || {}
}

2019-01-29 19:58 UTC, jgolieb commented on js/src/tooltip.js
> +          data.offsets = $.extend({}, data.offsets, this.config.offset(data.offsets, this.element) || {})
Done.

2019-01-30 12:30 UTC, Johann-S commented
@XhmikosR it seems we have some issues with Bundlesize, the github token is not found https://travis-ci.org/twbs/bootstrap/jobs/486082928#L833

2019-01-30 12:34 UTC, Johann-S commented on js/tests/unit/tooltip.js
> +      .bootstrapTooltip()
```js
var myOffset = 5
var $trigger = $('<a href="#" rel="tooltip" data-trigger="click" title="Another tooltip"/>')
  .appendTo('#qunit-fixture')
  .bootstrapTooltip({
    offset: myOffset,
  })
```

and after you'll be able to do:
```js
assert.strictEqual(offset.offset, myOffset)
```

I think it's more explicit like that

2019-01-30 12:35 UTC, Johann-S commented
Just one comment and it'll be alright 👍

2019-01-30 12:48 UTC, XhmikosR commented
@Johann-S the GH token isn't (and wasn't) available for PRs made by people without push rights, same as Browser Stack.

The build fails here due to the bundlesize limit. We'll need to increase the two bundle JS limits a bit.

2019-01-30 15:50 UTC, Johann-S approved these changes

2019-02-05 08:24 UTC, merged