minor jQuery.hasclass removal
twbs/bootstrap pull request #28158
Opened 2019-02-01 17:52 UTC by jwilson8767

2019-02-01 17:57 UTC, XhmikosR commented
Are there any other instances?

2019-02-01 17:58 UTC, XhmikosR commented
Hmm tests fail though.

2019-02-01 18:04 UTC, jwilson8767 commented
No other occurrences of this particular issue, not sure why tests are failing, could `this._dialog` sometimes be a jquery instance?

2019-02-02 09:59 UTC, XhmikosR commented
Yeah, maybe tests need to be adapted too.

2019-02-02 17:49 UTC, Johann-S commented
That's because a lot of modals in our tests do not have a `.modal-dialog` child.

It wasn't an issue before because jQuery fail in silence but not Vanilla JS

2019-02-06 08:43 UTC, XhmikosR commented
@jwilson8767 can you fix the issue?

2019-02-07 14:43 UTC, jwilson8767 commented
@XhmikosR Done, and tests are now passing.

2019-02-07 14:44 UTC, XhmikosR commented
Thanks! @Johann-S I think it's fine now, if so squash and merge please.

2019-02-11 01:53 UTC, ghiscoding commented
Hey guys, I just happened to have a peak at the PR and, I just noticed that the code is not exactly 100% bullet proof. I am using TypeScript a lot lately and in few occasion with the TSlint `no null` option and this PR would fail it. 

Technically the following is 100% safe

```diff
- if (this._dialog && this._dialog.classList.contains(ClassName.SCROLLABLE)) {
+ if (this._dialog && this._dialog.classList && this._dialog.classList.contains && this._dialog.classList.contains(ClassName.SCROLLABLE)) {
```

But I think that if you have a `classList`, you most probably have a `contains`, so the previous might be overkill and it might be more than enough to go with the simpler
```diff
- if (this._dialog && this._dialog.classList.contains(ClassName.SCROLLABLE)) {
+ if (this._dialog && this._dialog.classList && this._dialog.classList.contains(ClassName.SCROLLABLE)) {
```

Anywho, if you think my suggestion is still overkill then please disregard, but I think it's always better to avoid any possibility of errors thrown in the console... Bootstrap is awesome, thank you :)

2019-02-11 09:04 UTC, Johann-S requested changes

2019-02-11 09:04 UTC, Johann-S commented on js/src/modal.js
> +    if (this._dialog && this._dialog.classList.contains(ClassName.SCROLLABLE)) {
```js
if (this._dialog.classList.contains(ClassName.SCROLLABLE))
```

is enough, because a Modal must have a `dialog`

2019-02-11 09:23 UTC, Johann-S commented
Hi @ghiscoding,

Defensive code isn't something we should do here, because a modal must have a dialog, and when you have an `HTMLElement` you have a `classList`.

This PR won't fail in TS, because `_dialog` is an `HTMLElement`

2019-02-11 13:14 UTC, Johann-S approved these changes

2019-02-11 13:15 UTC, merged

2019-02-11 13:15 UTC, Johann-S commented
Thanks for your work @jwilson8767 👍

2019-02-11 14:33 UTC, jwilson8767 commented
@Johann-S Thanks for giving this your attention! Looking forward to being off of jQuery :)