Input group scss refactoring
twbs/bootstrap pull request #28309
Opened 2019-02-19 14:04 UTC by alexandreDavid

Using a mixin for removing duplicated code.

2019-02-19 14:06 UTC, XhmikosR commented
Please retarget the PR to the master branch.

2019-02-19 14:06 UTC, XhmikosR submitted a review, later dismissed
Please retarget the PR to the master branch.

2019-02-19 14:12 UTC, XhmikosR commented
And make sure tests pass ofc.

2019-02-19 16:08 UTC, ysds requested changes

2019-02-19 16:08 UTC, ysds commented on scss/mixins/_input-group.scss
> +    @include border-radius($badge-border-radius);
```suggestion
    @include border-radius($border-radius);
```

2019-02-20 20:02 UTC, MartijnCuppens commented
I got mixed feelings with this one. On one hand this removes a lot of duplicate code, on the other hand, this adds a new file, with only one mixin. I guess this is a step closer an ideal solution, but we're not there yet.

Thoughts @mdo @ysds?

2019-02-21 01:38 UTC, vsn4ik commented on scss/_input-group.scss
>  .input-group-lg > .custom-select,
```
.input-group-lg > .custom-select,
.input-group-sm > .custom-select {
  padding-right: $custom-select-padding-x + $custom-select-indicator-padding;
}
```
->
```
@mixin input-group-size(...) {
  ...
  > .custom-select {
    padding-right: $custom-select-padding-x + $custom-select-indicator-padding;
  }
}
```
?

2019-02-21 08:13 UTC, ysds commented
@MartijnCuppens We already have a file for similar sizing mixin - [mixin/_pagination.scss](https://github.com/twbs/bootstrap/blob/51375abca5769682f1d27de2e29e6e9f15ec7314/scss/mixins/_pagination.scss). Maybe we should choose to add the input group sizing mixin or remove the pagination' one for consistency.

2020-01-02 19:25 UTC, MartijnCuppens commented
Closing this to consolidate https://github.com/twbs/bootstrap/pull/29885

2020-01-02 19:25 UTC, closed without merging