Update tab.js
twbs/bootstrap pull request #28534
Opened 2019-03-20 23:12 UTC by Lexipowder

Makes multiple tab-contents from one tab work

https://github.com/twbs/bootstrap/issues/19964

2019-03-20 23:14 UTC, XhmikosR submitted a review, later dismissed

2019-03-20 23:14 UTC, XhmikosR commented on js/src/tab.js
> +
Useless spaces.

2019-03-20 23:14 UTC, XhmikosR commented on js/src/tab.js
> +      target = document.querySelectorAll(selector);
We already have our own function for this: `SelectorEngine.find()`.

2019-03-20 23:14 UTC, XhmikosR commented on js/src/tab.js
> +      for (let i = 0, len = target.length; i < len; i++) {
Wrong indentation

2019-03-20 23:14 UTC, XhmikosR commented
Also, please be more clear as to what this is supposed to fix.

2019-03-21 08:35 UTC, Lexipowder commented
Thanks for the feedback, this is my first I contribute to bootstrap, so thanks for being patient.
The problem that which should be fixed is, for example in a business application where you work with tab structure, with a tab-content for line items (like order data, product information) and side-bar with functions (also tab-content) which are related to what kind of details are shown.

Therefore it would be necessary that both tab-contents change/show with the click on one tab.

Tab (data-target=”.view1”)
<div class=”col-12”>
<div class=”col-8 view1”>
… line items …
</div>
<div class=”col-4 view1”>
… side-bar with function that coould be applied on the line items shown, functions can be different per display typs of line items …
</div>

2019-03-21 08:53 UTC, Johann-S requested changes
@Lexipowder thanks for your PR.

There is two things left:
 - Mention that feature in tab docs
 - A unit test

2019-03-21 13:40 UTC, Lexipowder commented
Sorry for asking, my task?

- Mention that feature in tab docs
- A unit test

2019-03-21 13:49 UTC, XhmikosR commented
Yup :)

2019-05-16 08:19 UTC, boomsya commented
I don`t understand. Multiple tab-contents from one pill works in 4.3.1 or not?

2019-07-25 14:44 UTC, Johann-S commented
Finally we will pass on that feature thanks @Lexipowder, if you want to finish your work feel free to open a new PR 👍

2019-07-25 14:44 UTC, closed without merging