Modify `.card-header-tabs .nav-link.active` colors
twbs/bootstrap pull request #28833
Opened 2019-05-27 15:31 UTC by shaneparsons

Set `.card-header-tabs .nav-link.active` background / border colors to better match card.

2019-05-27 15:33 UTC, shaneparsons commented
For #28820.

2019-05-27 16:18 UTC, ysds commented
Should also care for hover?

2019-05-27 19:18 UTC, shaneparsons commented
Since `background-color` isn't actually changed on hover, and the `border-color` changes are fine, I don't think any hover styles are needed.

I did make a change to my pull request though:

Previous:
`border-color: $card-border-color $card-border-color $card-bg;`

New:
`border-bottom-color: $card-bg;`

Now only the bottom border colour changes, to match the card background.

2019-05-27 19:24 UTC, shaneparsons commented
Here are some screenshots of the difference the pull request makes:

Before:
![Screen Shot 2019-05-27 at 3 21 46 PM](https://user-images.githubusercontent.com/5495493/58436446-62581b80-8093-11e9-88a0-f317b2424efd.png)

After:
![Screen Shot 2019-05-27 at 3 22 37 PM](https://user-images.githubusercontent.com/5495493/58436454-684dfc80-8093-11e9-8c3b-8b9379a2cc55.png)

Note: the first tab is active, the second tab is hovered.

2019-05-28 07:45 UTC, mdo reviewed
I think I’m in favor of this. Feels like a helpful consideration for folks who may modify the `$body-bg` to be something different. Otherwise though, it’s unnecessary. Thoughts from @twbs/css-review for how to account for that and avoid including CSS that’s not used by default?

2019-05-28 07:45 UTC, mdo commented on scss/_card.scss
> +    background: $card-bg;
Don’t use the shorthand, use `background-color` so it doesn’t override additional `background-` properties.

```suggestion
    background-color: $card-bg;
```

2019-05-28 13:32 UTC, shaneparsons commented
@mdo Indeed. Some frameworks like Laravel modify the `$body-bg` by default too, so it's one less thing that developers have to worry about.

2019-05-28 13:49 UTC, shaneparsons commented
There's probably a way to modify this to play nice with [#background-and-color](https://getbootstrap.com/docs/4.3/components/card/#background-and-color) as well, but that's a seperate issue.

2019-05-28 17:10 UTC, ysds requested changes
> Thoughts from @twbs/css-review for how to account for that and avoid including CSS that’s not used by default?

@shaneparsons Could you change as the follows? 😄

```scss
  .nav-link.active {
    background-color: $card-bg;
    border-bottom-color: $card-bg;
  }
```

to

```scss
  @if $nav-tabs-link-active-bg != $card-bg {
    .nav-link.active {
      background-color: $card-bg;
      border-bottom-color: $card-bg;
    }
  }
```

2019-05-28 17:33 UTC, shaneparsons commented
> > Thoughts from @twbs/css-review for how to account for that and avoid including CSS that’s not used by default?
> 
> @shaneparsons Could you change as the follows? 😄
> 
> ```scss
>   .nav-link.active {
>     background-color: $card-bg;
>     border-bottom-color: $card-bg;
>   }
> ```
> 
> to
> 
> ```scss
>   @if $nav-tabs-link-active-bg != $card-bg {
>     .nav-link.active {
>       background-color: $card-bg;
>       border-bottom-color: $card-bg;
>     }
>   }
> ```

Done!

See my edit to https://github.com/twbs/bootstrap/pull/28833#issuecomment-496524571 and let me know if the additions are of any interest to you.

2019-05-28 17:45 UTC, ysds commented
I think it's over-engineering to integrate with the background utilities. It would be better to solve it with custom variables in the future (v6?)

2019-05-28 17:45 UTC, ysds approved these changes

2019-05-28 17:55 UTC, shaneparsons commented
> I think it's over-engineering to integrate with the background utilities. It would be better to solve it with custom variables in the future (v6?)

Yeah I agree on that one. I don't have a ton of experience with mixins / utilities, so that was just my hacky take on the solution. I more so just intended to get the conversation started.

2019-05-29 09:31 UTC, MartijnCuppens approved these changes

2019-05-29 14:01 UTC, mdo approved these changes
Thanks, everyone! <3

2019-05-29 15:21 UTC, XhmikosR commented
I assume we don't want this backported, right?

2019-05-29 16:38 UTC, merged