Make tabs ARIA accessible.
twbs/bootstrap pull request #29006
Opened 2019-07-10 01:04 UTC by maedi

Bootstrap Tabs almost conforms to the ARIA role spec for tabs but not quite:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role#Description

To match the spec the following changes have been made:
- Change the `tab` from using `aria-expanded` to `aria-selected`
- Connect to `tabpanel`s via the `tab`'s `aria-controls` value
- Change the `tabpanel` from using an `.active` css class to `aria-expanded` (in addition)

The HTML will need to ensure that their `tab`'s `aria-controls` and `tabpanel`'s `id` match.

2019-07-10 07:00 UTC, XhmikosR commented
@mdo @Johann-S @patrickhlauke: this is for v3... We *could* merge it if we are going to release v3.4.2.

2019-07-10 07:17 UTC, patrickhlauke commented
open `tabpanel` doesn't need nor benefit from `aria-expanded`, since it's completely hidden from the accessibility tree when not open

2019-07-10 07:20 UTC, patrickhlauke commented on js/tab.js
> +      $activeTabpanel.attr('aria-expanded', false);
`aria-expanded` is unnecessary on the tab panel

2019-07-10 07:20 UTC, patrickhlauke commented on js/tab.js
> +      elementTabpanel.attr('aria-expanded', true);
`aria-expanded` is unnecessary on the tab panel

2019-07-10 07:27 UTC, patrickhlauke requested changes
In short, the only minimal change from this PR that is required is switching from using `aria-expanded` (which was wrongly used in v3) to `aria-selected`

(there's more fundamental things that make our tab implementation not quite compliant, like lack of keyboard support, but we're tackling those for v5 with potential v4 backport)

2019-07-10 09:35 UTC, Johann-S commented
I'm not in favor of merging that, because v3 is EOL

2019-07-11 16:34 UTC, mdo commented
v3 is EOL, we shouldn't be shipping anything else there.

2019-07-11 16:34 UTC, closed without merging