Added link to creative commons license
twbs/bootstrap pull request #29032
Opened 2019-07-13 12:06 UTC by sunn-e

The previous link is dead one.

2019-07-13 13:32 UTC, XhmikosR approved these changes

2019-07-13 13:33 UTC, XhmikosR requested changes
Actually, we should link to `https://creativecommons.org/licenses/by/3.0/`

2019-07-13 20:22 UTC, sunn-e commented
> 
> 
> Actually, we should link to `https://creativecommons.org/licenses/by/3.0/`

I was actually waiting for someone to tell what is the actual license used. Thanks. I will update it.

2019-07-14 08:48 UTC, XhmikosR approved these changes

2019-07-14 08:52 UTC, merged