Contrast colors added to theme-colors
twbs/bootstrap pull request #30044
Opened 2020-01-17 12:01 UTC by memic84

Fixes #29361

- [x] Contrast colors are added to theme-colors.
- [x] Instances with old code are replaced to `text-{{ .contrast_color }}`

2020-01-17 13:34 UTC, MartijnCuppens approved these changes
Only change is the background of the yellow text: https://deploy-preview-30044--twbs-bootstrap.netlify.com/docs/4.3/utilities/colors/#color (but this is an improvement)

2020-01-17 13:37 UTC, XhmikosR requested changes
1. I'd change `contrast_color` to `contrast-color`
2. I wouldn't add redundant classes; we only need this in 2 cases otherwise it doesn't have any effect

2020-01-17 13:54 UTC, XhmikosR commented
@memic84 you can use something like (untested) `{{ with .constrast-ratio }} text-{{ . }}{{ end }}`; this will only add the extra classes if they are set. Then you can remove the unneeded ones.

2020-01-17 13:55 UTC, XhmikosR commented on site/content/docs/4.3/components/badge.md
> +
This seems unneeded

2020-01-17 13:59 UTC, memic84 commented
I renamed the class to `contrast-color`, but there are problems with the proposed change for redundant classes. 

The cards also require the white color to be set, which means that we have to set all contrast-colors. Also this will add more logic, and the logic will be in two places templates and theme-colors, where with the redundant classes it's only in theme-colors.yml.

2020-01-17 14:00 UTC, XhmikosR commented
Yeah, but the end users don't need the extra classes.

Anyway, I'll have a look later myself and see how this can be simplified.

2020-01-17 14:07 UTC, memic84 commented
> Yeah, but the end users don't need the extra classes.
> 
> Anyway, I'll have a look later myself and see how this can be simplified.

I agree, that the end users don't need the extra classes.

My only problem is that, for example the contrast-color of primary, is sometimes needed and sometimes not. I will check the Hugo docs, for a solution...

2020-01-17 14:10 UTC, XhmikosR commented
Maybe we should go with your original patch and just mention that the extra classes are not needed?

But then if we are going to do that, we might as well just go the `with` solution since we'll edit the files.

BTW `contrast-color` doesn't work with Hugo, I will revert it to the underscore one.

2020-01-17 14:12 UTC, XhmikosR commented
This is what I suggested in case you want to play with it `{{ with .contrast_color }} text-{{ . }}{{ end }}` (adapt it for the bg case as needed).

But we need to think how to proceed before any further changes.

2020-01-17 14:13 UTC, XhmikosR commented
Also, found a bug with Hugo; when I change the data file, the changes are not reflected unless I restart Hugo. I will try to report it.

2020-01-17 14:17 UTC, memic84 commented
> This is what I suggested in case you want to play with it `{{ with .contrast_color }} text-{{ . }}{{ end }}` (adapt it for the bg case as needed).
> 
> But we need to think how to proceed before any further changes.

With this it means, that the contrast color will be used if there's one defined in the theme-colors.yml? 

It seems like a solid solution, and that we create the exception in templates where needed, ex. cards with `text-white`

2020-01-17 14:21 UTC, XhmikosR commented
>With this it means, that the contrast color will be used if there's one defined in the theme-colors.yml?

Yeah, `with` is just for that.

I mean, if we are going to edit the content files to say that the extra classes are only needed for our examples, we might as well go with this solution since we will need to edit the files anyway.

Another solution would be to try to abstract the inline shortcode's logic into a common shortcode where we will pass HTML etc. I haven't tried this so I don't know if it's worth it, but it might be simpler to have the logic in one place, assuming it works.

2020-01-17 14:28 UTC, memic84 commented
This works: `<span class="badge bg-{{ .name }}{{with .contrast_color}} text-{{.}}{{end}}">{{ .name | title }}</span>{{- end -}}` for example in the badge page.

I'll push soon...

2020-01-17 15:08 UTC, memic84 commented
There might be some inconsistencies in hugo templates with coding style. I'll fix this soon, when the proposed fix is ok.

2020-01-29 09:02 UTC, memic84 commented
@XhmikosR Have you checked the changes? Let me know is this is OK now?

2020-04-10 09:29 UTC, ffoodd commented
FYI this'll have conflicts with #30468 : if we ever merge this one, simply drop my own changes in `.md` files since they basically add a utility to use sufficiently contrasted colors.

2020-04-17 12:41 UTC, ffoodd approved these changes

2020-04-17 12:43 UTC, ffoodd commented
LGTM. @XhmikosR, anything else to update?

2020-04-17 12:43 UTC, XhmikosR commented
Don't merge this yet, I haven't cleaned it up

2020-10-29 18:53 UTC, mdo commented
What's the cleanup left here @XhmikosR?

2020-10-30 13:20 UTC, XhmikosR commented
@mdo @ffoodd please have another look. I rebased the branch and adapted it to the recent changes.

One way would be to have light/dark in all colors, or the other would be what we currently have by specifying only the exceptions.

Regardless, needs another pair of eyes since I didn't test it thoroughly and it's been a long time since the PR was made :)

2020-10-30 13:37 UTC, ffoodd approved these changes
LGTM, very elegant (and efficient!)

And specifying the exceptions seems better to me, since this is what we need this for. MAkes it much easier to spot colours with specific requirements.

2020-10-30 22:04 UTC, mdo approved these changes
:shipit:

2020-10-31 06:20 UTC, XhmikosR approved these changes

2020-10-31 06:21 UTC, merged