Documentation skip links
twbs/bootstrap pull request #30073
Opened 2020-01-23 15:52 UTC by ffoodd

Mostly usability improvements — at least some tries:

- new skip-link to the main navigation, in documentation page;
- new skip-link to search form (on pages that display it);
- refactored skip-links pattern, mainly to ease their use for screen magnifiers users (which can't see them appearing since when using it, they are likely to be on the top left corner of the document).

This is more convenient to use, and also simplify both markup and styles — however maybe opinionated?

Each of these is a separate commit so let me know if I should revert one of those.

Ping @patrickhlauke again :)

2020-01-23 23:26 UTC, Milad-Abooali approved these changes

2020-01-24 06:42 UTC, MartijnCuppens commented
- I don't really like the theming changes, any reasons why you did this? Also don't remove the hover state, the link is now blue when hovered.
- Combining skippy and skippy-text is a good idea though
- Any reason why you don't link to the search input field itself?

2020-01-24 08:32 UTC, ffoodd commented
For the theming, I only moved them to the top left corners, which is generally where it's used by screen magnifiers users. It's not an absolute rule obviously, just a kind of convention.

As a matter of fact, previous theming using full width colored background might be a sufficient clue I guess, however I'd recommend obviousness to visual clues, when speaking about visual deficiencies.

I'm fixing the hover color, missed that; and you're right about linking to the search input, would be better!

Commits on their way, let me know if I should revert the theming part.

2020-01-27 10:02 UTC, MartijnCuppens commented
Ping @twbs/team for a second opinion on the theming changes. Personally I don't the blue outline we have now:
![image](https://user-images.githubusercontent.com/11559216/73165623-722d7100-40f4-11ea-9ee6-687f91a15e99.png)

2020-01-29 13:46 UTC, ffoodd commented
@MartijnCuppens Those are default outlines from your browser (Chrome, I guess?) — and should be the same in the navbar, for example. 

Should I customize it? They don't seem to be customized for links at all in `_reboot.scss`…

2020-02-12 10:09 UTC, XhmikosR commented
@ysds what's your take on this?

2020-02-12 14:01 UTC, ysds approved these changes
I don't like UIs that cover logos because their identities seem to be ignored, but there is no rational reason to deny this proposal. The colors (bg, text and outlines) look good for me.

2020-02-15 02:17 UTC, mdo commented
Is this a common practice? I haven't seen this many tabs in front of my ability to get to a clearly focusable element. Also, tabbing to the search form applies the focus style, but it's not focused with my cursor—at least in Safari, I cannot type in the field with tab-tab-tab-enter. Feels like an incomplete implementation with that.

I'd also echo the feedback of this being a little tough to see given the colors. It matches, yes, but it could be more obvious.

2020-02-16 11:15 UTC, XhmikosR commented
I agree with the search focus comment. I too would expect it to focus the search input.

I like the change in the skip to main content part but only for desktop. For mobile it hides the logo. Not a big deal, and TBH, this might be a better approach since the page does not jump when the links show up?

2020-02-17 08:27 UTC, ffoodd commented
You're right about the search input, I guess it's somehow related to Algolia. I'll investigate on this.

About the design thing, let me know if you have any ideas: FYI I didn't change anything on the design part, except links being above the header instead of making it jumppy (and this is still easy to revert).

I seriously think it's more common to have skip links fixed above the header than moving around. Above the logo is not a concern to me, since people got to your page and saw it… I guess their comfortable usage of the page is more important than always see your logo :D 

The main goals of this PR are:
1. get skip links left aligned, since people using a screen magnifier start on the top left, whatever their screen resolution is;
2. add other skip links to ease navigating: to the search input, and to the documentation subnav.

Styling skip links wasn't to my mind so please elt me know if you think I can improve this too.

For now it's at least missing a correct behaviour for the search input getting focus.

2020-02-17 09:16 UTC, ffoodd commented
Hi there,

I'm getting very different and disappointing behaviours on this. It seems to work fine in Chrome, but not at all in Firefox — and I only tested those two, I guess trying with Edge, Safari, or mobile browsers would get things worse. I made [a reduced test case on CodePen](https://codepen.io/ffoodd/pen/VwLaGjE?editors=1111).

At this point, the skip to search input link would require some JavaScript to properly get the focus :/ I found several posts mentionning this kind of issues with skip links / anchors, all of them ending up with a JavaScript patch…

Since there's not so much tabs to get through before reaching the search input, I'm not sure it's worth it.

I'd recommend to simply remove the skip to search link (and still standing by for the design part) — do you have any opinion on this?

2020-02-18 07:53 UTC, XhmikosR commented
I'm still not sure if the second skip to main nav has any value since the nav it's in the content already.

/CC @mdo @patrickhlauke for your final words

2020-02-18 10:42 UTC, patrickhlauke commented
i think the additional skip link is quite useful for kbd users as, when navigating through the docs, it allows for reasonably quick access to the side navigation there without needing to constantly tab through the top navigation stuff.

i wonder though if rather than "main navigation", it should say "docs navigation" (i.e. "skip to docs navigation") as arguably the main navigation throughout the site is the one at the top? (though i see the `<nav>` itself also has an `aria-label="Main Navigation"`, so it's consistent with that i guess)

also, a complete aside - is there any issue opened about the disclosure widgets in the side navigation there not having `aria-expanded` and not having a button role?

2020-02-18 11:46 UTC, XhmikosR commented
> also, a complete aside - is there any issue opened about the disclosure widgets in the side navigation there not having `aria-expanded` and not having a button role?

The thing is that the docs don't use our core collapse plugin for the sidebar (I didn't implement this and it must got merged without noticing it). So, it's very basic and obviously lacks some stuff. I tried to switch to the collapse plugin for the sidebar, but I gave up since it didn't work properly.

2020-02-18 12:07 UTC, ffoodd commented
@XhmikosR @patrickhlauke I think I managed to make collapse work on sidenav: could you please check?

2020-02-18 12:26 UTC, XhmikosR commented
@ffoodd please try to keep your PRs clean, simple and short. Squash any patches when possible, don't make more than 1 core change. Please move the discussion about the sidebar to a new PR.

2020-02-18 12:32 UTC, patrickhlauke commented
there seems to be some slight delay now between activating the disclosure control and the submenu appearing.

additional complication/consideration: when in smaller screen view, where the secondary navigation is collapsed behind the hamburger menu, the "skip to docs navigation" won't work as expected when the hamburger is currently closed.

2020-02-18 12:50 UTC, ffoodd commented
@patrickhlauke Collapse behaviour is handled in #30230 from now on.

For skip to docs nav, maybe could we simply hide it on smaller screen with utility classes?

2020-02-18 12:52 UTC, patrickhlauke commented
> For skip to docs nav, maybe could we simply hide it on smaller screen with utility classes?

i guess that would be the least bad alternative, yes

2020-02-18 12:57 UTC, ffoodd commented
This is done. :)

2020-03-19 07:55 UTC, XhmikosR commented
@mdo @patrickhlauke: do you think this is ready to land in v5?

2020-03-19 08:37 UTC, patrickhlauke commented
@XhmikosR @ffoodd this looks good, yes.

on a completely separate note...the hamburger button on small screen lacks any kind of focus indication. is that already noted/addressed somewhere?

![small screen docs navigation with hamburger menu button](https://user-images.githubusercontent.com/895831/77047586-e251c800-69bc-11ea-88f9-54a685dd6f2b.png)

2020-03-19 08:40 UTC, XhmikosR commented
>on a completely separate note...the hamburger button on small screen lacks any kind of focus indication. is that already noted/addressed somewhere?

Nope, we should fix it in a separate PR targeting master, good catch!

@ffoodd please rebase and clean up your patches when you have some time :)

Still wondering if we should backport this. Thoughts?

2020-03-19 08:41 UTC, patrickhlauke commented
> Nope, we should fix it in a separate PR targeting master, good catch!

i'll file a fresh issue

2020-03-19 08:55 UTC, patrickhlauke commented
> Still wondering if we should backport this. Thoughts?

would be nice if we could, but not a deal-breaker if we'd rather concentrate on more pressing matters

2020-03-19 15:20 UTC, XhmikosR commented
I added in the 4.4.2 project to track this and we can backport it later

2020-03-23 10:02 UTC, ffoodd commented
@XhmikosR Rebased!

2020-03-23 13:16 UTC, XhmikosR approved these changes

2020-03-23 13:19 UTC, XhmikosR requested changes

2020-03-23 13:19 UTC, XhmikosR commented on site/assets/scss/_skippy.scss
> +  top: map-get($spacers, 2);
Actually, @ffoodd can you remove `map-get`s and use the values directly? We don't do this anywhere else.

2020-03-23 14:18 UTC, XhmikosR approved these changes

2020-03-23 14:23 UTC, merged

2020-05-26 03:20 UTC, XhmikosR commented
@MartijnCuppens @ffoodd so what's it going to be with this? Currently we have the patch on master, and I'm tracking in v4-next, but I recall we had some second thoughts?

2020-05-26 05:04 UTC, ffoodd commented
Indeed, I'll try something else today.