Floating labels improvements
twbs/bootstrap pull request #30966
Opened 2020-06-04 09:31 UTC by ffoodd

Next to #30965 — for v5 concerns.

1. Edge fallback can be accessible by not making labels `display: none` and simply switching to flex reversed layout…
2. Refactored things a bit since we have plenty of vendor prefixes in this file, whilst Autoprefixer runs on this file.

2020-06-16 02:09 UTC, mdo submitted a review, later dismissed

2020-06-16 02:12 UTC, mdo commented
Testing this on Netlify in IE11 isn't super clear to me... that's likely because I'm looking at v5's code that doesn't support IE at all anymore, but the example doesn't work there anymore. Signed off on this earlier, but going to retract and punt to alpha 2 to confirm a few things first <3.

2020-06-17 14:45 UTC, XhmikosR commented
Could be because the branch was behind, have another try @mdo. Note that this PR is for Edge not IE since IE is not supported on v5.

2020-06-22 08:13 UTC, XhmikosR requested changes

2020-06-22 08:13 UTC, XhmikosR commented on site/content/docs/5.0/examples/floating-labels/floating-labels.css
> -.form-label-group input::-webkit-input-placeholder {
Better put these back. The prefixes are automatically added based on our browserslist config.

2020-06-24 11:10 UTC, XhmikosR approved these changes

2020-06-24 11:11 UTC, merged