docs: add info on modifying and adding utilities
twbs/bootstrap pull request #31328
Opened 2020-07-19 18:15 UTC by Luke-zhang-04

- The documentation should show how to modify and add utilities to the existing utilities without directly modifying `node_modules`
- The current documentation currently shows "adding custom utility groups" by overriding the existing `$utilities` map
- Changes use `map-merge` and `map-get` functions to modify the current `$utilities` instead of overriding it

2020-08-16 08:37 UTC, happy07-cm commented
[packers and movers pune](happypackers.in)

2020-09-15 02:47 UTC, mdo requested changes

2020-09-15 02:47 UTC, mdo commented on site/content/docs/5.0/utilities/api.md
> +Make sure to import this file instead of the default file in your Bootstrap imports
```suggestion
Add new utilities with `map-merge`. Start by importing the utilities stylesheet, then use `map-merge` to add new properties and values.
```

2020-09-15 02:47 UTC, mdo commented on site/content/docs/5.0/utilities/api.md
> +Make sure to import this file instead of the default file in your Bootstrap imports
```suggestion
Modify existing utilities with `map-get` and `map-merge`. Once again, be sure to import the utilities stylesheet before your custom utilities.
```

2020-09-15 02:47 UTC, mdo commented on site/content/docs/5.0/utilities/api.md
> +@import "[PATH TO BOOTSTRAP]/scss/utilities";
```suggestion
@import "bootstrap/scss/utilities";
```

2020-09-15 02:47 UTC, mdo commented on site/content/docs/5.0/utilities/api.md
> +@import "[PATH TO BOOTSTRAP]/scss/utilities";
```suggestion
@import "bootstrap/scss/utilities";
```

2020-10-31 07:17 UTC, XhmikosR commented
@mdo @MartijnCuppens is there something else needed here?

2020-11-02 17:04 UTC, mdo commented
This definitely needs copy edits, and more over, I think the API page needs some updates to clarify a few things. Right now, some sections read like you can just declare `$utilities: ()` anywhere and it'll _modify_ the existing `$utilities` map, but it in fact overrides it entirely. We should clearly document how the API works, and then how to add to it with your own custom utilities without replacing the default utils.

2020-11-02 17:09 UTC, mdo commented
Captured the above in #32049.

2020-11-03 18:45 UTC, mdo commented
Merged this into #32049 and riffed on it more. Thanks!

2020-11-03 18:45 UTC, closed without merging