extend jquery after domContentLoaded event is fired
twbs/bootstrap pull request #32024
Opened 2020-10-30 23:32 UTC by tidusIO

I've added waiting for domContentLoaded event before extending jQuery. That's one possible solution to be sure, that data attributes of body can be readed.
Reference to issue: https://github.com/twbs/bootstrap/issues/31202

2020-10-31 06:52 UTC, Johann-S requested changes
Hi @tidusIO,

Thanks for your work 👍 

The overall is good, it needs just a few unit tests

2020-10-31 06:52 UTC, Johann-S commented on js/src/util/index.js
> +const onDOMContentLoaded = callback => {
Can you add a unit test here please ?

2020-10-31 09:03 UTC, tidusIO commented on js/src/util/index.js
> +const onDOMContentLoaded = callback => {
This function is tested now.

2020-10-31 09:35 UTC, tidusIO commented
It would be useful having some tests mocking getjQuery or jquery in window object, so that the uncovered parts are covered.

I'm struggling a bit with mocking these parts.

2020-10-31 10:01 UTC, tidusIO commented
We still have the problem in event-handler.js, when calling getjQuery().

2020-10-31 11:01 UTC, tidusIO commented
I would prefer a way like this: https://github.com/twbs/bootstrap/commit/ff1fa49b88e1c48de603f1613b04650d2f8354d0
It's much cleaner and there shouldn't be no problems. If we'd implement it with event listener, the problem could be, that the user has to wait for DOMContentLoaded at some places too.

2020-10-31 17:48 UTC, Johann-S commented on js/src/dom/event-handler.js
> +      onDOMContentLoaded(() => {
we don't need to wait for the DOM content to be loaded here because we don't register any jQuery plugin here

2020-10-31 21:00 UTC, Johann-S commented
it seems something decreased the minimum coverage required

2020-10-31 21:12 UTC, tidusIO commented
Do you know, if coverage also includes `js-test-jquery`?

2020-10-31 21:34 UTC, Johann-S commented
The coverage doesn't include the jQuery part.
I don't think it's really necessary since jQuery is a very small part of our codebase and the main goal of v5 is to work without jQuery

2020-10-31 21:45 UTC, tidusIO commented
Okay, still not familiar enough with bootstrap codebase. I simply overlooked the `/* istanbul ignore if */` statements.

2020-10-31 21:52 UTC, Johann-S approved these changes
Thanks for your hard work @tidusIO 👍

2020-11-01 06:01 UTC, XhmikosR commented on js/src/util/index.js
> +  if (document.readyState === 'loading') {
Just to confirm, this should work with defer too?

2020-11-01 12:39 UTC, XhmikosR commented
@tidusIO apart from my comment above, can you please make a CodePen with the scripts in `head` so that we can test?

2020-11-01 13:12 UTC, tidusIO commented
Yes, I've replied your comment. I can, but probably not before Wednesday.

2020-11-01 13:30 UTC, XhmikosR commented
NVM I tested it myself and it works as expected, thanks for the PR!

2020-11-01 13:32 UTC, merged

2021-06-14 09:58 UTC, rpokrovskij commented
Bad decision. Jquery plugins should be loaded in developer defined order: there is convention that this order is maintained by `script` loading.   How to control this order after you broke it with domContentLoaded  ? What if every jquery plugin start doing it this way?

2023-12-25 11:14 UTC, NefedovIv commented
Rly like last comment. We works with sharepoint onprem, and have a problem there. SP have own event model, many usefull events trigered before DOMContentLoaded without access to jquery bootstrap plagins. We spand a time for only understand that plagins extend performed in postponed format.