Add focus visibility on tabs with pills
twbs/bootstrap pull request #32357
Opened 2020-12-07 02:48 UTC by mayralgr

Closes #31427 

Proposal: add the scss variables for the hover and focus

![change_css](https://user-images.githubusercontent.com/16580567/101303683-311de700-3804-11eb-9865-c703d1ba6a1f.gif)

2020-12-07 07:40 UTC, patrickhlauke commented
I think this should specifically target only the pills nav links, as this PR in its current form affects all nav links - see, for instance, the top navigation in the header (Home, Docs, Examples ...) https://deploy-preview-32357--twbs-bootstrap.netlify.app/

![Nav with hovered 'examples' showing the blue hover outline](https://user-images.githubusercontent.com/895831/101322755-76233700-385f-11eb-97f6-9a5a62f3783d.png)

2020-12-07 07:42 UTC, patrickhlauke requested changes

2020-12-07 07:42 UTC, patrickhlauke commented on scss/_variables.scss
> +$nav-link-focus-box-shadow:        0 0 0 $nav-link-focus-width $nav-link-focus-color !default;
make it specific to `$nav-pills-link...`

2020-12-09 00:05 UTC, mayralgr commented
@patrickhlauke changes where made, let me know if another change is needed

2020-12-10 06:22 UTC, mdo requested changes
We shouldn't be setting focus styles (the box-shadow) on hover. Will review in more depth likely after beta 2.

2020-12-11 21:06 UTC, mayralgr commented
@mdo I left it just with the focus. Let me know if it is the correct approach.

2020-12-13 23:03 UTC, patrickhlauke commented
> We shouldn't be setting focus styles (the box-shadow) on hover. Will review in more depth likely after beta 2.

well, it was just replicating what buttons do...i personally wouldn't have minded.

2020-12-13 23:28 UTC, patrickhlauke commented
beyond that though, https://deploy-preview-32357--twbs-bootstrap.netlify.app/docs/5.0/components/navs-tabs/ looks good to me

2020-12-13 23:28 UTC, patrickhlauke approved these changes

2020-12-15 14:33 UTC, mayralgr commented
@mdo is the anything else needed ? Thank you!

2020-12-20 23:12 UTC, patrickhlauke commented
This looks good to me. @mdo / @twbs/css-review ?

2020-12-20 23:23 UTC, ESA-Security-Group commented
16 gången du mailat mig nu? Var fan är du egentligen?

Location...!?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Patrick H. Lauke <notifications@github.com>
Sent: Monday, December 21, 2020 12:17:03 AM
To: twbs/bootstrap <bootstrap@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [twbs/bootstrap] Add focus visibility on tabs with pills (#32357)


This looks good to me. @mdo<https://github.com/mdo> / @twbs/css-review<https://github.com/orgs/twbs/teams/css-review> ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/twbs/bootstrap/pull/32357#issuecomment-748684866>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALLTNOWRA226SIFTMFCMRYLSV2AW7ANCNFSM4UP2DJRQ>.

2021-01-13 06:31 UTC, mdo commented
Sorry I let this fall off my radar.

Couple things come to mind now:

- We set `:hover, :focus` on all `.nav-link`s, so that's my bad.
- However, we don't actually set any focus styles. Seems to me if we wanted to do this right, we'd set separate hover and focus styles.
- And, we'd apply or customize those styles by nav modifier class (pills vs tabs).
- Safari, Chrome, and Firefox all have separate focus styles. In Safari, I end up seeing double focus outlines. Chrome it's a dark outline. Firefox, kinda nothing, but sometimes a thin dotted line.

Will dive into this a bit myself and see what comes to mind for v5.

<img width="845" alt="Screen Shot 2021-01-12 at 10 26 48 PM" src="https://user-images.githubusercontent.com/98681/104414907-dde73480-5525-11eb-9adf-6dcf2f8c8bff.png">
<img width="828" alt="Screen Shot 2021-01-12 at 10 27 34 PM" src="https://user-images.githubusercontent.com/98681/104414908-df186180-5525-11eb-82d3-f666ddfb5596.png">

2021-01-17 11:06 UTC, patrickhlauke commented
> Safari, Chrome, and Firefox all have separate focus styles. In Safari, I end up seeing double focus outlines. Chrome it's a dark outline. Firefox, kinda nothing, but sometimes a thin dotted line.

for the regular (non-pill) tabs, this needs to be this way because otherwise, you either define `:focus` explicitly and then it applies for mouse/touch users when they interact with the tabs as well (which would look odd), OR you use `:focus-visible` but then polyfill it ... it's the same old problem that keeps bubbling up.

could be sorted for pills I guess, as there it would look less disruptive if an explicit `:focus` is defined and applied even after mouse/touch.

2021-01-17 17:03 UTC, mdo commented
I think the doubling up I saw was because `outline` wasn't reset when `box-shadow` was added.

2021-01-18 00:22 UTC, patrickhlauke commented
> I think the doubling up I saw was because `outline` wasn't reset when `box-shadow` was added.

ah gotcha, we can fix it just for the pill ones, yes

2021-01-18 00:25 UTC, patrickhlauke commented on scss/_nav.scss
> +    }
add an `outline: 0` to suppress double focus styles

2021-01-18 02:58 UTC, mayralgr commented
Hi guys I did this minor change but I am having trouble with the tests, as I left it I think I need a rebase or something ( I try but still gives an error ) any help ? 😅

2021-01-18 09:21 UTC, patrickhlauke commented
i think you forgot to `git pull` changes that were made to your branch here (as a result of rebasing/merging in changes here on github) before making the latest change, so your PR suddenly included lots of reverts of things that blew the tests up. i think i managed to manually fix it

2021-02-09 13:04 UTC, XhmikosR commented
Haven't looked at it too close, but it seems like the outline results in duplicate borders for active tabs and -1px or so for inactive ones.

2021-02-09 22:28 UTC, patrickhlauke commented
> Haven't looked at it too close, but it seems like the outline results in duplicate borders for active tabs and -1px or so for inactive ones.

not sure i'm following what you're seeing. which browser? which example specifically? got a screenshot/pointer to it?

2021-02-16 14:45 UTC, XhmikosR commented
Sorry, for the late reply. I probably mixed the examples and I was looking at the `nav-tabs` example, not the `nav-pills` one.

It works, but the focus style seems to overlap with the other nav-items.

2021-02-16 15:04 UTC, patrickhlauke commented
> Sorry, for the late reply. I probably mixed the examples and I was looking at the `nav-tabs` example, not the `nav-pills` one.
> 
> It works, but the focus style seems to overlap with the other nav-items.

Yeah I think there's no clean way around this. As that overlapping focus style only shows for keyboard users as they navigate through, and momentarily (before either the link is followed or, in case of dynamic tabs, when that tab then becomes active) it's something I think is not completely deal-breaking (otherwise we have to start moving to inner shadows or something rather that box shadows)

> 
> Edit: also browsers seem to have their own focus styles already, and with this patch we will have an inconsistent style in nav-tabs?

If you go to https://getbootstrap.com/docs/5.0/components/navs-tabs/#pills with Firefox (at least on Windows), there's no visible default focus indication. See this animation where I go back and forth with `Tab` and note how on the active one nothing can be seen when it gets focus:

![firefox-pills-focus](https://user-images.githubusercontent.com/895831/108080600-f76d2600-7067-11eb-8a6d-2a3bc11683d1.gif)

With this change, it's at least consistent across all browsers.

![firefox-pills-focus2](https://user-images.githubusercontent.com/895831/108080883-41560c00-7068-11eb-8dc7-1951e2698944.gif)

Leaving it up to browser default in this case is not a good idea, because of this variability (while yes, Chrome for instance has very clear default focus outline).

2021-02-16 16:19 UTC, XhmikosR commented
All right, let's wait for @twbs/css-review to have a look. I'd swear there was some kind of CSS property we recently used in another RP .

2021-02-16 16:38 UTC, patrickhlauke commented
> All right, let's wait for @twbs/css-review to have a look. I'd swear there was some kind of CSS property we recently used in another RP .

ah, you might be thinking of https://developer.mozilla.org/en-US/docs/Web/CSS/isolation ... hmm, this may help yes, but not sure how the semi-transparent box shadow over the active pill would show, if at all

2021-02-16 16:40 UTC, ffoodd commented
@XhmikosR @patrickhlauke Just tried, it doesn't help there since our `box-shadow` is the same color than our `background`, with a transparency. Either we change this color (and drop transparency, but that sounds inconsistent with other styles) to make it noticeable, or we consider adding space between pills?

There might be other approaches but I'm unable to find one for now.

2021-02-16 19:30 UTC, XhmikosR commented
I'd vote to just keep it simple and consistent for the time being :)

2021-03-08 21:27 UTC, AstroOrbis approved these changes

2021-05-04 10:18 UTC, patrickhlauke commented
This has slipped a bit off our radar... @mdo and @twbs/css-review in general, what are your feelings on this? it's probably not perfect for all circumstances, but does patch a gap in accessibility we currently have.

2021-05-04 11:08 UTC, ffoodd approved these changes
LGTM, not perfect but a good patch for now 👌

Focus styles are a whole topic deserving closer attention.

2021-08-29 21:38 UTC, GeoSot commented
@twbs/css-review  may we put this on a following project or close it?

2022-12-29 04:40 UTC, mdo commented
Focus styles coming in #33125.

2022-12-29 04:40 UTC, closed without merging