Grammatically update the doc
twbs/bootstrap pull request #33267
Opened 2021-03-05 08:14 UTC by mohamed-khoualed

Small grammatical update to the  Bootstrap doc

2021-03-05 10:19 UTC, patrickhlauke requested changes, later dismissed
only change i'd say is leave the "mobile first" without hyphen

2021-03-05 10:19 UTC, patrickhlauke commented on site/content/docs/5.0/getting-started/introduction.md
> +That's all you need for the overall page requirements. Visit the [Layout docs]({{< docsref "/layout/grid" >}}) or [our official examples]({{< docsref "/examples" >}}) to start laying out your site's
both with and without the "the" works (or rather, the sentence is a tiny bit awkward either way). no strong preference either way.

2021-03-05 10:19 UTC, patrickhlauke commented on site/content/docs/5.0/getting-started/introduction.md
> +Bootstrap is developed *mobile-first*, a strategy in which we optimize code for mobile devices first and then scale up components as necessary using CSS media queries. To ensure proper rendering and
in this case, both with and without the hyphen works, I think - and there's quite a few instances of it being used without. Slight preference for having it without, here, as it's not directly an adjective (i.e. if the sentence was "is developed with a mobile-first approach" then yes, i'd go with hyphen ... but in this case it looks better to me without)

2021-03-05 10:19 UTC, patrickhlauke commented on site/content/docs/5.0/getting-started/introduction.md
> +For more straightforward sizing in CSS, we switch the global `box-sizing` value from `content-box` to `border-box`. This ensures `padding` does not affect the final computed width of an element, but
yup, as with my comment about "mobile first" vs "mobile-first", this is a case where the hyphen does make sense as "third-party" is used as an adjective.

2021-03-05 10:19 UTC, patrickhlauke commented on site/content/docs/5.0/getting-started/introduction.md
> +- Developers should use the keyword `bootstrap` on packages that modify or add to the functionality of Bootstrap when distributing through [npm](https://www.npmjs.com/search?q=keywords:bootstrap) or
both "which" and "that" are valid. using "that" is probably a bit more natural-sounding

2021-03-10 23:56 UTC, mdo commented on site/content/docs/5.0/getting-started/introduction.md
> +That's all you need for the overall page requirements. Visit the [Layout docs]({{< docsref "/layout/grid" >}}) or [our official examples]({{< docsref "/examples" >}}) to start laying out your site's
```suggestion
For next steps, visit the [Layout docs]({{< docsref "/layout/grid" >}}) or [our official examples]({{< docsref "/examples" >}}) to start laying out your site's content and components.
```

2021-03-10 23:56 UTC, mdo commented on site/content/docs/5.0/getting-started/introduction.md
> +Bootstrap is developed *mobile-first*, a strategy in which we optimize code for mobile devices first and then scale up components as necessary using CSS media queries. To ensure proper rendering and
```suggestion
Bootstrap is developed *mobile first*, a strategy in which we optimize code for mobile devices first and then scale up components as necessary using CSS media queries. To ensure proper rendering and touch zooming for all devices, **add the responsive viewport meta tag** to your `<head>`.
```

2021-03-10 23:56 UTC, mdo approved these changes

2021-03-11 03:05 UTC, merged