Dropdown: support `.dropdown-item` wrapped in `<li>` tags
twbs/bootstrap pull request #33649
Opened 2021-04-15 15:23 UTC by cpsievert

Backports #33634 into v4

2021-04-16 05:50 UTC, XhmikosR commented
Let's wait until the main PR has landed and this one's tests pass.

2021-04-18 13:09 UTC, alpadev requested changes

2021-04-18 13:09 UTC, alpadev commented on js/tests/unit/tab.js
> +    assert.notOk($tabs.find('.nav-link').hasClass('active'))
I think you need to exclude the `dropdown-toggle` here like `.find('.nav-link:not(.dropdown-toggle)')` to make the test work.

2021-04-19 15:09 UTC, cpsievert commented
FWIW, the failure on Node 14 doesn't appear to be related to this PR

2021-04-28 00:32 UTC, alpadev approved these changes

2021-04-28 04:02 UTC, merged