Move .col-* classes to same media query after .row-cols-* classes
twbs/bootstrap pull request #34341
Opened 2021-06-23 19:58 UTC by mdo

Fixes #34335.

2021-06-23 21:07 UTC, angrymouse approved these changes

2021-06-24 05:07 UTC, danielkauffman reviewed
Fixes #34335 awesome!

CodePen showing the issue in v5.0.2: https://codepen.io/rocksolidsolutions/pen/zYZVeeq

CodePen showing the fix in this branch: https://codepen.io/rocksolidsolutions/pen/qBrzgKq

Building the dist files and running `git diff v5.0.1 -- dist/css/bootstrap-grid.css` and `git diff v5.0.2 -- dist/css/bootstrap-grid.css` both seem okay.

I suppose it would be good to check that #33621 is still fixed after this change.

2021-06-24 16:20 UTC, danielkauffman reviewed
Per @lacutah #33530 expects `row-cols*` to override `col`. I theoretically like the cleanliness of having all of the `row-cols*` declarations together and all of the `col` declarations together (as with this PR) but doing so either breaks `cols row-cols` or breaks `col-N col-breakpoint`. I'm not sure how widespread each of these use cases are. But the simple solution (assuming both cases need to be supported) seems to be ordering the declarations first `col` then `row-cols*` then `col-breakpoint*`.

2021-06-29 12:33 UTC, ffoodd commented
I agree with @danielkauffman here. We have an issue with this PR regarding `.col` (without breakpoint): see #33621 [CodePen using this PR's CSS](https://codepen.io/ffoodd/pen/VwbwRdW) to reproduce.

`.col` should always be first, and `.col-*` last.

2021-06-29 12:37 UTC, ffoodd requested changes

2021-06-29 12:37 UTC, ffoodd commented on scss/mixins/_grid.scss
> +      .col#{$infix} {
IMHO we should skip if `$infix` is empty, and prefer to set `.col` before any loop. Maybe hard-coded in our main grid file, maybe?

2021-07-28 19:59 UTC, mdo commented
Punting on this for #34612 right now.

2021-07-28 19:59 UTC, closed without merging