input-group with form-floating
twbs/bootstrap pull request #34527
Opened 2021-07-19 02:01 UTC by 719media

2021-09-01 14:30 UTC, ffoodd approved these changes
Looks good to me, awesome work! Thanks!

I made [a fork of your CodePen](https://codepen.io/ffoodd/pen/jOwqYzO) using the new `5.1`  docs path to show the result.

The question now is whether we want to support this or not? What weird issues may pop out of this?

2021-09-01 15:26 UTC, 719media commented
@ffoodd
I went back and reviewed the PR since it was from a month back.
Only thing I saw was a better place for the z-index rule, so I moved it to a more appropriate place.

2021-09-01 15:46 UTC, ffoodd commented
Indeed, nice move! I didn't catch this, thanks :)

2021-10-06 18:44 UTC, 719media commented
It would be awesome if this could be merged for 5.2
With the latest 5.1.2 release, there is a minor issue with how buttons now have align-self: center (see https://github.com/twbs/bootstrap/pull/34834). That can be rectified by adding something like `align-self: stretch` into the `.input-group .btn` rule in the changed file. I didn't make that change in this PR, because it's not entirely a "form-floating" thing.
Thanks

2021-12-13 12:26 UTC, nkdas91 reviewed
There is still an issue with this if we add validation feedbacks ```.valid-feedback```, ```.invalid-feedback```.

https://codepen.io/nkdas91/pen/JjrbeBM

![image](https://user-images.githubusercontent.com/25012345/145812028-899f744b-7c91-42c5-a7c2-e9087a9feaaf.png)

2021-12-13 21:28 UTC, 719media commented
Yes, I don't have an easy solution for those. My personal opinion of bootstrap validation is that it is so incredibly brittle, I never use it. For me, this is another example of such.

However, if you change the `<div class="form-floating">` to `<fieldset class="form-floating">`, and move the feedback outside, it actually will work with bootstrap validation.

https://codepen.io/nefiga/pen/KKXapZG

2022-02-08 11:42 UTC, ffoodd commented
Back to this: this PR lacks documentation and examples, which would allow to mention edge cases.

Regarding validation feedback, using `fieldset` works but is far from ideal when it comes to accessibility (since it'd require a `legend` at least). I'd better recommend to move the feedback outside and associate it to the form input using `id` and `aria-describedby`.

Then you may use spacing utilities to align things as intended, and you'd benefit from the `.has-validation` class feature on input groups to get rounded corners back. BTW I recommend to only insert feedbacks when needed, instead of having several hidden `div`s that mess up with rounded corners in input groups.

I made [a quick working CodePen demonstrating this](https://codepen.io/ffoodd/pen/VwrPqWe). Could be made better by using `querySelectorAll()` and looping but no need for this POC.

If that sounds good to all of you, @719media would you mind trying to add some docs for this? I guess the form floating page at least need some updates, and maybe the validation page too?

2022-02-08 11:43 UTC, ffoodd requested changes, later dismissed
At least needs docs :)

2022-03-01 05:17 UTC, 719media commented
@ffoodd OK I have added some basic docs for the floating labels page.

2022-03-03 15:50 UTC, AgentSmith0 commented
Would be nice if this PR could me merged. Thanks!

2022-03-20 04:33 UTC, 719media commented
@ffoodd any way we could get this merged for 5.2.0? Thanks

2022-05-19 15:12 UTC, fhughes90 commented
Waiting on an update for this as well

2022-06-14 06:21 UTC, 719media commented
@mdo Any changes requested to get this merged? Or are there things that still just don't feel right here you can expound on?

2022-07-04 09:39 UTC, nkdas91 commented
Fixes #36636

2022-07-17 23:26 UTC, mdo commented
Rebased, squashed, and edited a couple things in #36759. Closing this PR for that one.

2022-07-17 23:26 UTC, closed without merging