reolved #34833
twbs/bootstrap pull request #34834
Opened 2021-08-28 15:26 UTC by zaidjawed

Issue: #34833
When placing a button with size classes as direct child of a div with d-flex, size is not respected

```
<div class="d-flex flex-row">
  <button type="button" class="m-2 btn btn-primary">Default</button>
  <button type="button" class="m-2 btn btn-primary btn-sm">Small</button>
  <button type="button" class="m-2 btn btn-primary btn-md">Medium</button>
  <button type="button" class="m-2 btn btn-primary btn-lg">Large</button>
</div>
```
Produces
![131220125-75cef342-d108-442d-811b-25a2ecb679a1](https://user-images.githubusercontent.com/87218997/131222783-21805d97-ec16-4472-8d60-8c3f2fdc902f.png)

While

```
<div class="d-flex flex-row">
  <div>
    <button type="button" class="m-2 btn btn-primary">Default</button>
    <button type="button" class="m-2 btn btn-primary btn-sm">Small</button>
    <button type="button" class="m-2 btn btn-primary btn-md">Medium</button>
    <button type="button" class="m-2 btn btn-primary btn-lg">Large</button>
  </div>
</div>
```

Produces
![131220163-0b761e9f-f518-4d68-bc99-43052cc18992](https://user-images.githubusercontent.com/87218997/131222799-04be0851-559e-42c2-b511-3e8d06b9431d.png)

Solution:

According to [W3Schools](https://www.w3schools.com/cssref/css3_pr_align-items.asp) 
the default value of align-items is **stretch** which might be causing this issue.

I simply added **align-self to center** to give a default value to center if the buttons are a direct child of flex.

2021-09-01 08:50 UTC, ffoodd requested changes
Feels safe to me, thanks for submitting this :)

2021-09-01 08:50 UTC, ffoodd commented on scss/_buttons.scss
> +
Please drop the line breaks and comments, this is not needed.

2021-09-01 11:05 UTC, ffoodd approved these changes

2021-09-01 23:00 UTC, mdo approved these changes
I'm into it!

2021-09-07 20:21 UTC, merged

2021-10-05 17:10 UTC, wKovacs64 commented
This was a breaking change. Can't you just apply `align-items-center` on your flex container instead?

```
<div class="d-flex flex-row align-items-center">
  <button type="button" class="m-2 btn btn-primary">Default</button>
  <button type="button" class="m-2 btn btn-primary btn-sm">Small</button>
  <button type="button" class="m-2 btn btn-primary btn-md">Medium</button>
  <button type="button" class="m-2 btn btn-primary btn-lg">Large</button>
</div>
```

2021-10-06 18:21 UTC, andreas-venturini commented
This broke most of the button styles in our application. I strongly suggest highlighting this change more prominently in the Changelog (possibly even mark as a breaking change). This is not what we would've expected of a minor patch release.

Anyway, keep up the good work :v:

2021-10-06 18:49 UTC, andreas-venturini commented
@ffoodd done https://github.com/twbs/bootstrap/issues/35126

Thinking about this some more, I think you should consider reverting (I'm not disagreeing with this change per se, it might just be a bit too much for a minor patch release)

2021-10-08 09:56 UTC, amshkv commented
This change was unexpected and broke the part of the interface where the parent was `d-flex` with `align-items-start`
Now we need to redefine all `btn` in this layout.
Especially unexpected for `flex-column`
![image](https://user-images.githubusercontent.com/23584933/136536892-e71e6b14-481d-457c-a6a1-c9029576a9be.png)