Fixes #34852 Select does not have border radius modificators for large and small variant
twbs/bootstrap pull request #34853
Opened 2021-08-31 12:32 UTC by crdo

Adds border-radius modifiers for small and large Select to _form-select.scss
Adds corresponding variables to _variables.scss

2021-09-01 08:03 UTC, ffoodd commented on scss/forms/_form-select.scss
> +  @include border-radius($form-select-border-radius-sm, 0);
Why did you add a fallback to `0`?

2021-09-01 08:12 UTC, ffoodd requested changes
No need for the `0` fallback, but apart from that it's really good, thanks!

2021-09-01 08:49 UTC, crdo commented on scss/forms/_form-select.scss
> +  @include border-radius($form-select-border-radius-sm, 0);
Yes, you are right. Removed.

2021-09-01 09:02 UTC, ffoodd approved these changes
Thanks!

2021-09-07 20:24 UTC, mdo approved these changes

2021-09-07 20:35 UTC, merged