Fix `btn-light`'s active state color
twbs/bootstrap pull request #35293
Opened 2021-10-28 13:40 UTC by tpg-gulshan

~~Fixes #35258~~

Fixes #34123

2021-11-03 07:59 UTC, ffoodd requested changes
Thanks for submitting this! 
This is not the best way though, since you're making an exception were we try to have a generic behaviour.

I think we need to question the light color itself, since your issue relates more  to the color being to close to white (thus lightening it has almost no effect).

2021-12-15 13:43 UTC, ffoodd commented
Back to this, I'd say either we consider darkening our default light color (which would concern everything using it) or we consider using the `button-variant()` mixin with defined parameters, instead of [simply using the color itself](https://github.com/twbs/bootstrap/blob/main/scss/_buttons.scss#L55).

I'd recommend going for this, since we also have contrast issues with some of our outline buttons, that would benefit from a less generic way of building buttons variants — meaning probably to drop the very simple loop and declare at least some variants indepently. This is used [in Boosted](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/scss/_buttons.scss#L67) at least, even if we don't need that much specificity.

By doing so, we could get closer to what v4 looked like. Not quite sure yet of how the best values to use, but if you want to give it a shot it'd be really appreciated :)

2021-12-16 10:20 UTC, tpg-gulshan commented
Thanks, @ffoodd for your observations on this.
I'll look into it again and spend some more time fixing it in a different and better way. I will also consider your idea to make it done.

2022-04-13 01:24 UTC, mdo commented
Is this still something you want to iterate on @tpg-gulshan or should we take a crack at it?

2022-04-14 03:59 UTC, mdo commented
Thinking about this in another way in #36168.

2022-06-08 22:32 UTC, closed without merging