Convert border utilities to CSS variables
twbs/bootstrap pull request #35428
Opened 2021-11-30 05:15 UTC by mdo

- Updates the utilities mixin to check for specific CSS variable names via `css-variable`
- Bonus fix: we now prevent local variables for `0` value utilities (e.g., `.border-top-0` no longer sets `--bs-border-opacity: 1`
- Adds new `.border-opacity-*` classes
- Adds new root variables: `--bs-border-color`, `--bs-border-style`, `--bs-border-width`
- Documents the new variable changes

Todo:
- [ ] Document in migration guide
- [ ] Clean up language and comments in the diff

2021-11-30 06:51 UTC, alecpl commented on scss/_utilities.scss
> +        null: var(--bs-border-width) var(--bs-border-style) var(--bs-border-color),
Shouldn't this use `#{$variable-prefix}`?

2021-11-30 07:00 UTC, alecpl commented
This `#{$variable-prefix}` everywhere is kinda distracting. Have you considered something like https://dev.to/felipperegazio/css-custom-properties-vars-with-sass-scss-a-practical-architecture-strategy-1m88 ?

2021-11-30 07:51 UTC, mdo commented
Yup, that's coming next :).

2021-12-14 20:47 UTC, ffoodd requested changes
Those are nice additions, almost there 👌

2021-12-14 20:47 UTC, ffoodd commented on site/content/docs/5.1/utilities/borders.md
> +Or, choose from any of the `.bg-opacity` utilities:
`.border-opacity`, isn't it?

2021-12-14 20:47 UTC, ffoodd commented on site/content/docs/5.1/utilities/api.md
>      class: text-opacity,
Is this a good example? If I understand the changes in utilities API, result would be the same if we dropped `css-variable-name`, wouldn't it?

2022-02-15 01:09 UTC, mdo commented
Changes addressed @ffoodd, ready for another review :D.

2022-02-25 22:57 UTC, mdo commented
Added another commit to replace instances of `$border-color` and `$border-width` with their new CSS variable counterparts.

2022-02-28 14:25 UTC, ffoodd approved these changes
One of the new sentence sounds weird, but apart from that it works great!

2022-02-28 19:29 UTC, mdo commented on site/content/docs/5.1/utilities/api.md
> +Set the `css-var` boolean option to `true` and the API will generate local CSS variables for the given selector instead of the usual `property: value` rules. Add an optional `css-variable-name` have
Fixed, definitely didn't make sense hah.

2022-02-28 19:40 UTC, merged