Add in border-radius for btn-group
twbs/bootstrap pull request #35467
Opened 2021-12-05 19:59 UTC by AndyJiang99

Fixes the border-radius for btn-group #34598

2021-12-08 16:39 UTC, ffoodd requested changes
This should be added before the comment regarding double borders, with a line break between them.

Apart from that, I don't see any reason to reject this. Thanks!

2021-12-08 22:09 UTC, AndyJiang99 commented
> This should be added before the comment regarding double borders, with a line break between them.
> 
> Apart from that, I don't see any reason to reject this. Thanks!

Thanks for letting me know. I've addressed the changes, please take another look when you get a chance to. Thanks! Additionally, since I'm a first-time contributor for this repo, I need a maintainer to approve running workflows.

2021-12-08 22:57 UTC, ffoodd requested changes

2021-12-08 22:57 UTC, ffoodd commented on scss/_button-group.scss
> +  // Prevent white corners if shadow or shadow-lg property applied
This comment isn't really needed, the property and value speak for themselves. 

Then I guess it'd be good to go 👌

2021-12-09 07:08 UTC, AndyJiang99 commented
Addressed linting issue for border-radius on the property-disallowed-list

2021-12-09 07:56 UTC, ffoodd requested changes

2021-12-09 21:02 UTC, AndyJiang99 commented on scss/_button-group.scss
> +  border-radius: $btn-border-radius;
Gotcha, understood! No worries, addressed the changes!

2021-12-14 06:42 UTC, ffoodd approved these changes
👌

2021-12-16 08:43 UTC, merged