Add sticky bottom utility
twbs/bootstrap pull request #35518
Opened 2021-12-10 10:08 UTC by florianlacreuse

Close #35503.

2021-12-10 14:04 UTC, WinterSilence commented
how it's work?

2021-12-10 14:38 UTC, florianlacreuse commented
Live example: https://codepen.io/florianlacreuse/pen/wvrzdpY

2021-12-10 15:05 UTC, WinterSilence commented
@florianlacreuse
> Note that a sticky element "sticks" to its nearest ancestor that has a "scrolling mechanism" (created when overflow is hidden, scroll, auto, or overlay), even if that ancestor isn't the nearest actually scrolling ancestor

i.e. it's work fine if page have long body, in other case your `sticky-bottom` footer displayed at center page.

2021-12-10 15:37 UTC, florianlacreuse commented
I'm not sure what you mean. An element with `.sticky-top` can also be in middle of the page.

`.sticky-top` and `.sticky-bottom` are different than "sticky header" and "sticky footer". See: https://getbootstrap.com/docs/5.1/examples/sticky-footer/

2021-12-10 15:57 UTC, WinterSilence commented
https://codepen.io/WinterSilence/pen/BawLddW

2021-12-10 16:05 UTC, WinterSilence commented
@florianlacreuse 
> .sticky-top and .sticky-bottom are different than "sticky header" and "sticky footer". 
see [sticky header in manual](https://getbootstrap.com/docs/5.1/components/navbar/#placement)
users 100% will try add `.sticky-bottom` to footer - need notice displaying when sticky doesn't work as expected.

2021-12-10 16:21 UTC, florianlacreuse commented
Thanks for the live example, I understand better what you meant.

Yes, `.sticky-bottom` will not magically position the target element at the bottom of its "container" / ancestor. And neither does the `.sticky-top`, just that by default the elements are usually "on top".

Your example fixed: https://codepen.io/florianlacreuse/pen/MWEjvPP

2021-12-10 16:44 UTC, WinterSilence commented
@florianlacreuse yes, add this comment to `position.md`

2021-12-14 21:04 UTC, ffoodd requested changes
Thanks for the PR!

LGTM, and after double checking how `position: sticky` support compares to our current browser target, I confirm we can drop sentences regarding browser support.

2021-12-14 21:19 UTC, ffoodd commented
Regarding edge cases, I don't think we should mention them. This is how `position` works, and is really easy to mess up when you don't understand containing block.

For example, `position: fixed` does not always refer to the viewport since it refers to its containing block. Any element between the fixed element and the viewport, with e.g. a `transform`, will become its containing block. 

We don't mention such edge cases as it's in the CSS specification and we don't aim at proxying it. At least IMHO, this is still open to discussions obviously 🙂

2021-12-15 09:07 UTC, florianlacreuse commented on site/content/docs/5.1/components/navbar.md
> +Also note that **`.sticky-top` and `.sticky-bottom` uses `position: sticky`, which [isn't fully supported in every browser](https://caniuse.com/css-sticky)**.
You are right about that, I dropped it.

2021-12-15 09:08 UTC, florianlacreuse commented on site/content/docs/5.1/helpers/position.md
> +Position an element at the bottom of the viewport, from edge to edge, but only after you scroll past it. The `.sticky-bottom` utility uses CSS's `position: sticky`, which isn't fully supported in all
Done.

2021-12-15 09:12 UTC, florianlacreuse commented
I agree with @ffoodd, this is pure CSS specs.

I dropped the sentences about browser support.

2021-12-15 10:17 UTC, ffoodd approved these changes
Great, thanks!

2021-12-16 08:27 UTC, merged