Properly escape IDs in getSelector() to handle weird IDs (#35565)
twbs/bootstrap pull request #35566
Opened 2021-12-17 18:11 UTC by pierresouchay

IDs need to be escaped before document.querySelector() is called

Will fix #35565

2021-12-17 20:47 UTC, GeoSot commented
Nice job @pierresouchay . I 've done some testing it and seems it brings another 'feature', enabling use ids starting with number.

Please add some tests to support your MR 😃

2021-12-17 22:58 UTC, pierresouchay commented
@GeoSot can you approve the worklow, so I can test it does not break anything?
I'll add the test, for now I just tested in blind mode

2021-12-18 10:53 UTC, GeoSot commented
You can try `npm run js-debug` and `npm run js-lint` before pushing, too 😉

2021-12-18 14:10 UTC, pierresouchay commented
@GeoSot Thanks, I'll try to add the test this evening. Do you have suggestion on what to test? I think I'll simply change a collapse test to target 0/my/id instead of test2 id...

2021-12-18 17:05 UTC, pierresouchay commented
@GeoSot all done, I applied linter, added test with problematic ID and rebased

2021-12-18 17:22 UTC, pierresouchay commented
WIll also probably fix https://github.com/twbs/bootstrap/issues/31099

2021-12-18 17:53 UTC, GeoSot commented
You probably need to add a test on `index.spec.js` => `getSelector`  and to handle the same thing in the `getElement` function (plus proper test) 😃

2021-12-18 18:01 UTC, pierresouchay commented
> You probably need to add a test on `index.spec.js` => `getSelector` and to handle the same thing in the `getElement` function (plus proper test) 😃

Done in last commit

2021-12-18 23:09 UTC, pierresouchay commented
@GeoSot or @XhmikosR can you launch the tests, I think the PR is ready.

Regards

2021-12-20 08:51 UTC, pierresouchay commented
@GeoSot Current support is not bad https://caniuse.com/mdn-api_css_escape 

<img width="1357" alt="Capture d’écran 2021-12-20 à 09 48 57" src="https://user-images.githubusercontent.com/8089033/146739092-63c56dfd-a4f2-4e2b-8661-ef79ef1562d7.png">

Does it fit the currently supported browsers for Bootstrap?

2021-12-20 09:04 UTC, pierresouchay commented
@GeoSot I could do another minor change (if you want me to):

```js
  if (selector !== null && selector.startsWith('#')) {
    // document.querySelector needs escaping to handle IDs (html5+) containing for instance /
    selector = '#' + CSS.escape(selector.slice(1))
  }
```

to be changed to:

```js
  if (selector !== null && selector.startsWith('#') && window.CSS && window.CSS.escape) {
    // document.querySelector needs escaping to handle IDs (html5+) containing for instance /
    selector = '#' + CSS.escape(selector.slice(1))
  }
```

=> so It would work as it does now for very old browsers not supporting CSS.escape (so, would still break on non HTML4 IDs, but would work for HTML4 IDs)

2021-12-20 17:46 UTC, pierresouchay commented
Hello @XhmikosR,

I added the tests (as seen in the labels of the PR), do you need more?

(BTW: I need someone to approve the tests in order to run)

2021-12-22 23:14 UTC, pierresouchay commented
IMHO, this change fixes bugs, not all of them, ans is straightforward (while we might argue on my comment about detecting the CSS.escape() function)
The escaping of other places with non-leading # is an issue I agree, but it probably far more complex and requires more refactoring. Unfortunately, this would requires some clever parsing because the # is not supported as it is with CSS escape as it requires more context to know if we are talking about ids of "regular" selectors (I mean html 4 compliant ones).
Still I think the / is more and more an issue as it makes sense to have IDs compliant with hash based-routing/history in single web pages (that's why I found the issue in the first place)

2021-12-24 00:30 UTC, GeoSot commented
Personally, I am ok with this check 
` (selector && selector.startsWith('#') && window.CSS && window.CSS.escape)`


@XhmikosR , please tell us you opinion. shall we go with the MVP or not?

2021-12-25 10:20 UTC, pierresouchay commented
@GeoSot & @XhmikosR Done, updated the test to detected CSS.escape() in latest patch.

Merry Christmas to all of you!

2022-01-11 07:42 UTC, pierresouchay commented
@XhmikosR & @GeoSot hello,
Hope you are all doing well. Did you decide something about this PR?

Regards

2022-01-11 22:50 UTC, GeoSot commented on js/tests/unit/tab.spec.js
> +    it('should work with tab id being an int (fix #31099)', done => {
```suggestion
    it('should work with tab id being an int', done => {
```

2022-01-11 22:52 UTC, GeoSot commented
I 'll approve it as it solves the 3 issues, keeping in mind that it is not an end up solution (the other 7  occurrences have to be be changed in the future)

2022-01-11 22:52 UTC, GeoSot approved these changes

2022-01-31 09:05 UTC, pierresouchay commented
Hello @XhmikosR & @GeoSot

What should I do to get this MR being merged (I know, I have to solve conflicts first)?

Do you want to rewrite all places where a selector is used?

Regards

2022-02-23 22:43 UTC, mdo commented
@GeoSot @XhmikosR Is this PR good to go?

2022-03-18 01:04 UTC, pierresouchay commented
Ping?

2022-03-18 06:23 UTC, XhmikosR commented
Sorry for the late reply, I've been pretty busy with real life.

I'll try to have a look in the next days.

2022-07-18 16:08 UTC, pierresouchay commented
Hello @GeoSot & @XhmikosR do you want to consider this? Should I try updating it?

2022-07-20 09:11 UTC, GeoSot commented
Hello, we had discussed a bit. 
I can recall that the main thoughts were that :
* we have multiple places we are using the `querySelector` (so would be inconsistent in some cases) 
*  that in case we support this, we have to be ready for new problems in case of selectors like `#2foo .bar` or `#2foo #2bar`

So I really don't have a valid answer right now, except that I am already working on the background to make the decision and the change easier in future #36027

2022-07-24 21:20 UTC, larseggert commented
I think we get hit by this, and a fix would be welcome.
```
Uncaught DOMException: Element.querySelector: '#section-1.1' is not a valid selector
```

2022-08-23 01:16 UTC, pierresouchay commented
> Hello, we had discussed a bit. I can recall that the main thoughts were that :
> 
>     * we have multiple places we are using the `querySelector` (so would be inconsistent in some cases)
> 
>     * that in case we support this, we have to be ready for new problems in case of selectors like `#2foo .bar` or `#2foo #2bar`
> 
> 
> So I really don't have a valid answer right now, except that I am already working on the background to make the decision and the change easier in future #36027

Hello @GeoSot ,

Ok, I had another proposal, to use the following:

```js
if (selector !== null && window.CSS && window.CSS.escape) {
  selector = selector.replaceAll(/#([^\s#]+)/g, function(full,id){return "#" + CSS.escape(id)})
}
```

A few examples of results:

```
"#section-1.1 .bar".replaceAll(/#([^\s#]+)/g, function(_full,id){return "#" + CSS.escape(id)})
"#section-1\\.1 .bar" 
```

```
"#foo .bar".replaceAll(/#([^\s#]+)/g, function(_full,id){return "#" + CSS.escape(id)})
=> "#foo .bar"
```

It sounds to work well... but as you mentioned, for some weird reason, it would not work for IDs starting with numbers.

So, for some weird reason, CSS.escape('2f') => "32 f"

So, in your example:

```
"#2foo .bar".replaceAll(/#([^\s#]+)/g, function(_full,id){return "#" + CSS.escape(id)})
=> "#\\32 foo .bar" => BAD
```

From my testing, this is only an issue with identifiers starting with numbers. I don't have a clear understanding of why.

What I thus propose is to basically ignore IDs starting with a number and thus to use:

```js
if (selector !== null && window.CSS && window.CSS.escape) {
  selector = selector.replaceAll(/#([^0-9][^\s#]+)/g, function(full,id){return "#" + CSS.escape(id)})
}
```

Which gives some more correct results than the current implementation:
```
"#2foo .bar > #this-is-my-solution-1.0".replaceAll(/#([^0-9][^\s#]+)/g, function(_full,id){return "#" + CSS.escape(id)})
=> "#2foo .bar > #this-is-my-solution-1\\.0" 
```

The only downside is that it does not work completely well with IDs starting with numbers, but for everything else, it works.

What do you think?

2022-08-23 06:23 UTC, pierresouchay commented
@GeoSot huh... according to https://mothereff.in/css-escapes and my test, the CSS.escape is actually working!

So, I am gonna submit a new patch

2022-08-23 07:32 UTC, pierresouchay commented
@GeoSot @XhmikosR Ok, I am now happy with this new version, it now works by escaping all IDs, whatever their position in the selector

Works with complex selectors such as ".foo 2bar", added a UTest to ensure it works well: https://github.com/twbs/bootstrap/pull/35566/files#diff-232a393b53d525c6749638629be8a4288ec1929b51c8144fe92a41c25c885bc3R132

2022-09-27 20:05 UTC, XhmikosR commented
We need to double check if our currently supported browsers have this feature.

Apart from that:

1. as long as the change covers all cases
2. everything is covered by tests

we could try landing it.

2022-09-28 07:59 UTC, pierresouchay commented
@XhmikosR I documented what is supported: https://caniuse.com/mdn-api_css_escape

Since a feature tested, older systems will behave as they do now

2022-10-01 11:16 UTC, pierresouchay commented
@GeoSot @XhmikosR Could someone validate the workflow so all tests do converge? (I did rebase to be up-to-date with current main branch...)

2022-10-13 23:04 UTC, pierresouchay commented
Hello @GeoSot and @XhmikosR ,

- This PR will be soon 11 months old.
- It fixes lots of issues.
- It is simple enough.
- it has tests that confirm the fixes
- It degrades if feature is not supported.
- I rebased several times to have something that could be merged easily. 

What is missing?

2022-10-15 18:20 UTC, GeoSot requested changes
I am just ok with the index.js test. Let's keep it simple

> What is missing?


It doesn't miss something, and thank you a lot for your patience. The only thing is that is a difficult decision as it may impact many different cases, we haven't thought of. 

For me, it seems ok to go. Worst case scenario, we will revert it

2022-11-07 00:48 UTC, GeoSot commented
@pierresouchay I've rebased the branch, according to the last changes, but seems I did something wrong with the tab test. Can you please take a look?

2022-11-07 12:03 UTC, julien-deramond commented on .bundlewatch.config.json
> +      "maxSize": "22.80 kB"
```suggestion
      "maxSize": "23.0 kB"
```

2022-11-07 12:12 UTC, GeoSot approved these changes

2022-11-07 12:43 UTC, merged

2022-11-07 12:46 UTC, GeoSot commented
No, we are done ;) 

Thank you a lot for your patience and your time

2023-01-11 13:10 UTC, XhmikosR commented
@pierresouchay you should make a separate issue with all the info there.

2023-01-11 14:39 UTC, larseggert commented
@XhmikosR adding this to a test illustrates the bug:
```patch
diff --git a/js/tests/unit/scrollspy.spec.js b/js/tests/unit/scrollspy.spec.js
index c7951e6..704b52a 100644
--- a/js/tests/unit/scrollspy.spec.js
+++ b/js/tests/unit/scrollspy.spec.js
@@ -341,11 +341,13 @@ describe('ScrollSpy', () => {
           '  <ul class="nav">',
           '    <li class="nav-item"><a class="nav-link" id="a-1" href="#div-1">div 1</a></li>',
           '    <li class="nav-item"><a class="nav-link" id="a-2" href="#div-2">div 2</a></li>',
+          '    <li class="nav-item"><a class="nav-link" id="a-2.1" href="#div-2.1">div 2</a></li>',
           '  </ul>',
           '</nav>',
           '<div class="content" style="overflow: auto; height: 50px">',
           '  <div id="div-1" style="height: 100px; padding: 0; margin: 0">div 1</div>',
           '  <div id="div-2" style="height: 200px; padding: 0; margin: 0">div 2</div>',
+          '  <div id="div-2.1" style="height: 200px; padding: 0; margin: 0">div 2.1</div>',
           '</div>'
         ].join('')
```

2023-01-11 14:43 UTC, julien-deramond commented
@larseggert Could you please create a separate issue with this information and the problem you have? Otherwise, it is very difficult for us to track since this PR is already merged.

2023-01-11 14:46 UTC, larseggert commented
See #37858