Document how to extract inline SVGs for strict CSP
twbs/bootstrap pull request #35802
Opened 2022-02-07 20:20 UTC by scallywag

Cf. https://github.com/twbs/bootstrap/issues/25394, https://github.com/twbs/bootstrap/issues/33134

2022-02-08 15:44 UTC, ffoodd requested changes
This is great, thanks a lot. I'm still wondering if it shouldn't be moved to the Webpack page, and simply linked to from the CSP section?

Any thought?

2022-02-08 15:44 UTC, ffoodd commented on site/content/docs/5.1/customize/overview.md
> +This rule will place inline SVGs into files under the `icons/` directory of the build directory, with the filename based on the hash of the file contents.  This should allow you to use a strict CSP t
```suggestion
This rule will place inline SVGs into files under the `icons/` directory of the build directory, with the filename based on the hash of the file contents. This should allow you to use a strict CSP that does not allow inline `data:` URLs in stylesheets.
```

2022-02-08 15:44 UTC, ffoodd commented on site/content/docs/5.1/customize/overview.md
> +
A heading is needed here to introduce this new section.

Something like:

`### Workaround using Webpack`

2022-02-17 20:57 UTC, scallywag commented
Hi, thanks for the review! Please see the updated changes.

2022-06-08 23:00 UTC, mdo commented
This will need to be updated given the new Webpack guide we shipped in v5.2.0. Any chance you want to take a crack at that?

2022-06-09 05:39 UTC, charlesroelli commented
Sure, I will have a go at it.

2022-06-15 19:50 UTC, closed without merging