New CSS variable for Navbars
twbs/bootstrap pull request #35829
Opened 2022-02-11 10:50 UTC by louismaximepiton

Adding a new CSS variable in order to be more flexible.

2022-02-11 11:26 UTC, julien-deramond commented on scss/_variables.scss
> +$navbar-brand-font-size:            $font-size-lg !default;
You can remove this line. `$navbar-brand-font-size` already exists line 1077.

2022-02-11 12:22 UTC, ffoodd requested changes
Simple change pointed out by @julien-deramond but apart from that, it's a nice addition. Thanks!

2022-02-11 12:22 UTC, ffoodd commented on scss/_variables.scss
> +$navbar-brand-font-size:            $font-size-lg !default;
```suggestion
```

2022-02-11 12:23 UTC, ffoodd approved these changes

2022-02-17 19:22 UTC, mdo approved these changes

2022-02-17 19:25 UTC, merged