Bikeshedding lint
twbs/bootstrap pull request #36048
Opened 2022-03-21 20:33 UTC by tkrotoff

- no need to import with .js extension
- use destructuring
- use template literals

Discovered this while playing with the code

2022-03-28 12:55 UTC, WinterSilence commented on js/tests/unit/util/config.spec.js
> +      }).toThrowError(TypeError, `${obj.constructor.NAME.toUpperCase()}: Option "parent" provided type "number" but expected type "(string|element)".`)
redundant changes: template strings work slower and and don't give any pros in current case

2022-06-14 20:40 UTC, tkrotoff commented
Any news?

2022-07-23 14:00 UTC, tkrotoff commented
Any news?

2022-10-03 13:34 UTC, mdo commented
@GeoSot @XhmikosR Thoughts on this?

2022-10-03 13:53 UTC, GeoSot requested changes

2022-10-03 13:53 UTC, GeoSot commented on js/src/util/focustrap.js
> -  _handleFocusin(event) {
is like this on purpose 0c3dfe104b520d6ce466f265bf60c6d74785972e

2022-10-03 13:53 UTC, GeoSot commented on js/src/util/index.js
> +  [transitionDuration] = transitionDuration.split(',');
the initial version is still easier for the eye ;)

2022-10-03 15:41 UTC, closed without merging