Add table tags (table, td, th, tr, colgroup)
twbs/bootstrap pull request #36408
Opened 2022-05-20 11:37 UTC by dev-ph1l

Issue: #36399

Added table tags and common attributes (span, colspan, scope, rowspan) in order to be able to use them in tooltips.

2022-09-01 01:04 UTC, mdo commented
@XhmikosR @GeoSot Wondering if there was a reason for not including any of these?

2022-09-08 05:06 UTC, XhmikosR commented
No reason, I'm not sure these are so common. We should check what Angular has first.

2022-12-29 13:39 UTC, patrickhlauke requested changes

2022-12-29 13:39 UTC, patrickhlauke commented on js/src/util/sanitizer.js
> +  table: ['span'],
`span` is incorrect here

2022-12-29 13:39 UTC, patrickhlauke commented on js/src/util/sanitizer.js
>    col: [],
add `span` attribute

2022-12-29 13:39 UTC, patrickhlauke commented on js/src/util/sanitizer.js
> +  td: ['colspan', 'rowspan'],
add `headers` attribute

2022-12-29 13:39 UTC, patrickhlauke commented on js/src/util/sanitizer.js
> +  th: ['scope'],
add `abbr`, `colspan`, `headers`, `rowspan`

2022-12-29 13:39 UTC, patrickhlauke commented on js/src/util/sanitizer.js
>    u: [],
also add elements `thead`, `tbody`, `tfoot`, and `caption` ?

2022-12-29 13:39 UTC, patrickhlauke commented
in principle, i'm in favour of this PR

2023-03-23 08:40 UTC, XhmikosR commented
@GeoSot are these covered by tests? I.e. shouldn't we need to add the new elements to tests?

Otherwise, if you agree, we could land this.

2023-03-23 08:42 UTC, XhmikosR commented
Actually, NVM, I just read @patrickhlauke comments.

@dev-ph1l please make a new PR addressing the comments and make sure that the new changes are added in tests.

2023-03-23 08:42 UTC, closed without merging