Update navbars example to include a centered nav with utilities
twbs/bootstrap pull request #36523
Opened 2022-06-07 17:19 UTC by mdo

Addresses #36486.

2022-06-08 15:17 UTC, SamuelMiller commented
In the above example, the entire navbar collapses. I think there may be a simpler approach to getting a truly centered Navbar with left and right align-items. See my reply, which includes a Codepen example of the basic concept: https://github.com/twbs/bootstrap/discussions/36486#discussioncomment-2903439). 

Also, I would follow the example navbarTogglerDemo02 where only the menu and right-align item collapses, not the navbar-brand: https://getbootstrap.com/docs/5.2/components/navbar/#content

2022-06-09 16:41 UTC, julien-deramond requested changes
This new example LGTM! Just a proposal to change the `aria-label`.
IDK if adding another example where only the menu and right-align item collapses and not the navbar-brand is relevant.

2022-06-09 16:41 UTC, julien-deramond commented on site/content/docs/5.2/examples/navbars/index.html
> +    <nav class="navbar navbar-expand-lg bg-light rounded" aria-label="Twelfth navbar example">
```suggestion
    <nav class="navbar navbar-expand-lg bg-light rounded" aria-label="Thirtheenth navbar example">
```

2022-06-09 23:22 UTC, SamuelMiller commented
> Also, see my codepen example for a potentially different approach to center the menu, using flex-1 on both left and right items only using the BS class "col" without specifying a number suffix. [#36486 (comment)](https://github.com/twbs/bootstrap/discussions/36486#discussioncomment-2903439)

I have provided a Codepen of this approach applied to a Bootstrap navbar. See comment, https://github.com/twbs/bootstrap/discussions/36486#discussioncomment-2917883

2022-10-22 21:03 UTC, merged