Added new example in `examples/features` page.
twbs/bootstrap pull request #36660
Opened 2022-07-03 03:44 UTC by thevipinmishra

2022-07-03 18:22 UTC, julien-deramond commented
Before starting a code review, do you consider this new example acceptable in terms of design @mdo?

2022-07-03 18:32 UTC, thevipinmishra commented
> Before starting a code review, do you consider [this new example](https://deploy-preview-36660--twbs-bootstrap.netlify.app/docs/5.2/examples/features/) acceptable in terms of design @mdo?

Is there any guidelines for the examples? In terms of design? 🙂

I'm thinking about adding a few more examples.

2022-07-08 02:15 UTC, thevipinmishra commented
Can I please have any update on this? 

I am happy to make any changes if somehow this examples doesn't fit. :)

@julien-deramond

2022-07-19 20:24 UTC, mdo commented on site/content/docs/5.2/examples/features/features.css
> +}
```suggestion
}

```

2022-07-19 20:24 UTC, mdo commented on site/content/docs/5.2/examples/features/index.html
> +            <a href="#" class="btn btn-primary btn-lg">Primary</a>
Nitpick: expand the text in the button for more accurate real world use.

```suggestion
            <a href="#" class="btn btn-primary btn-lg">Primary button</a>
```

2022-07-19 20:24 UTC, mdo commented on site/content/docs/5.2/examples/features/index.html
> +    <div class="row row-cols-1 row-cols-md-2 align-items-md-center g-4 py-5">
Changing to `g-5` for more space.

```suggestion
    <div class="row row-cols-1 row-cols-md-2 align-items-md-center g-5 py-5">
```

2022-07-19 20:24 UTC, mdo commented
Always down for more example snippets! Handful of code quality and consistency things here to address first though :).

2022-07-21 02:54 UTC, thevipinmishra commented
Hey @mdo,

I've fixed all the issues you pointed out, had some issues with the `.editorconfig` on my VS Code but It worked out fine on Sublime Text.

Thanks a lot for reviewing this. I'm planning to contribute with more examples! 😊

2022-07-24 15:30 UTC, patrickhlauke requested changes

2022-07-24 15:30 UTC, patrickhlauke commented on site/content/docs/5.2/examples/features/index.html
> +        <h2 class="fw-bold">Left-aligned title explaining these awesome features</h2>
in light of https://github.com/twbs/bootstrap/pull/36829 and keeping a more sensible heading structure, could you change this to an `<h3>` ?

2022-07-24 15:30 UTC, patrickhlauke commented on site/content/docs/5.2/examples/features/index.html
> +          <h3 class="fw-semibold mb-0">Featured title</h3>
in light of https://github.com/twbs/bootstrap/pull/36829 and keeping a more sensible heading structure, could you change this and all subsequent ones to `<h4>` ?

2022-07-24 15:38 UTC, thevipinmishra commented
Just pushed the required changes!

Thanks for the heads up, will surely take care of this in future!

2022-07-24 18:15 UTC, patrickhlauke commented
Perfect, thank you @thevipinmishra

2022-07-24 18:16 UTC, patrickhlauke approved these changes

2022-08-03 21:53 UTC, mdo approved these changes

2022-08-04 04:52 UTC, merged