Offcanvas:  activate focustrap when backdrop is enabled
twbs/bootstrap pull request #36717
Opened 2022-07-11 08:54 UTC by GeoSot

closes #36596

2022-07-12 05:21 UTC, julien-deramond commented
Added https://github.com/twbs/bootstrap/pull/36717/commits/658045e9aa70ecd9ce98c838e2c69b3acc171f7c to tackle the 3rd point from the issue:

> Also noticed that focus is not moved to either of the off-canvases (the docs nav, and the general nav), but remains on the toggle buttons. Not looked at the markup in depth, but suspect a tabindex="-1" is missing on them (compare to the working off-canvas examples https://getbootstrap.com/docs/5.2/components/offcanvas/).

To test it in the docs, simply focus the main header (keyboard), open both menus with 'Enter' and then press to 'Escape' to close them. 'Escape' didn't do anything before since offcanvases didn't get the focus. Now it's working.

2022-07-12 05:28 UTC, julien-deramond commented
If I have well understood the 2nd point in the issue, it is safe to remove `aria-expanded="false"` from the `.navbar-toggler`s in the docs since offcanvases won't change the status and make an `aria-expanded="true"`.
Done via https://github.com/twbs/bootstrap/pull/36717/commits/d8f192dc9451957efb48057f43e98085c57270df.

2022-07-12 05:37 UTC, julien-deramond approved these changes
JS part LGTM! I've added 2 commits to handle 2 other points mentioned in the issue. This PR will need also a review from @patrickhlauke.

2022-07-13 07:33 UTC, patrickhlauke requested changes

2022-07-13 07:36 UTC, patrickhlauke commented
Looking good, and correctly addresses the issue https://github.com/twbs/bootstrap/issues/36596

At a higher level though, I'm wondering if we should just always enable focus trapping? Or, if we *do* want to allow non-modal offcanvases, we should document this clearly in the docs (currently it seems the docs are silent about focus behaviour at all) and also make sure that `aria-modal="true"` is only added when it's intended to be a modal offcanvas

2022-07-13 07:58 UTC, GeoSot commented on js/tests/unit/offcanvas.spec.js
> +    it('should trap focus if scroll is allowed & backdrop is enabled', () => {
```suggestion
    it('should trap focus if scroll is allowed OR backdrop is enabled', () => {
```

2022-07-13 08:00 UTC, GeoSot commented
>  At a higher level though, I'm wondering if we should just always enable focus trapping? Or, if we do want to allow non-modal offcanvases, we should document this clearly in the docs (currently it seems the docs are silent about focus behaviour at all) and also make sure that aria-modal="true" is only added when it's intended to be a modal offcanvas


Either way, an offcanvas that doesn't scroll or has a backdrop, behaves like modal, so I think is right for know.
BUT yes, we may, can discuss it for next releases

2022-07-14 01:43 UTC, patrickhlauke approved these changes

2022-07-14 09:06 UTC, merged