Add accNames to all progress bar examples
twbs/bootstrap pull request #36732
Opened 2022-07-13 12:57 UTC by patrickhlauke

* also expands advice in progress.md, explicitly mentions giving them an accName, and includes the callout about using color to convey meaning
* updates cheat sheets, but note that for the RTL one, my arabic is...lacking. we should get somebody who knows what they're doing to translate those `aria-label`s properly

Closes #36714

2022-07-13 16:15 UTC, julien-deramond requested changes
LGTM! Thanks for this PR @patrickhlauke.
Just a small change proposed for consistency.
Regarding the arabic version (RTL) we could maybe ask in the Slack general channel for some translation if anyone can help use in the community :shrug:

2022-07-13 16:15 UTC, julien-deramond commented on site/content/docs/5.2/examples/cheatsheet-rtl/index.html
> +          <div class="progress-bar bg-success w-25" aria-label="Success example with label" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
```suggestion
          <div class="progress-bar bg-success w-25" role="progressbar" aria-label="Success example with label" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
```
Was OK but just for consistency.

2022-07-13 18:36 UTC, mdo approved these changes

2022-07-13 18:45 UTC, julien-deramond approved these changes

2022-07-13 20:11 UTC, julien-deramond commented
> Can I paste the translations here? @julien-deramond

Yes sure. Thanks a lot <3

2022-07-13 21:15 UTC, AqeelAT commented
- "Example with label" -> "مثال مع عنوان"
- "Success example with label" -> "مثال ناجح مع عنوان"
- "Info example with label" -> "مثال توضيح مع عنوان"
- "Warning example with label" -> "مثال تنبيه مع عنوان"
- "Danger example with label" -> "مثال خطر مع عنوان"
- "Segment one - default example" -> "القسم الأول - مثال افتراضي"
- "Segment two - animated striped success example" -> "القسم الثاني - مثال ناجح مقلّم متحرك"

Sorry for the delay.
Let me know if there is anything else I can do to help with bootstrap's RTLization.

@julien-deramond @mdo

2022-07-13 21:31 UTC, merged

2022-07-14 00:16 UTC, patrickhlauke commented
wonderful, thank you @AqeelAT