Improve example of .flex-wrap and -reverse
twbs/bootstrap pull request #37279
Opened 2022-10-10 06:52 UTC by naitsirch

### Description

Added numbers to the labels in the example of `.flex-wrap` and `.flex-wrap-reverse` to make it more clear what happens and how `.flex-wrap-reverse` works.

### Motivation & Context

The current example of `.flex-wrap` and `.flex-wrap-reverse` does not really show the difference between those two utilities, because every item is labelled 'Flex item'.

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2022-10-10 12:53 UTC, julien-deramond requested changes
It might be useful to add those numbers to understand what happens with `.flex-wrap-reverse`. @mdo thoughts?

2022-10-11 06:20 UTC, naitsirch commented on site/content/docs/5.2/utilities/flex.md
> +    <div class="p-2">Flex item1</div>
I have updated the PR according to your suggestion ;-)

2022-10-11 06:26 UTC, julien-deramond approved these changes

2022-10-12 18:45 UTC, mdo approved these changes

2022-10-12 18:45 UTC, merged