Add new link utilities, icon link helper, and update colored link helpers
twbs/bootstrap pull request #37762
Opened 2022-12-29 21:30 UTC by mdo

Fun update for links in Bootstrap with a few new changes across the project...

### New `.icon-link` helper

This allows you to immediately pair any Bootstrap Icon with a hyperlink and have it spaced, aligned, and styled properly. Includes support for icons before or after the text, and includes a basic hover state. There's opportunity for future hover states here, too. _Might make more sense as a component?_

<img width="815" alt="CleanShot 2022-12-29 at 12 57 29@2x" src="https://user-images.githubusercontent.com/98681/210010569-df8174b2-d17c-4e48-8a1f-7cda4f9f98bf.png">

### Color links are now built with CSS variables

Instead of resetting the `color` property, we reset the `--bs-link-color-rgb` values. I've also added a new `text-decoration-color` property to these helpers that defaults to the current link color in `rgb` form with `--bs-link-underline-opacity` as the alpha layer (defaulting to `1`). This leads me to the next update...

### Introducing several new link utilities

To help modify icon links, colored links, and even regular links, we have new `.link-opacity-*` to change the alpha transparency, `.link-offset-*` to change the distance of the underline, `.link-underline-*` to change the underline color`, and `.link-underline-opacity-*` to change the underline alpha transparency. The link opacity and link underline opacity utilities also have a predefined `:hover` variant as well.

<img width="819" alt="CleanShot 2022-12-29 at 12 57 57@2x" src="https://user-images.githubusercontent.com/98681/210010573-111f41ca-3d93-442b-96bc-dea2c9e308a5.png">

<img width="816" alt="CleanShot 2022-12-29 at 12 58 11@2x" src="https://user-images.githubusercontent.com/98681/210010575-44a6a990-dc2c-451a-b961-5f8a4c025196.png">

<img width="813" alt="CleanShot 2022-12-29 at 12 58 18@2x" src="https://user-images.githubusercontent.com/98681/210010580-b8d80f46-6249-44d9-9638-72d1a0e28c2f.png">

<img width="812" alt="CleanShot 2022-12-29 at 12 58 23@2x" src="https://user-images.githubusercontent.com/98681/210010599-cc826455-25e9-4d9c-adc4-07c5ea98dc91.png">

<img width="810" alt="CleanShot 2022-12-29 at 12 58 30@2x" src="https://user-images.githubusercontent.com/98681/210010614-9addae84-5659-4bb8-a57a-1737d5e46bdf.png">

2023-01-02 19:48 UTC, mdo commented
Going to ship and iterate on this one :D.

2023-01-02 22:29 UTC, patrickhlauke commented
For the icon links:

- suggest doubling up the "Style on hover" to also apply on focus or `:focus-visible`
- i'd add a an info/accessibility callout that pretty much replicates what it says on https://icons.getbootstrap.com/#accessibility - and for the examples you have so far, probably safest to add an `aria-hidden="true"` on the `<svg>`

2023-01-02 22:34 UTC, patrickhlauke commented
For the link utilities:

- both for underline color and colored links, worth adding the https://getbootstrap.com/docs/5.3/components/buttons/#conveying-meaning-to-assistive-technologies callout
- for link opacity, worth calling out that obviously this will result in contrast ratios that are well below the WCAG minimum

2023-01-02 22:43 UTC, patrickhlauke requested changes
See accessibility-related comments

2023-01-03 03:40 UTC, mdo commented
All done, thanks @patrickhlauke! Just pushed an update to address all that.

2023-01-03 09:46 UTC, patrickhlauke requested changes, later dismissed

2023-01-03 09:46 UTC, patrickhlauke commented on site/content/docs/5.3/utilities/link.md
> +Change the alpha opacity of the link `rgba()` color value with utilities. Please be aware that changes to a color's opacity can result in contrast ratios below the WCAG minimum.
suggest rewording "in contrast ratios below the WCAG minimum" to something more like

`can lead to links with [*insufficient* contrast]({{< docsref "getting-started/accessibility#color-contrast" >}}).`

2023-01-03 09:46 UTC, patrickhlauke commented on site/content/docs/5.3/helpers/icon-link.md
> +Icons used here are likely to be purely decorative, which means they should be hidden from assistive technologies using `aria-hidden="true"`, as we've done in our examples. For icons that are more th
the suggestion to use `alt` only works when it's an `<img>` element. for `<svg>`s, you need *both* a `role="img"` and an `aria-label`. Maybe worth adding an example right here, a la `<svg ... role="img" aria-label="..."><use xlink:href="..."></use></svg>`

2023-01-04 03:50 UTC, mdo commented
Done and done!

2023-01-04 06:23 UTC, mdo commented
Going to merge now that feedback is addressed—happy to iterate on exact copy more in follow-ups! Thanks for the review in the mean time <3.

2023-01-04 06:23 UTC, merged

2023-06-02 05:09 UTC, Jehong-Ahn commented on scss/helpers/_icon-link.scss
> +  gap: .375rem;
Why rem over em?