Color mode: Customization of dark theme
twbs/bootstrap pull request #38136
Opened 2023-02-28 11:46 UTC by louismaximepiton

### Description

Add a new maps and associated Sass variables to allow a deeper customization.
Initialized it to what we have atm.

### Motivation & Context

Facilitate a deeper customization of the dark mode basic colors.

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- (NA) I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-38136--twbs-bootstrap.netlify.app/docs>

### Related issues

NA

2023-03-17 11:52 UTC, julien-deramond commented
I haven't had the time to review it yet but I agree that it's needed. For example, see https://github.com/orgs/twbs/discussions/38255. Or simply in our Orange fork where our primary color changes depending on light and dark mode for a11y (contrasts) reasons.

2023-09-12 09:19 UTC, julien-deramond requested changes
First batch of comments. I haven't checked everything yet.
As said in my previous comment, I think this is mandatory for our color modes so that projects can switch the color palette in dark mode for a11y reasons.

### Targeted version

IMO, this PR should be embedded directly in v5.3.2 instead of v5.4.0 in order to finalize the color modes in v5.3.x.

### Bundle size

_main_ branch:

```
PASS ./dist/css/bootstrap-reboot.css: 3.26KB < 3.5KB (gzip)
PASS ./dist/css/bootstrap-reboot.min.css: 3.1KB < 3.25KB (gzip)
PASS ./dist/css/bootstrap-utilities.css: 11.5KB < 11.75KB (gzip)
```

_main-lmp-dark-theme-customization_ branch:

```
PASS ./dist/css/bootstrap-reboot.css: 3.27KB < 3.5KB (gzip)
PASS ./dist/css/bootstrap-reboot.min.css: 3.11KB < 3.25KB (gzip)
PASS ./dist/css/bootstrap-utilities.css: 11.51KB < 11.75KB (gzip)
```

This slight size change is acceptable IMO and is coming from the generation of the following custom properties in dark mode (already existing in light mode):

```diff
>   --bs-primary: #0d6efd;
>   --bs-secondary: #6c757d;
>   --bs-success: #198754;
>   --bs-info: #0dcaf0;
>   --bs-warning: #ffc107;
>   --bs-danger: #dc3545;
>   --bs-light: #f8f9fa;
>   --bs-dark: #212529;
>   --bs-primary-rgb: 13, 110, 253;
>   --bs-secondary-rgb: 108, 117, 125;
>   --bs-success-rgb: 25, 135, 84;
>   --bs-info-rgb: 13, 202, 240;
>   --bs-warning-rgb: 255, 193, 7;
>   --bs-danger-rgb: 220, 53, 69;
>   --bs-light-rgb: 248, 249, 250;
>   --bs-dark-rgb: 33, 37, 41;
```

### Documentation

here’s probably something to update in:
* https://twbs-bootstrap.netlify.app/docs/5.3/customize/color-modes/#adding-theme-colors
* `$theme-colors-dark` should be added in docs/5.3/utilities/colors/#sass-maps (like `$theme-colors-text-dark` )
* migration guide

### Issues

Have you checked whether this PR can close some existing issues in the tracker?

2023-09-12 09:19 UTC, julien-deramond commented on scss/_variables-dark.scss
> +$primary-dark:                      $blue !default;
You probably want to use `$primary`, `$secondary`, etc. instead of `$blue`, `$gray-600` here in order to keep things synchronized.

2023-09-12 10:27 UTC, julien-deramond commented
Another thing that is pretty problematic and that will maybe force us to land this PR in v6 only is that when `$theme-colors-dark` primary color is modified to be green for example in dark mode, buttons are not modified because they are defined with a loop over `$theme-colors`. This loop should use custom properties instead, but doing that will break the compilation because of what we're doing in `button-variant()` mixin with the use of `tint-color`, `shade-color`.

As discussed, @louismaximepiton, I let you create a branch based on this one to check what would be the necessary changes in order to make the buttons dependent on `$theme-colors-dark` as well. From that, we'll decide if this PR could be merged or not in v5.

2026-03-08 00:33 UTC, mdo commented
Closing as stale.

2026-03-08 00:33 UTC, closed without merging