Add note about cancelling modal events to modal.md
twbs/bootstrap pull request #38411
Opened 2023-04-05 12:35 UTC by crespire

Adds a note about cancelling a modal event by `return event.preventDefault();`

### Description

Adds additional code snippet demonstrating cancelling a modal event.

### Motivation & Context
As someone new to Bootstrap, I didn't see this behaviour documented but it exists and was fixed with #34087 a few years ago.

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

Documentation change only.

### Related issues

2024-02-21 09:22 UTC, GeoSot approved these changes

2024-02-27 16:53 UTC, crespire commented on site/content/docs/5.3/components/modal.md
> +myModalEl.addEventListner('hide.bs.modal', event => {
```suggestion
myModalEl.addEventListener('hide.bs.modal', event => {
```

2024-02-27 16:55 UTC, julien-deramond requested changes
Thanks for the PR @crespire, there are some issues to fix with the content that are in my comments.

I'm wondering if it's not a duplicate of https://getbootstrap.com/docs/5.3/getting-started/javascript/#events. This concept is already explained generally in the JavaScript documentation.

2024-02-27 16:55 UTC, julien-deramond commented on site/content/docs/5.3/components/modal.md
> +myModalEl.addEventListner('hide.bs.modal', event => {
```suggestion
myModalEl.addEventListener('hide.bs.modal', event => {
```

2024-02-27 16:55 UTC, julien-deramond commented on site/content/docs/5.3/components/modal.md
> +}
```suggestion
})
```

2024-02-27 16:57 UTC, crespire commented
> Thanks for the PR @crespire, there are some issues to fix with the content that are in my comments.
> 
> I'm wondering if it's not a duplicate of https://getbootstrap.com/docs/5.3/getting-started/javascript/#events. This concept is already explained generally in the JavaScript documentation.

Thanks for the note. I'm happy to change this to a link reference instead if you feel that's more ideal. I think sometimes folks read sections of docs in isolation and details like this can get lost are can be a somewhat "unknown unknown" for more junior folks (like myself!).

Let me know what direction you want to take on this, but I've accepted your other suggestions!

2025-02-09 09:46 UTC, julien-deramond commented
What do you think if instead of the code example, we describe the event more precisely by referencing this use case like that:

```diff
diff --git a/site/content/docs/5.3/components/modal.md b/site/content/docs/5.3/components/modal.md
index 9f42f5aba..25b7f3a3a 100644
--- a/site/content/docs/5.3/components/modal.md
+++ b/site/content/docs/5.3/components/modal.md
@@ -856,7 +856,7 @@ Bootstrap's modal class exposes a few events for hooking into modal functionalit
 {{< bs-table >}}
 | Event | Description |
 | --- | --- |
-| `hide.bs.modal` | This event is fired immediately when the `hide` instance method has been called. |
+| `hide.bs.modal` | This event is fired immediately when the `hide` instance method has been called. Can be prevented by calling `event.preventDefault()`. See [JavaScript events documentation]({{< docsref "/getting-started/javascript#events" >}}) for more details on event prevention. |
 | `hidden.bs.modal` | This event is fired when the modal has finished being hidden from the user (will wait for CSS transitions to complete). |
 | `hidePrevented.bs.modal` | This event is fired when the modal is shown, its backdrop is `static` and a click outside of the modal is performed. The event is also fired when the escape key is pressed and the `keyboard` option is set to `false`. |
 | `show.bs.modal` | This event fires immediately when the `show` instance method is called. If caused by a click, the clicked element is available as the `relatedTarget` property of the event. |
```

It would keep the documentation DRY by referencing the general events documentation and make the hide prevention capability more discoverable.

2025-02-12 01:50 UTC, crespire commented
> What do you think if instead of the code example, we describe the event more precisely by referencing this use case like that:
> 
> ```diff
> diff --git a/site/content/docs/5.3/components/modal.md b/site/content/docs/5.3/components/modal.md
> index 9f42f5aba..25b7f3a3a 100644
> --- a/site/content/docs/5.3/components/modal.md
> +++ b/site/content/docs/5.3/components/modal.md
> @@ -856,7 +856,7 @@ Bootstrap's modal class exposes a few events for hooking into modal functionalit
>  {{< bs-table >}}
>  | Event | Description |
>  | --- | --- |
> -| `hide.bs.modal` | This event is fired immediately when the `hide` instance method has been called. |
> +| `hide.bs.modal` | This event is fired immediately when the `hide` instance method has been called. Can be prevented by calling `event.preventDefault()`. See [JavaScript events documentation]({{< docsref "/getting-started/javascript#events" >}}) for more details on event prevention. |
>  | `hidden.bs.modal` | This event is fired when the modal has finished being hidden from the user (will wait for CSS transitions to complete). |
>  | `hidePrevented.bs.modal` | This event is fired when the modal is shown, its backdrop is `static` and a click outside of the modal is performed. The event is also fired when the escape key is pressed and the `keyboard` option is set to `false`. |
>  | `show.bs.modal` | This event fires immediately when the `show` instance method is called. If caused by a click, the clicked element is available as the `relatedTarget` property of the event. |
> ```
> 
> It would keep the documentation DRY by referencing the general events documentation and make the hide prevention capability more discoverable.



> What do you think if instead of the code example, we describe the event more precisely by referencing this use case like that:
> 
> ```diff
> diff --git a/site/content/docs/5.3/components/modal.md b/site/content/docs/5.3/components/modal.md
> index 9f42f5aba..25b7f3a3a 100644
> --- a/site/content/docs/5.3/components/modal.md
> +++ b/site/content/docs/5.3/components/modal.md
> @@ -856,7 +856,7 @@ Bootstrap's modal class exposes a few events for hooking into modal functionalit
>  {{< bs-table >}}
>  | Event | Description |
>  | --- | --- |
> -| `hide.bs.modal` | This event is fired immediately when the `hide` instance method has been called. |
> +| `hide.bs.modal` | This event is fired immediately when the `hide` instance method has been called. Can be prevented by calling `event.preventDefault()`. See [JavaScript events documentation]({{< docsref "/getting-started/javascript#events" >}}) for more details on event prevention. |
>  | `hidden.bs.modal` | This event is fired when the modal has finished being hidden from the user (will wait for CSS transitions to complete). |
>  | `hidePrevented.bs.modal` | This event is fired when the modal is shown, its backdrop is `static` and a click outside of the modal is performed. The event is also fired when the escape key is pressed and the `keyboard` option is set to `false`. |
>  | `show.bs.modal` | This event fires immediately when the `show` instance method is called. If caused by a click, the clicked element is available as the `relatedTarget` property of the event. |
> ```
> 
> It would keep the documentation DRY by referencing the general events documentation and make the hide prevention capability more discoverable.

I think that's a good idea! I'm not tied to my proposed changes.

2025-02-12 17:42 UTC, julien-deramond approved these changes

2025-02-12 17:46 UTC, merged