Docs: add `shift-color()` usage example in sass customization page
twbs/bootstrap pull request #39435
Opened 2023-11-24 16:49 UTC by julien-deramond

### Description

This PR suggests adding a new `.custom-element-3` example in our Customize > Sass > Colors page to show how to use `shift-color()`.

### Motivation & Context

This is an enhancement that could be useful to folks when they are using this Sass function to show that the weight must be set in percentage too.

### Type of changes

- [ ] Docs enhancement (non-breaking change)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- (N/A) I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/docs/5.3/customize/sass/#colors

### Related issues

Closes #39432

2023-12-06 14:25 UTC, louismaximepiton requested changes

2023-12-09 21:35 UTC, mdo approved these changes

2023-12-12 07:01 UTC, julien-deramond commented on site/content/docs/5.3/customize/sass.md
I changed a little bit the suggested wording but added a precision in the description as suggested via https://github.com/twbs/bootstrap/pull/39435/commits/15056fdf102455882469fae047e88da88a057030. What do you think?

2023-12-12 07:03 UTC, louismaximepiton commented on site/content/docs/5.3/customize/sass.md
Sounds great to me, thanks for the change :)

2023-12-12 07:03 UTC, louismaximepiton approved these changes

2023-12-12 07:08 UTC, merged