Added documentation for using checkboxes to toggle collapse
twbs/bootstrap pull request #39767
Opened 2024-03-09 23:06 UTC by TommasoAllegretti

### Description

The Collapse documentation only talks about buttons and <a> elements as toggles. However, using checkboxes also works fine. Therefore, it should be pointed out in the docs that you can also use checkboxes as collapse toggles.

### Motivation & Context

As requested in issue #39728 

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### Related issues

#39728

2024-03-11 06:43 UTC, julien-deramond commented
I'd say that we shouldn't mention checkboxes specifically but rather make it understandable that collapse can be used with basically everything. For example, you can also use it with basic HTML elements such as `<code>`, `<div>`, etc.

```html
<code data-bs-toggle="collapse" data-bs-target="#collapseExample">Test from code</code>
<div data-bs-toggle="collapse" data-bs-target="#collapseExample" class="w-100 h-100 bg-warning">Test from div</div>
<div class="collapse" id="collapseExample" style="">
  <div class="card card-body">
    Some placeholder content for the collapse component. This panel is hidden by default but revealed when the user activates the relevant trigger.
  </div>
</div>
```

Maybe we can make it clearer in "How it works" that it works with everything and that buttons and links are used on this page because they would be the most common elements as triggers 🤷

2024-03-11 13:38 UTC, XhmikosR commented
Agreed, we are better off documenting the above. Let alone that the checkbox in this PR is hard to notice next to the buttons.

2024-05-02 22:09 UTC, TommasoAllegretti commented
Sorry for the delayed response, I followed your feedback and changed the documentation accordingly.
Please let me know if the documentation is now clear enough in explaining the possibility of using various different elements to toggle a collapse.

2024-05-24 21:37 UTC, patrickhlauke commented
as an aside, we probably don't want to suggest using an arbitrary non-focusable element, for accessibility reasons

2024-05-24 21:45 UTC, patrickhlauke requested changes

2024-05-24 21:45 UTC, patrickhlauke commented on site/content/docs/5.3/components/collapse.md
> +The collapse JavaScript plugin is used to show and hide content. Buttons, anchors and many other elements can be used as triggers that are mapped to specific elements you toggle. Collapsing an elemen
other *interactive*/*focusable* elements (while technically that's not required in the code, it'd be dangerous to suggest authors can just make anything a trigger, for accessibility reasons.

2024-05-24 21:45 UTC, patrickhlauke commented on site/content/docs/5.3/components/collapse.md
> +Generally, we recommend using a `<button>` with the `data-bs-target` attribute. While not recommended from a semantic point of view, you can also use an `<a>` link with the `href` attribute (and a `r
again, just having a `<div>` will make it an inaccessible control, so probably best not to suggest that.

2024-06-13 01:41 UTC, mdo commented
Agreed on the advice of only encouraging semantic elements for this kind of thing. Sure a checkbox can be used, and any other element, but I don't think that needs stating here. We encourage one thing—we don't need to encourage everything IMO. Anyone on the maintainer team though that feels strongly is free to overrule though :).

2024-06-13 01:41 UTC, closed without merging

2024-06-13 14:20 UTC, carlosmintfan commented
Are you sure? A checkbox looks much better design for deciding whether some elements in a list should be shown or not.