Dark theme fixes
twbs/bootstrap pull request #39989
Opened 2024-05-15 23:03 UTC by karlshea

### Description

* Allow `data-bs-theme="dark"` on parent element of `.navbar` to trigger `.navbar-dark` variables as described in the documentation.
* Allow `data-bs-theme="dark"` on parent or current element of `.dropdown-menu` to trigger `.dropdown-menu-dark` variables as described in the documentation.

### Motivation & Context

See #39984 

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### Related issues

#39984, #39291

2024-05-25 06:20 UTC, julien-deramond requested changes
Thanks for submitting a PR @karlshea 

I haven't looked at the code and the modifications that you suggest yet. However, I can see in the deployed version a rendering issue in the dark mode version of https://deploy-preview-39989--twbs-bootstrap.netlify.app/docs/5.3/components/navbar/#color-schemes, where the last navbar should render black texts instead of white:
<img width="773" alt="Screenshot 2024-05-25 at 08 18 13" src="https://github.com/twbs/bootstrap/assets/17381666/b10e76ff-78ed-4f53-9f4a-da15c31f9a14">

2024-05-25 07:01 UTC, karlshea commented
@julien-deramond I'm not sure how the last navbar could be fixed if the background color is set with a style tag, there doesn't seem to be anything to work off of there?

In 5.3 without this PR's change if I remove `bg-primary` from the second navbar and manually set the background color with a style the text also renders white in dark mode.

2024-05-25 07:10 UTC, julien-deramond commented
I've checked rapidly, but there is a forced `data-bs-theme="light"` (that should be displayed in the markup of the documentation, by the way). In this case, the color should be black since the light mode is forced.

I'll need to find the time to check all the existing PRs and issues at the same time regarding the color modes, because this could be also fixed automatically by https://github.com/twbs/bootstrap/pull/39295 if the `color:` is set by default (not the case right now).

2024-05-28 21:54 UTC, karlshea commented
Yeah I'm not really sure what to do here. Maybe CSS specificity is winning?

2026-06-27 20:40 UTC, mdo commented
v6 reworks the navbar onto the .theme-* token system with light-dark(), replacing the .navbar-dark/.navbar-light model this patches. Closing as superseded by the v6 rewrite.

2026-06-27 20:40 UTC, closed without merging