Simplify link styling using :is(), to avoid additional rule with :not().
twbs/bootstrap pull request #40439
Opened 2024-05-22 16:01 UTC by donquixote

### Description

Use a single rule with `a:is(...) {` instead of `a {` + `a:not(...)` for link styling.

### Motivation & Context

In `_reboot.scss` we have link styling that is immediately countered by a more specific rule to undo the styling on named anchors. The `:not()` part was introduced in #19402 and refined in #30726.

This is awkward and can be simplified.

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

(I shall review the points later)

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### Related issues

- #19402
- #30726

2024-05-22 16:28 UTC, julien-deramond commented
Thanks for this PR @donquixote 
Looks promising as an enhancement of the code base, but I'm afraid we can't use it right now based on our current [.browserslistrc](https://github.com/twbs/bootstrap/blob/main/.browserslistrc) and [what's mentioned in Caniuse for `:is()`](https://caniuse.com/?search=%3Ais).
However, this is something we could probably embed in v6 when we'll update this `.browserslistrc` with more recent browsers versions.

2024-05-22 16:46 UTC, donquixote commented
Alright, thanks for the quick response!

I don't have any investment in this atm, I just wanted to share this idea before I forget about it.

Btw, can we use `:not(:not())` in these browsers, to replace `:is()`?
Do you have any way to test if this would work?

2024-05-22 16:52 UTC, donquixote commented
I pushed a version with `:not(:not())`, in case you want to test it.
I don't have the possibility to test it myself atm.

2024-05-22 16:53 UTC, julien-deramond commented
> I pushed a version with `:not(:not())`, in case you want to test it. I don't have the possibility to test it myself atm.

Thanks for that. I changed the label to v5 instead of v6.
I'll try to find some time to test it with different combinations of browsers/OSs.

2024-05-22 16:56 UTC, donquixote commented
Btw we could use `:link` instead of `[href]`.
But I wanted to keep this as close as possible to the existing code.

2024-05-25 06:11 UTC, julien-deramond requested changes
Thanks for submitting this PR @donquixote 

I haven't looked at the code yet, but just in terms of rendering in the deployed documentation at https://deploy-preview-40439--twbs-bootstrap.netlify.app/, there are several regressions in the homepage:

1. These links shouldn't be underlined:
<img width="389" alt="Screenshot 2024-05-25 at 08 10 49" src="https://github.com/twbs/bootstrap/assets/17381666/d5f58878-7a75-4ff5-a81a-f6bf8d721511">

2. In this button, the text should have the right color and shouldn't be underlined:
<img width="246" alt="Screenshot 2024-05-25 at 08 11 13" src="https://github.com/twbs/bootstrap/assets/17381666/c1d7cfd8-5f5c-485c-9bb7-9b6db13aec81">

There are a lot of problems too in the side menu:

<img width="208" alt="Screenshot 2024-05-25 at 08 12 34" src="https://github.com/twbs/bootstrap/assets/17381666/68209347-4fda-4652-83dd-d4639bea146f">

_Note: tested only with macOS 14.4.1 / Firefox 126.0_

2024-07-02 04:25 UTC, closed without merging