button-group: Fix `btn-group-vertical` by using same rules as `btn-group`
twbs/bootstrap pull request #40488
Opened 2024-05-25 05:13 UTC by tordans

### Description

See https://github.com/twbs/bootstrap/issues/40487

The css conditions for vertical button groups was different from the regular button group.

When using the same conditions for the regular groups for the vertical group, the bug is fixed.

**Current CSS:**

See the `.btn-group>:not(.btn-check)+.btn` on the right

> <img width="1399" alt="Bildschirmfoto 2024-05-25 um 07 06 39" src="https://github.com/twbs/bootstrap/assets/111561/1d5c8e2b-3e22-4d9f-b021-32a35a660c2c">

**Modified CSS:**

> <img width="1385" alt="Bildschirmfoto 2024-05-25 um 07 08 03" src="https://github.com/twbs/bootstrap/assets/111561/567f3a15-646f-45f8-864f-796d602126ca">

I am assuming the css for the regular button group was improved at some point but not applied to the vertical button group at this point.

The second change is to add `> .btn.dropdown-toggle-split:first-child` to the `Reset rounded corners` section which is also copied down from the regular button group. I am not sure what that does but I think the same logic applies to assume that both button groups should behave the same.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] ~New feature (non-breaking change which adds functionality)~
- [ ] ~Refactoring (non-breaking change)~
- [ ] ~Breaking change (fix or feature that would change existing functionality)~

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### Related issues

- https://github.com/twbs/bootstrap/issues/40487

2024-05-25 05:54 UTC, julien-deramond requested changes
Thanks for catching the issue in the first place and then for submitting a PR @tordans 
I haven't checked out the code yet, but there's an issue with the rendering in the deployed version at https://deploy-preview-40488--twbs-bootstrap.netlify.app/docs/5.3/components/button-group/#vertical-variation; the top-right corner from the 2nd item in the vertical variation is rounded, and the left-bottom corner of the last item should be rounded.
<img width="134" alt="Screenshot 2024-05-25 at 07 53 00" src="https://github.com/twbs/bootstrap/assets/17381666/3532f48b-0c1a-46d0-a98e-9a10fe496ff8">
<img width="94" alt="Screenshot 2024-05-25 at 07 52 55" src="https://github.com/twbs/bootstrap/assets/17381666/835118f6-2191-4bf5-b37d-ca6d8dc1b95e">

2024-05-25 12:03 UTC, tordans reviewed
This change was not supposed to be in here. Will fix soon.

2024-05-25 12:03 UTC, tordans commented on scss/_button-group.scss
> +    @include border-start-radius(0);
```suggestion
    @include border-top-radius(0);
```

2024-05-25 12:40 UTC, PRERAKAGARWAL28 commented
Thanks for catching the issue in the first place and then for submitting a PR @tordans
I have resolved the issue. 
https://stackblitz.com/edit/jzsfzg?file=index.html

2024-05-25 12:57 UTC, tordans commented
> I haven't checked out the code yet, but there's an issue with the rendering in the deployed version at https://deploy-preview-40488--twbs-bootstrap.netlify.app/docs/5.3/components/button-group/#vertical-variation; the top-right corner from the 2nd item in the vertical variation is rounded, and the left-bottom corner of the last item should be rounded.

This is fixed now. The preview looks right to me, now.

2024-05-27 19:35 UTC, julien-deramond approved these changes
Thanks again for the PR, @tordans. It's really appreciated.

I've tested the rendering with several combinations of buttons and dropdowns, and it seems to work perfectly now. Even with some outlined versions, the rendering is acceptable. The following mention in the documentation is still valid, even if it shouldn't be too hard to adapt in the future:
> Split button dropdowns are not supported here.

The comment follows what exists already for the simple `.btn-group`, and the new code is scoped for `.btn-group-vertical` only. This makes it very isolated, without extra impacts on the rest of the code.

Regarding the documentation, having the dropdown in the first position will make it easier for us to maintain in the future and to spot potential regressions. We do lose a little bit of the logic behind the rendering of the set of dropdowns' variants (with two buttons in the middle), but I think it's OK. Otherwise, we could even drop the buttons. IMO, let's leave it as is. If other maintainers have stronger opinions, feel free to directly modify the code.

IMO, it's safe to merge. @twbs/css-review, I'll leave it open for now until you can double-check if you want.

2024-05-29 06:42 UTC, louismaximepiton approved these changes
Feels right to me, couldn't find any regression while playing with it. Thanks for your contribution!

2024-05-30 05:49 UTC, merged