Disabled buttons get colored error fixed
twbs/bootstrap pull request #40608
Opened 2024-07-06 08:38 UTC by Riyazul555

### Description

### Motivation & Context

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [ ] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### Related issues

Closes issue #40557

2024-07-06 08:51 UTC, julien-deramond requested changes
Thanks for submitting a PR @Riyazul555 
I haven't looked at the issue in detail, but here's already a first quick feedback.
There's something to do with `--#{$prefix}btn-disabled-opacity` as in your version, this CSS variable is no more used at all.
And you also set `background-color` two times for the same rule.

2024-07-06 15:09 UTC, Riyazul555 commented
Ok I got it @julien-deramond 
I have made new changes 
Please check out 
Thanks

2024-07-11 13:29 UTC, rr-it commented
This PR makes the ligtness of the buttons fixed. The buttons should fade into the background , so the lightness has to change depending on which background a button is put on.
So this does not close the mentioned issue.

@Riyazul555 There is already an open PR for the issue.  Please see https://github.com/twbs/bootstrap/pull/40559  -feedback welcome!

2025-04-09 06:12 UTC, mdo commented
Closing as stale.

2025-04-09 06:12 UTC, closed without merging