Docs: Modernize footer design and improve visual hierarchy
twbs/bootstrap pull request #40969
Opened 2024-10-22 18:46 UTC by SuhaniBh

### Description
The current Bootstrap footer design, while functional, can benefit from modern design principles to enhance visual appeal and user experience. This PR modernizes the footer with improved spacing, typography, and visual hierarchy while maintaining its core functionality.

### Motivation & Context
This change improves the visual presentation of Bootstrap's documentation footer by:
- Enhancing readability with better spacing and typography
- Implementing a more modern color scheme with subtle backgrounds
- Adding smooth hover interactions for better user feedback
- Improving mobile responsiveness and content organization
- Maintaining accessibility standards while upgrading the design

### Type of changes
[x] New feature (non-breaking change which adds functionality)
[ ] Bug fix (non-breaking change which fixes an issue)
[ ] Refactoring (non-breaking change)
[ ] Breaking change (fix or feature that would change existing functionality)

### Checklist
[x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/github/CONTRIBUTING.md)
[x] My code follows the code style of the project (using npm run lint)
[x] My change introduces changes to the documentation
[x] I have updated the documentation accordingly
[x] I have added tests to cover my changes
[x] All new and existing tests passed

### Live previews
- <https://deploy-preview-[your_pr_number]--twbs-bootstrap.netlify.app/>
- Direct link to footer section: <https://deploy-preview-[your_pr_number]--twbs-bootstrap.netlify.app/#footer>

### Related issues
N/A - Enhancement proposal for footer design modernization

2024-10-23 05:44 UTC, julien-deramond requested changes
Thanks for creating the PR, @SuhaniBh!

There are a few code issues that need addressing, but let's hold off on fixing them until we hear back from @mdo (who designs Bootstrap) about the design. We don't want to spend time on code adjustments if the rendering doesn't meet the design expectations.

On a personal note, though I'm not a designer, I find the light version a bit too colorful. I also think the logo and 'Bootstrap' text shouldn't be blue.

2024-10-23 05:44 UTC, julien-deramond commented on site/layouts/partials/footer.html
> +<style>
This page can't use `<style>`, the CSS part should be put inside the corresponding (S)CSS file.

2024-10-23 05:44 UTC, julien-deramond commented on site/layouts/partials/footer.html
> +          <li class="mb-3"><a href="https://stackoverflow.com/questions/tagged/bootstrap-5" target="_blank" rel="noopener" class="text-decoration-none text-body-secondary hover-primary">Stack Overflo
For the links style, it should be handled in the corresponding (S)CSS file, not by repeating classes all over the file.

2024-10-23 05:44 UTC, julien-deramond commented on site/layouts/partials/footer.html
> +      <!-- Brand Column -->
The comments added in this PR can be removed.

2024-12-04 05:27 UTC, closed without merging

2024-12-04 05:27 UTC, mdo commented
Thanks, but we'll pass.